Repository freeorion/freeorion, pull requests merged in 2018-07, with the labels that each got.

#2179 Validate string as utf8 in Font::DetermineLines
  GG/src/Font.cpp
Labels: category:bug, component:UI, status:cherry-pick for release

#2196 [tests] Fix incorrect sorting
  default/python/tests/AI/test_savegame_manager.py
Labels: category:refactoring, component:AI

#2195 [logger] use same format for python and cpp loggers
  python/LoggingWrapper.cpp
Labels: category:bug, component:internal

#2178 fix some MilitaryAI calculations
  default/python/AI/CombatRatingsAI.py
  default/python/AI/MilitaryAI.py
Labels: category:bug, component:AI, status:cherry-pick for release

#2176 in 0.4.8 Use 'Unknown Design' for unknown shipdesigns in Sitreps
  util/VarText.cpp
Labels: category:bug, component:UI

#2128 Sets launch capacity of FT_BAY_1 to 4 if FT_HANGAR_1 is aboard.
  default/python/AI/AIDependencies.py
  default/python/AI/ShipDesignAI.py
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_1.focs.txt
Labels: category:tweak, component:AI, component:content scripting, component:game mechanic

#2197 Fix industry/research meter growth (#2183 & #2185)
  default/scripting/species/common/general.macros
  default/scripting/species/common/industry.macros
  default/scripting/species/common/population.macros
  default/scripting/species/common/research.macros
  default/stringtables/en.txt
Labels: category:bug, component:content scripting, status:cherry-pick for release

#2208 Upgrade TravisCI pytest version to 3.6.3
  .travis.yml
Labels: category:tweak, component:infrastructure

#2192 Address vector element access wrt _GLIBCXX_ASSERTIONS
  GG/src/GLClientAndServerBuffer.cpp
  GG/src/ListBox.cpp
Labels: category:bug, component:internal

#2198 Improve AI tests
  default/python/tests/AI/character_test/character_test.py
  default/python/tests/AI/test_read_only_dict.py
  default/python/tests/AI/test_savegame_manager.py
Labels: category:refactoring, component:AI

#2199 Disable (force true) default-design option, for 0.4.8
  UI/ClientUI.cpp
  UI/DesignWnd.cpp
Labels: category:bug, component:UI, component:internal, status:cherry-pick for release

#2206 Use generic_wstring on Windows in PathToString
  util/Directories.cpp
Labels: category:bug, component:internal, component:network, status:cherry-pick for release

#2200 Add warning for excess stockpile contributions
  UI/MapWnd.cpp
  UI/ResourceBrowseWnd.h
  default/data/art/icons/buttons/warned_resource.png
  default/data/art/icons/buttons/warned_resource_clicked.png
  default/data/art/icons/buttons/warned_resource_mouseover.png
Labels: category:bug, category:tweak, component:UI, status:cherry-pick for release, status:help wanted, status:testing requested

#2202 Change Planet Suitiability alignment to spaces, add logging
  UI/EncyclopediaDetailPanel.cpp
  default/stringtables/en.txt
  default/stringtables/fr.txt
Labels: category:bug, component:UI, status:cherry-pick for release

#2212 Changelog update
  ChangeLog.md
Labels: category:tweak, component:technical docs

#2217 Fix ResourceSupplyConnectedByEmpire condition
  universe/Condition.cpp
Labels: category:bug, component:game mechanic, component:internal, status:cherry-pick for release

#2229 Reject updates to MPLobby with disconnected players or duplicated player IDs
  server/ServerFSM.cpp
Labels: category:bug, component:network

#2209 [tests] Update instructions
  default/python/tests/README.md
Labels: category:tweak, component:AI, component:technical docs

#2226 Fix ValueRef error doing a pedia lookup of a ship after learning SHP_ADV_DAM_CONT.
  default/scripting/techs/ship_parts/damage_control/SHP_ADV_DAM_CONT.focs.txt
Labels: category:bug, component:content scripting

#2230 Add options to manage cookies expire time.
  default/stringtables/en.txt
  network/ServerNetworking.cpp
  server/dmain.cpp
Labels: category:feature, component:network
