Repository freeorion/freeorion, pull requests merged in 2018-03, with the labels that each got.

#2023 BT_STOCKPILE
  Empire/Empire.cpp
  Empire/Empire.h
  UI/BuildDesignatorWnd.cpp
  UI/ProductionWnd.cpp
  default/stringtables/en.txt
  python/EnumWrapper.cpp
  universe/Enums.h
  util/Order.cpp
Labels: category:feature, component:game mechanic

#2016 Use default logging
  default/python/AI/AIDependencies.py
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/ColonisationAI.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/DiplomaticCorp.py
  default/python/AI/ExplorationAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/FreeOrionAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/MoveUtilsAI.py
  default/python/AI/PlanetUtilsAI.py
  default/python/AI/PriorityAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/TechsListsAI.py
  default/python/AI/character/character_module.py
  default/python/AI/character/character_strings_module.py
  default/python/AI/fleet_orders.py
  default/python/AI/pathfinding.py
  default/python/AI/turn_state.py
  default/python/AI/universe_object.py
  default/python/auth/auth.py
  default/python/common/configure_logging.py
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/interface_inspector.py
  default/python/stub_generator/parse_docs.py
  default/python/turn_events/turn_events.py
  default/python/universe_generation/universe_generator.py
Labels: category:refactoring, component:AI, status:help wanted

#2035 Fix AI debug chat when logging framework is used
  default/python/AI/freeorion_tools/interactive_shell.py
Labels: category:bug, component:AI, component:infrastructure

#2037 Sa/cleanup
  default/python/AI/AIstate.py
  default/python/AI/PriorityAI.py
  default/python/tox.ini
  default/python/universe_generation/universe_generator.py
Labels: category:refactoring, component:AI

#2038 Update readme
  default/python/README.md
  default/python/tox.ini
Labels: category:tweak, component:AI, component:infrastructure

#2032 Fix AI mock interface typehinting for getVisibilityTurnMap
  default/python/AI/freeOrionAIInterface.pyi
  default/python/stub_generator/generate_stub.py
Labels: category:bug, component:AI, component:infrastructure

#2034 Add a context manager and decorator to switch between python log levels
  default/python/AI/freeorion_tools/_freeorion_tools.py
Labels: category:feature, component:AI, component:infrastructure

#2036 Replace print statements with logger calls in ShipDesignAI.py
  default/python/AI/ShipDesignAI.py
Labels: category:refactoring, component:AI

#2047 Fixes test compilation with newer SDL.
  GG/test/acceptance/CMakeLists.txt
Labels: category:tweak, component:build system

#2051 Don't let new ships/monsters blockade
  Empire/Empire.cpp
  universe/Fleet.cpp
  universe/Fleet.h
Labels: category:tweak, component:game mechanic

#2018 Augment effect tracing
  universe/Effect.cpp
  universe/Effect.h
  universe/Universe.cpp
Labels: category:tweak, component:content scripting, component:internal

#2058 appveyor: Setup skip options
  appveyor.yml
Labels: category:tweak, component:infrastructure

#2022 Run python linter on travis
  .travis.yml
  default/python/README.md
Labels: category:refactoring, component:infrastructure

#2061 Enclose oarchive scope when used with stringstream
  network/Message.cpp
Labels: category:bug, component:network

#2041 BT stockpile review changes
  Empire/Empire.cpp
  Empire/Empire.h
  Empire/ProductionQueue.cpp
  UI/BuildDesignatorWnd.cpp
  UI/ProductionWnd.cpp
  default/stringtables/en.txt
  default/stringtables/fr.txt
  default/stringtables/ru.txt
Labels: category:tweak, component:game mechanic, component:internal

#2054 Allow authenticated player to replace his connection without stopping the game.
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
Labels: category:feature, component:network
