Repository freeorion/freeorion, pull requests merged in 2018-12, with the labels that each got.

#2326 Fix monster shield regeneration (#2325)
  default/scripting/ship_hulls/monster/SH_BLACK_KRAKEN_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_BLOATED_JUGGERNAUT_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_COSMIC_DRAGON_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_DAMPENING_CLOUD_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_DRONE_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_FLOATER.focs.txt
  default/scripting/ship_hulls/monster/SH_GUARD_0_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_GUARD_1_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_GUARD_3_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_GUARD_MONSTER_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_IMMOBILE_FACTOR.focs.txt
  default/scripting/ship_hulls/monster/SH_JUGGERNAUT_1_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_JUGGERNAUT_2_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_JUGGERNAUT_3_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRAKEN_1_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRAKEN_2_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRAKEN_3_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRILL_1_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRILL_2_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRILL_3_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRILL_4_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_NEBULOUS.focs.txt
  default/scripting/ship_hulls/monster/SH_PSIONIC_SNOWFLAKE_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_SNOWFLAKE_1_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_SNOWFLAKE_2_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_SNOWFLAKE_3_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_STRONG_MONSTER_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_TREE_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_WHITE_KRAKEN_BODY.focs.txt
  default/scripting/ship_hulls/monster/monster.macros
  default/scripting/species/common/shields.macros
Labels: category:bug, component:content scripting, status:cherry-pick for release

#2309 Translated new races (Sly, Replicon, Fulver), other minor updates.
  default/stringtables/ru.txt
Labels: category:feature, component:translation, status:work in progress

#2313 Status empire icons
  default/data/art/icons/allied.png
  default/data/art/icons/peace.png
  default/data/art/icons/war.png
Labels: category:feature, component:art music text assets, status:work in progress

#2332 Fix AI considerations re lost fleets
  default/python/AI/AIstate.py
Labels: category:bug, component:AI

#2334 Limit AI periodic resetting of military missions
  default/python/AI/MilitaryAI.py
Labels: category:bug, component:AI, status:cherry-pick for release

#2333 Reduce AI invasion overkill/waste
  default/python/AI/fleet_orders.py
  default/python/AI/target.py
Labels: category:bug, component:AI, status:cherry-pick for release

#2335 Only select fleets with sufficient fuel for a mission
  default/python/AI/FleetUtilsAI.py
  default/python/AI/MilitaryAI.py
Labels: category:bug, component:AI, status:cherry-pick for release

#2298 Add debugging helper function assertion_fails
  default/python/AI/FreeOrionAI.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/tests/AI/test_assertion_fails.py
Labels: category:feature, component:content scripting, component:internal

#2338 Misc AI fixes
  default/python/AI/AIDependencies.py
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/MilitaryAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/TechsListsAI.py
  default/python/AI/fleet_orders.py
Labels: category:bug, component:AI, status:cherry-pick for release

#2253 Always Enable Screensaver
  GG/src/SDL/SDLGUI.cpp
Labels: category:tweak, component:UI
