Repository freeorion/freeorion, pull requests merged in 2018-02, with the labels that each got.

#1960 AI support for playing SLY
  default/python/AI/PriorityAI.py
  default/python/AI/ProductionAI.py
Labels: category:tweak, component:AI, status:work in progress

#1981 [cleanup] Cleanup auth
  default/python/auth/auth.py
Labels: category:refactoring, component:AI

#1984 [cleanup] cleanup ai
  default/python/AI/ResearchAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/character/character_module.py
  default/python/tox.ini
Labels: category:refactoring, component:AI

#1980 Increase colony base hull cost to 3
  default/scripting/ship_hulls/SH_COLONY_BASE.focs.txt
Labels: category:tweak, component:content scripting

#1977 Planet habitable size
  UI/ObjectListWnd.cpp
  default/python/AI/AIDependencies.py
  default/python/AI/ColonisationAI.py
  default/python/AI/ResourcesAI.py
  default/scripting/buildings/ART_FACTORY_PLANET.focs.txt
  default/scripting/buildings/ART_PARADISE_PLANET.focs.txt
  default/scripting/buildings/ART_PLANET.focs.txt
  default/scripting/buildings/GAIA_TRANS.focs.txt
  default/scripting/buildings/HYPER_DAM.focs.txt
  default/scripting/buildings/TERRAFORM.focs.txt
  default/scripting/game_rules.focs.txt
  default/scripting/specials/planet/GAIA.focs.txt
  default/scripting/specials/planet/TEMPORAL_ANOMOLY.focs.txt
  default/scripting/specials/planet/TIDAL_LOCK.focs.txt
  default/scripting/specials/planet/growth/growth.macros
  default/scripting/species/SP_BANFORO.focs.txt
  default/scripting/species/common/population.macros
  default/scripting/species/common/xenophobic.macros
  default/scripting/techs/construction/N_DIMEN_STRUCT.focs.txt
  default/scripting/techs/growth/CYBORG.focs.txt
  default/scripting/techs/growth/ORBITAL_HAB.focs.txt
  default/scripting/techs/growth/SUBTER_HAB.focs.txt
  default/scripting/techs/growth/SYMBIOTIC_BIO.focs.txt
  default/scripting/techs/growth/XENO_GENETICS.focs.txt
  default/scripting/techs/growth/XENO_HYBRIDS.focs.txt
  default/stringtables/en.txt
  parse/DoubleValueRefParser.cpp
  parse/Tokens.h
  python/UniverseWrapper.cpp
  test/parse/TestValueRefDoubleParser.cpp
  universe/Planet.cpp
  universe/Planet.h
  universe/ValueRef.cpp
Labels: category:tweak, component:content scripting, component:game mechanic

#1963 Imperial Stockpile (4th revision)
  default/scripting/buildings/GAS_GIANT_GEN.focs.txt
  default/scripting/buildings/SPACE_ELEVATOR.focs.txt
  default/scripting/buildings/TERRAFORM.focs.txt
  default/scripting/encyclopedia/game_concepts/metabolism/GASEOUS_SPECIES.focs.txt
  default/scripting/encyclopedia/game_concepts/planetary_focus/STOCKPILE_FOCUS.focs.txt
  default/scripting/encyclopedia/species/GASEOUS_SPECIES_CLASS.focs.txt
  default/scripting/ship_hulls/robotic/SH_SPACE_FLUX_BUBBLE.focs.txt
  default/scripting/ship_hulls/ship_hulls.macros
  default/scripting/species/SP_SLY.focs.txt
  default/scripting/species/common/population.macros
  default/scripting/species/common/stockpile.macros
  default/scripting/species/common/supply.macros
  default/scripting/techs/production/PREDICTIVE_STOCKPILING.focs.txt
  default/stringtables/en.txt
Labels: category:tweak, component:game mechanic

#1989 Fix AI being kicked out from multiplayer lobby.
  server/ServerFSM.cpp
Labels: category:bug, component:network

#1979 [mock] Update mock for freeOrionAIInterface
  default/python/interface_mock/generate_mock.py
  default/python/interface_mock/interface_inspector.py
  default/python/interface_mock/parse_docs.py
  default/python/interface_mock/result/freeOrionAIInterface.py
Labels: category:refactoring, component:AI

#1969 Join playing game as Observer or Moderator
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
  server/ServerFSM.h
Labels: category:feature, component:UI, component:game mechanic, component:network, status:work in progress

#1996 Grow supply even if VERY_BAD_SUPPLY
  default/scripting/species/common/supply.macros
Labels: category:bug, component:content scripting

#1999 Show incoming warning after everything has settled
  default/customizations/custom_sitreps.txt
Labels: category:bug, component:content scripting

#1994 Dont show GASEOUS_DESC for all species
  default/scripting/species/SP_SLY.focs.txt
  default/scripting/species/common/population.macros
Labels: category:tweak, component:content scripting

#2000 Fix missing import - sorry for this
  default/customizations/custom_sitreps.txt
Labels: category:bug, component:content scripting, status:merged

#1991 Update pytest run
  default/python/tests/README.md
  default/python/tests/conftest.py
Labels: category:refactoring, component:AI

#1978 Fix wrong de-stringtable of cruiser/destroyer and laser/md
  default/stringtables/de.txt
Labels: category:bug, component:translation

#1982 Improve DesignWnd empty list prompts.
  UI/DesignWnd.cpp
  UI/QueueListBox.cpp
  UI/QueueListBox.h
  default/stringtables/en.txt
Labels: category:feature, category:tweak, component:UI

#1998 Rework AI orbital colonization
  default/python/AI/AIstate.py
  default/python/AI/ColonisationAI.py
  default/python/AI/savegame_codec/_definitions.py
Labels: category:refactoring, component:AI

#2002 Add mock module for tests
  default/python/tests/conftest.py
  default/python/tests/freeOrionAIInterface.py
Labels: category:refactoring, component:AI

#2003 Display current value for troop parts in ship articles
  UI/EncyclopediaDetailPanel.cpp
Labels: category:bug, component:UI

#2006 Add space between valuetest operators and rhs reference
  universe/Condition.cpp
Labels: category:bug, component:UI

#2008 Fix some stat and label strings
  default/stringtables/en.txt
Labels: category:bug, component:art music text assets

#1997 Add Game UID universe property.
  UI/EncyclopediaDetailPanel.cpp
  default/python/universe_generation/universe_generator.py
  default/stringtables/en.txt
  default/stringtables/ru.txt
  python/UniverseWrapper.cpp
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
  util/MultiplayerCommon.cpp
  util/MultiplayerCommon.h
  util/SerializeMultiplayerCommon.cpp
Labels: category:feature, component:internal

#2007 Dont describe average stockpile in species description
  default/scripting/species/common/stockpile.macros
Labels: category:bug, component:UI, component:content scripting

#2014 Show PP waste warning if stockpile input is unusually high
  UI/MapWnd.cpp
Labels: category:feature, component:UI

#1992 Remove stringtable includes
  Empire/Empire.cpp
  UI/CensusBrowseWnd.cpp
  UI/CensusBrowseWnd.h
  UI/MapWnd.cpp
  default/README.md
  default/content_specific_parameters.txt
  default/global_settings.txt
  default/scripting/species/SpeciesCensusOrdering.focs.txt
  default/stringtables/cz.txt
  default/stringtables/da.txt
  default/stringtables/de.txt
  default/stringtables/en.txt
  default/stringtables/es.txt
  default/stringtables/fi.txt
  default/stringtables/fr.txt
  default/stringtables/it.txt
  default/stringtables/nl.txt
  default/stringtables/pl.txt
  default/stringtables/ru.txt
  default/stringtables/sv.txt
  parse/Parse.h
  parse/SpeciesParser.cpp
  parse/Tokens.h
  universe/Species.cpp
  universe/Species.h
Labels: category:refactoring, component:UI, component:art music text assets, component:content scripting

#1990 Move mock location
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/handlers/README.md
  default/python/handlers/inspect_freeOrionAIInterface.py
  default/python/stub_generator/__init__.py
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/interface_inspector.py
  default/python/stub_generator/parse_docs.py
  default/python/stub_generator/stub_functions.py
  default/python/tox.ini
Labels: category:refactoring, component:AI

#2010 Fix DesignWnd does not display available SavedDesigns
  UI/DesignWnd.cpp
Labels: category:bug, component:UI

#1970 Update tests, setup travis
  .travis.yml
Labels: category:tweak, component:build system, component:infrastructure

#2019 Ai invasion adjustments
  default/python/AI/InvasionAI.py
Labels: category:tweak, component:AI, status:testing requested
