Repository freeorion/freeorion, pull requests merged in 2019-06, with the labels that each got.

#2336 Big pictures of species (Trenchers, Abaddoni, Scylior, Ugmors, Banforo, Phinnert).
  default/data/art/species/abaddoni.png
  default/data/art/species/banforo.png
  default/data/art/species/chato.png
  default/data/art/species/gysache.png
  default/data/art/species/happybirthdays.png
  default/data/art/species/phinnert.png
  default/data/art/species/preview/abaddoni.png
  default/data/art/species/preview/banforo.png
  default/data/art/species/preview/chato.png
  default/data/art/species/preview/gysache.png
  default/data/art/species/preview/happybirthdays.png
  default/data/art/species/preview/phinnert.png
  default/data/art/species/preview/scylior.png
  default/data/art/species/preview/trenchers.png
  default/data/art/species/preview/trith.png
  default/data/art/species/preview/ugmors.png
  default/data/art/species/scylior.png
  default/data/art/species/trenchers.png
  default/data/art/species/trith.png
  default/data/art/species/ugmors.png
  default/stringtables/en.txt
  default/stringtables/fr.txt
  default/stringtables/ru.txt
Labels: category:tweak, component:art music text assets

#2454 Encode server name to save it in the XML element
  client/human/HumanClientApp.cpp
  client/human/HumanClientApp.h
  client/human/HumanClientFSM.cpp
Labels: category:bug, component:network

#2435 Add testing and RelWithDebugInfo for cmake for windows
  BUILD.md
  CMakeLists.txt
  GG/test/unit/CMakeLists.txt
  appveyor.yml
  test/parse/CMakeLists.txt
  test/system/CMakeLists.txt
  test/system/ClientAppFixture.cpp
  test/util/CMakeLists.txt
Labels: category:feature, component:build system, component:infrastructure

#2458 Fix AI fuel tank ship design
  default/python/AI/AIDependencies.py
  default/python/AI/ShipDesignAI.py
Labels: category:tweak, component:AI

#2455 Show known servers in server list
  UI/ServerConnectWnd.cpp
  client/human/HumanClientApp.cpp
  client/human/HumanClientFSM.cpp
Labels: category:feature, component:UI, component:network

#2463 Output python exceptions to logger
  client/AI/AIClientApp.cpp
  python/AI/AIFramework.cpp
  python/AI/AIWrapper.cpp
  python/CommonFramework.cpp
  python/server/ServerFramework.cpp
  python/server/ServerWrapper.cpp
Labels: category:feature, component:internal

#2467 Fix python re-declaring snprinf for MSVC already supports it
  CMakeLists.txt
Labels: category:bug, component:internal, status:merged

#2462 Try to find suffixed boost_python
  CMakeLists.txt
Labels: category:bug, component:infrastructure

#2469 Try to find suffixed boost_python
  CMakeLists.txt
Labels: category:bug, component:infrastructure

#2460 Big Eaxaw art
  default/data/art/species/eaxaw.png
  default/data/art/species/preview/eaxaw.png
  default/stringtables/en.txt
  default/stringtables/fr.txt
  default/stringtables/ru.txt
Labels: category:feature, component:art music text assets

#2465 Load chat history in quickstart and load mode
  server/ServerFSM.cpp
Labels: category:feature, component:UI, component:network

#2470 Fix printing python exception without traceback
  python/CommonFramework.cpp
Labels: category:bug, component:internal

#2472 Output diagnostic information to monitor issues with GameStartMessage
  network/Message.cpp
Labels: category:tweak, component:internal

#2464 Don't send message after write error again
  network/ServerNetworking.cpp
  network/ServerNetworking.h
Labels: category:feature, component:network

#2473 Update Travis CI Linux to Ubuntu Xenial
  .travis.yml
Labels: category:bug, component:infrastructure

#2474 Add more diagnostic output
  network/Message.cpp
Labels: category:tweak, component:internal

#2437 Add check if building is enqueueable before issuing an enqueue order
  AI/AIInterface.cpp
Labels: category:bug, component:AI

#2471 Fix cmake compatibility
  CMakeLists.txt
Labels: category:bug, component:infrastructure

#2477 Add thread id to logs
  python/LoggingWrapper.cpp
  util/Logger.cpp
  util/Logger.h
Labels: category:feature, component:internal

#2478 Add more logs about restoring UI data and ship designs
  UI/DesignWnd.cpp
  client/human/HumanClientFSM.cpp
  parse/ShipDesignsParser.cpp
Labels: category:tweak, component:internal

#2480 Avoid serializing boost::optional in SaveGameUIData
  util/MultiplayerCommon.h
  util/SerializeMultiplayerCommon.cpp
Labels: category:bug, component:network

#2461 Use a fresh combat target condition for fighters
  combat/CombatSystem.cpp
Labels: category:bug, component:content scripting, component:internal

#2483 Add more trace logs to found out issue with UI data
  util/SerializeMultiplayerCommon.cpp
Labels: category:tweak, component:internal, component:network

#2486 Avoid serializing of std::unordered_map in SaveGameUIData
  util/MultiplayerCommon.h
  util/SerializeMultiplayerCommon.cpp
Labels: category:bug, component:network

#2481 Add option to set game UID
  default/stringtables/en.txt
  server/ServerApp.cpp
  server/ServerFSM.cpp
  server/dmain.cpp
  util/MultiplayerCommon.h
Labels: category:feature, component:internal

#2487 fix planet status indicator tooltip
  UI/SidePanel.cpp
Labels: category:bug, component:UI, status:merged

#2490 Replace bits8 and bits16 removed in Boost 1.70
  GG/src/gilext/io/png_io_private.hpp
Labels: category:bug, component:internal, status:testing requested

#2491 Replace bits8 and bits16 removed in Boost 1.70
  GG/src/gilext/io/png_io_private.hpp
Labels: category:bug, component:internal, status:cherry-pick for release

#2493 add CUIWnd::Flash
  UI/CUIWnd.cpp
  UI/CUIWnd.h
Labels: category:feature, component:UI
