Repository freeorion/freeorion, pull requests merged in 2019-01, with the labels that each got.

#2347 Show player list based on empires
  UI/PlayerListWnd.cpp
  UI/PlayerListWnd.h
Labels: category:feature, component:UI

#2350 Fix some issues with empire color from save game
  GG/GG/Clr.h
  GG/GG/ClrConstants.h
  GG/src/CMakeLists.txt
  GG/src/ClrConstants.cpp
  msvc2015/GiGi/GiGi.vcxproj
  msvc2015/GiGi/GiGi.vcxproj.filters
  msvc2017/GiGi/GiGi.vcxproj
  msvc2017/GiGi/GiGi.vcxproj.filters
  server/ServerFSM.cpp
  test/system/CMakeLists.txt
Labels: category:bug, component:internal

#2329 Add option to enable/disable network binary serialization
  default/stringtables/en.txt
  network/ServerNetworking.cpp
  network/ServerNetworking.h
  server/ServerApp.cpp
  server/ServerFSM.cpp
  server/dmain.cpp
Labels: category:feature, component:internal

#2351 Some test fixes
  .travis.yml
  test/system/ClientAppFixture.cpp
  test/system/SmokeTestGame.cpp
  test/system/SmokeTestHostless.cpp
Labels: category:bug, component:build system, component:infrastructure, component:internal

#2359 Tweaks
  UI/EncyclopediaDetailPanel.cpp
  UI/FleetWnd.cpp
  combat/CombatEvents.h
  server/ServerApp.cpp
  universe/Ship.cpp
  universe/ShipDesign.cpp
  universe/Universe.cpp
  util/SerializeOrderSet.cpp
Labels: category:tweak, component:internal

#2341 Target research pedia links and definition
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets

#2361 Target Industry pedia links and definition
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets

#2362 Target meters pedia links and definitions
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets

#2363 Ship part meter value ref
  parse/ConditionParser4.cpp
  parse/DoubleComplexValueRefParser.cpp
  parse/EnumParser.cpp
  parse/Tokens.h
  parse/ValueRefParser.h
  universe/ValueRef.cpp
Labels: category:feature, component:content scripting, component:internal

#2345 Do not send private information about empires
  default/scripting/game_rules.focs.txt
  default/stringtables/en.txt
  util/SerializeEmpire.cpp
Labels: category:feature, component:game mechanic, component:network

#2330 Condition Combat Targetting
  UI/CombatReport/CombatLogWnd.cpp
  combat/CombatEvent.h
  combat/CombatEvents.cpp
  combat/CombatEvents.h
  combat/CombatSystem.cpp
  combat/CombatSystem.h
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_0.focs.txt
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_1.focs.txt
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_2.focs.txt
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_3.focs.txt
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_4.focs.txt
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_KRILL.focs.txt
  default/scripting/ship_parts/ShortRange/SR_WEAPON_0_1.focs.txt
  default/scripting/ship_parts/targeting.macros
  default/stringtables/en.txt
  parse/ConditionParser3.cpp
  parse/ConditionParser4.cpp
  parse/EffectParser1.cpp
  parse/EffectParser2.cpp
  parse/ShipPartsParser.cpp
  parse/StringValueRefParser.cpp
  parse/Tokens.h
  python/AI/AIWrapper.cpp
  server/ServerApp.cpp
  universe/Condition.cpp
  universe/Condition.h
  universe/Fighter.cpp
  universe/Fighter.h
  universe/ObjectMap.h
  universe/Ship.cpp
  universe/ShipDesign.cpp
  universe/ShipDesign.h
  universe/UniverseObject.h
  universe/ValueRef.h
Labels: category:feature, component:game mechanic, status:work in progress
