Repository freeorion/freeorion, pull requests merged in 2019-12, with the labels that each got.

#2664 lower the min unfocused FPS to 0.1
  UI/ClientUI.cpp
Labels: category:tweak, component:UI

#2660 Fix segfault when trying to delete in empty password
  UI/CUIControls.cpp
Labels: category:bug, component:UI, priority:high, status:cherry-pick for release

#2659 Fix Empty Censored Password Edit Delete Crash
  UI/CUIControls.cpp
  UI/CUIControls.h
Labels: category:bug, component:UI, priority:high, status:cherry-pick for release, status:merged

#2670 added openSUSE install instructions
  README.md
Labels: category:tweak, component:technical docs, status:cherry-pick for release, status:merged

#2671 Revert "added openSUSE install instructions"
  README.md
Labels: category:bug, component:technical docs, status:merged

#2673 Suse readme
  README.md
Labels: category:tweak, component:technical docs, status:cherry-pick for release, status:merged

#2668 Flak Description
  default/stringtables/en.txt
Labels: category:bug, component:art music text assets, status:cherry-pick for release

#2667 changelog update v0.4.9
  ChangeLog.md
Labels: category:tweak, component:deployment, component:user manual

#2674 Add game rule to enable allied fleet repair
  ChangeLog.md
  default/scripting/buildings/shipyards/ORBITAL_DRYDOCK.focs.txt
  default/scripting/game_rules.focs.txt
  default/scripting/techs/ship_parts/damage_control/SHP_FLEET_REPAIR.focs.txt
  default/stringtables/en.txt
Labels: category:feature, component:content scripting, component:network, priority:high, status:cherry-pick for release, status:merged

#2683 Fix potential division by zero
  default/python/AI/AIFleetMission.py
Labels: category:bug, component:AI

#2682 Fix potential division by zero
  default/python/AI/AIFleetMission.py
Labels: category:bug, component:AI
