Repository freeorion/freeorion, pull requests merged in 2019-10, with the labels that each got.

#2580 Fix bug introduced by #2577
  default/scripting/ship_hulls/ship_hulls.macros
Labels: category:bug, category:tweak, component:content scripting

#2584 Don't clean empire readiness on player list changes
  UI/PlayerListWnd.cpp
  UI/PlayerListWnd.h
  client/human/HumanClientFSM.cpp
Labels: category:bug, component:UI, component:network

#2585 fix psychogenic domination pedia description
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets, status:merged

#2504 Add /pm command to message_wnd
  AI/AIInterface.cpp
  UI/ChatWnd.cpp
  UI/ChatWnd.h
  UI/MultiplayerLobbyWnd.cpp
  client/AI/AIClientApp.cpp
  client/human/HumanClientFSM.cpp
  default/stringtables/en.txt
  network/Message.cpp
  network/Message.h
  server/ServerFSM.cpp
Labels: category:feature, component:UI, component:network, status:testing requested

#2570 Inform other empires about detection increase
  default/customizations/custom_sitreps.txt
  default/stringtables/en.txt
Labels: category:feature, component:content scripting

#2586 Made CMAKE_PREFIX_PATH configurable
  CMakeLists.txt
Labels: category:tweak, component:build system

#2587 Shift supply check and Inform about weapon upgrade
  default/scripting/techs/ship_weapons/ship_weapons.macros
  default/scripting/techs/techs.macros
  default/stringtables/en.txt
Labels: category:bug, component:content scripting

#2589 Don't use Enter as OK in Galaxy Setup
  UI/GalaxySetupWnd.cpp
Labels: category:bug, category:tweak, component:UI

#2590 Fix handling for gifting objects.
  UI/FleetWnd.cpp
  util/Order.cpp
Labels: category:bug, component:internal

#2595 Add Alliance to Peace in AFFIL_ALLY conditions
  universe/Condition.cpp
  universe/Effect.cpp
Labels: category:bug, component:internal

#2597 Add more Diplomacy articles to Pedia
  default/scripting/encyclopedia/game_concepts/AI_LEVELS.focs.txt
  default/scripting/encyclopedia/game_concepts/diplomacy/ALLIANCE.focs.txt
  default/scripting/encyclopedia/game_concepts/diplomacy/GIFTING.focs.txt
  default/scripting/encyclopedia/game_concepts/diplomacy/WAR.focs.txt
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets, component:user manual

#2594 Issue #2551 changes
  client/human/HumanClientApp.cpp
  client/human/HumanClientApp.h
  default/stringtables/en.txt
Labels: category:feature, component:UI, component:game mechanic

#2530 Fix AI fighter calculations
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/fleet_orders.py
Labels: category:bug, component:AI, status:work in progress

#2601 Improve SitRepPanel::SizeMove() performance
  UI/SitRepPanel.cpp
Labels: category:tweak, component:UI, priority:high

#2602 Do not confirm quit for observers and moderators.
  client/human/HumanClientApp.cpp
Labels: category:tweak, component:UI, component:network

#2618 Don't automatically choose empire based on player name in the in-game lobby
  UI/MultiplayerLobbyWnd.cpp
  server/ServerFSM.cpp
  util/MultiplayerCommon.h
  util/SerializeMultiplayerCommon.cpp
Labels: category:bug, component:UI, component:network, priority:high

#2621 Alleryn fuel pedia fix
  default/python/AI/ShipDesignAI.py
  default/scripting/ship_hulls/SH_BASIC_MEDIUM.focs.txt
  default/scripting/ship_hulls/SH_BASIC_SMALL.focs.txt
  default/scripting/ship_hulls/asteroid/SH_HEAVY_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_MINIASTEROID_SWARM.focs.txt
  default/scripting/ship_hulls/asteroid/SH_SCATTERED_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_SMALL_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_SMALL_CAMOUFLAGE_ASTEROID.focs.txt
  default/scripting/ship_hulls/energy/SH_COMPRESSED_ENERGY.focs.txt
  default/scripting/ship_hulls/energy/SH_ENERGY_FRIGATE.focs.txt
  default/scripting/ship_hulls/energy/SH_SOLAR.focs.txt
  default/scripting/ship_hulls/organic/SH_ENDOMORPHIC.focs.txt
  default/scripting/ship_hulls/organic/SH_ENDOSYMBIOTIC.focs.txt
  default/scripting/ship_hulls/organic/SH_ORGANIC.focs.txt
  default/scripting/ship_hulls/organic/SH_PROTOPLASMIC.focs.txt
  default/scripting/ship_hulls/organic/SH_STATIC_MULTICELLULAR.focs.txt
  default/scripting/ship_hulls/organic/SH_SYMBIOTIC.focs.txt
  default/scripting/ship_hulls/robotic/SH_LOGITICS_FACILITATOR.focs.txt
  default/scripting/ship_hulls/robotic/SH_SELF_GRAVITATING.focs.txt
  default/scripting/ship_hulls/robotic/SH_SPACE_FLUX_BUBBLE.focs.txt
  default/scripting/ship_hulls/robotic/SH_SPATIAL_FLUX.focs.txt
  default/scripting/ship_hulls/robotic/SH_TITANIC.focs.txt
  default/scripting/ship_hulls/robotic/SH_TRANSSPATIAL.focs.txt
  default/scripting/ship_hulls/ship_hulls.macros
  default/stringtables/en.txt
Labels: category:tweak, component:AI, component:content scripting

#2619 Fix log filters not applying while setting a new log level
  util/Logger.cpp
Labels: category:bug, component:internal

#2609 Async write returns nothing so remove bool result
  network/ServerNetworking.cpp
  network/ServerNetworking.h
  server/ServerFSM.cpp
Labels: category:refactoring, component:internal, component:network
