Repository freeorion/freeorion, pull requests merged in 2019-02, with the labels that each got.

#2346 UI improvements
  UI/DesignWnd.cpp
  UI/MapWnd.cpp
  default/stringtables/en.txt
Labels: category:feature, component:UI

#2364 Repeal save game data request
  AI/AIInterface.cpp
  AI/AIInterface.h
  UI/FleetWnd.cpp
  UI/InGameMenu.cpp
  UI/MapWnd.cpp
  UI/MapWnd.h
  UI/SidePanel.cpp
  client/AI/AIClientApp.cpp
  client/ClientApp.cpp
  client/ClientApp.h
  client/ClientFSMEvents.h
  client/human/HumanClientApp.cpp
  client/human/HumanClientApp.h
  client/human/HumanClientFSM.cpp
  client/human/HumanClientFSM.h
  network/Message.cpp
  network/Message.h
  network/ServerNetworking.cpp
  python/AI/AIFramework.cpp
  python/AI/AIFramework.h
  server/SaveLoad.cpp
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
  server/ServerFSM.h
  test/system/ClientAppFixture.cpp
  test/system/ClientAppFixture.h
  test/system/SmokeTestGame.cpp
  test/system/SmokeTestHostless.cpp
  util/OrderSet.cpp
  util/OrderSet.h
Labels: category:tweak, component:network, status:work in progress

#2375 Bandaid-fix for random AI CI errors
  default/python/common/handlers.py
Labels: category:bug, component:infrastructure, status:workaround

#2376 Also target planets without defense but with shields
  combat/CombatSystem.cpp
  default/scripting/ship_parts/targeting.macros
Labels: category:tweak, component:content scripting, component:game mechanic

#2381 Fix cookie expire option usage
  network/ServerNetworking.cpp
Labels: category:bug, component:internal, status:merged

#2380 Treat timeout read error as disconnection
  network/ServerNetworking.cpp
Labels: category:tweak, component:network

#2383 Set icon in construction - ref 4dbd875
  universe/ShipDesign.cpp
Labels: category:bug, component:UI

#2377 Some fixes for MSVC projects generated by cmake
  CMakeLists.txt
  GG/CMakeLists.txt
  GG/test/acceptance/CMakeLists.txt
  GG/test/unit/CMakeLists.txt
  test/parse/CMakeLists.txt
  test/system/CMakeLists.txt
  test/util/CMakeLists.txt
Labels: category:bug, component:build system

#2360 Transfer player connection to async handlers by shared pointer instead of raw pointer
  network/ServerNetworking.cpp
  network/ServerNetworking.h
Labels: category:tweak, component:internal, component:network, status:testing requested, status:work in progress

#2386 Fix Boost auto-linking
  CMakeLists.txt
  GG/CMakeLists.txt
  GG/test/unit/CMakeLists.txt
  test/parse/CMakeLists.txt
  test/system/CMakeLists.txt
  test/util/CMakeLists.txt
Labels: category:bug, component:build system

#2382 Protect empires of authenticated players
  Empire/Empire.cpp
  Empire/Empire.h
  Empire/EmpireManager.cpp
  Empire/EmpireManager.h
  server/SaveLoad.cpp
  server/ServerApp.cpp
  server/ServerFSM.cpp
  universe/UniverseGenerator.cpp
  util/MultiplayerCommon.h
  util/SerializeEmpire.cpp
  util/SerializeMultiplayerCommon.cpp
Labels: category:feature, component:network

#2379 Allow human players to disconnect without stopping game
  UI/InGameMenu.cpp
  default/stringtables/en.txt
  server/ServerApp.cpp
  server/ServerFSM.cpp
  server/dmain.cpp
Labels: category:feature, component:network

#2392 Fix found by static analysis code misc issues
  GG/GG/Font.h
  GG/src/Font.cpp
  GG/src/SDL/SDLGUI.cpp
  GG/src/dialogs/FileDlg.cpp
  GG/src/dialogs/ThreeButtonDlg.cpp
  network/ClientNetworking.cpp
  python/AI/AIWrapper.cpp
Labels: category:tweak, component:internal, status:merged

#2389 Potential Common library performance improvements
  Empire/ResearchQueue.cpp
  Empire/Supply.cpp
  GG/GG/Clr.h
  universe/Condition.cpp
  universe/Effect.cpp
  universe/ResourceCenter.cpp
  universe/Ship.cpp
  universe/ShipDesign.cpp
  universe/Universe.cpp
  universe/ValueRef.cpp
  util/Directories.cpp
  util/MultiplayerCommon.cpp
  util/OptionsDB.cpp
  util/SaveGamePreviewUtils.cpp
  util/SerializeEmpire.cpp
  util/SerializeUniverse.cpp
  util/i18n.cpp
Labels: category:refactoring, component:internal

#2391 Fix found by static analysis code issues in daemon
  GG/src/SDL/SDLGUI.cpp
  GG/src/Texture.cpp
  UI/Sound.cpp
  client/AI/AIClientApp.cpp
  client/human/HumanClientApp.cpp
  client/human/chmain.cpp
  combat/CombatSystem.cpp
  python/CommonFramework.cpp
  python/UniverseWrapper.cpp
  python/server/ServerWrapper.cpp
  server/ServerApp.cpp
  server/ServerFSM.cpp
Labels: category:tweak, component:internal
