Repository freeorion/freeorion, pull requests merged in 2019-03, with the labels that each got.

#2390 Fix found by static analysis code issues in Common library
  Empire/Empire.cpp
  Empire/ResearchQueue.cpp
  combat/CombatEvents.cpp
  universe/Fighter.cpp
  universe/Fleet.cpp
  universe/Tech.cpp
  universe/Universe.cpp
  universe/UniverseObject.cpp
  universe/ValueRef.cpp
  util/OptionsDB.cpp
Labels: category:tweak, component:internal

#2368 Population meters pedia links and definition
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets

#2396 Let Interspecies academy research boost change target research
  default/scripting/buildings/INTERSPECIES_ACADEMY.focs.txt
Labels: category:bug, component:content scripting

#2395 SVG Rendering in Pedia
  GG/CMakeLists.txt
  GG/GG/DrawUtil.h
  GG/GG/StaticGraphic.h
  GG/GG/Texture.h
  GG/GG/VectorTexture.h
  GG/GG/Wnd.h
  GG/src/CMakeLists.txt
  GG/src/DrawUtil.cpp
  GG/src/RichText/ImageBlock.cpp
  GG/src/StaticGraphic.cpp
  GG/src/Texture.cpp
  GG/src/VectorTexture.cpp
  GG/src/nanosvg/LICENSE.txt
  GG/src/nanosvg/README.md
  GG/src/nanosvg/nanosvg.h
  GG/src/nanosvg/nanosvgrast.h
  GG/src/nanovg/CMakeLists.txt
  GG/src/nanovg/LICENSE.txt
  GG/src/nanovg/README.md
  GG/src/nanovg/fontstash.h
  GG/src/nanovg/nanovg.c
  GG/src/nanovg/nanovg.h
  GG/src/nanovg/nanovg_gl.h
  GG/src/nanovg/nanovg_gl_utils.h
  GG/src/nanovg/stb_image.h
  GG/src/nanovg/stb_truetype.h
  GG/src/svg.cpp
  UI/EncyclopediaDetailPanel.cpp
  default/stringtables/en.txt
  msvc2017/GiGi/GiGi.vcxproj
  msvc2017/GiGi/GiGi.vcxproj.filters
Labels: category:feature, component:UI, component:art music text assets

#2398 Don't save eliminated empres to empire data
  server/SaveLoad.cpp
Labels: category:feature, component:UI, component:game mechanic

#2403 Notify players that eliminated empire finished its orders
  server/ServerApp.cpp
Labels: category:tweak, component:internal, component:network

#2399 Don't allow to enter to playing game as a eliminated empire
  server/ServerApp.cpp
Labels: category:tweak, component:internal, component:network

#2400 Allow to load game without all human player connected
  default/stringtables/en.txt
  server/ServerFSM.cpp
  server/dmain.cpp
Labels: category:feature, component:internal, component:network

#2402 Automatically save game before exit
  server/ServerFSM.cpp
Labels: category:feature, component:internal

#2405 Remove unactual single substatus of WaitingForTurnEnd.
  server/ServerFSM.cpp
  server/ServerFSM.h
Labels: category:refactoring, component:internal

#2404 Save and load readiness status
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
  util/MultiplayerCommon.h
  util/SerializeMultiplayerCommon.cpp
Labels: category:feature, component:game mechanic, component:network

#2407 Timed auto save
  default/stringtables/en.txt
  server/ServerFSM.cpp
  server/ServerFSM.h
  util/MultiplayerCommon.cpp
Labels: category:feature, component:game mechanic

#2331 Add snapcraft.yaml to enable snap build.
  snap/snapcraft.yaml
Labels: category:feature, component:deployment

#2384 Topmost matches condition
  default/scripting/buildings/ART_PARADISE_PLANET.focs.txt
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_1.focs.txt
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_3.focs.txt
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_4.focs.txt
  default/stringtables/en.txt
  parse/ConditionParser1.cpp
  parse/ConditionParser1.h
  parse/Tokens.h
  universe/Condition.cpp
  universe/Condition.h
Labels: category:feature, component:content scripting, component:internal

#2408 Add option to start hostless server from saved game
  client/human/chmain.cpp
  default/stringtables/en.txt
  server/ServerApp.cpp
  server/ServerFSM.cpp
  util/MultiplayerCommon.cpp
Labels: category:feature, component:UI, component:internal, component:network

#2410 Replace deprecated boost::asio stuff.
  GG/src/Texture.cpp
  network/ClientNetworking.cpp
  network/ServerNetworking.cpp
  network/ServerNetworking.h
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
Labels: category:bug, component:internal, component:network

#2413 Match nothing in OrderedAlternativesOf if no operand condition applied
  universe/Condition.cpp
Labels: category:bug, component:content scripting, component:game mechanic

#1624 add planet status marker
  UI/SidePanel.cpp
  default/data/art/icons/planet_status_attacked.png
  default/data/art/icons/planet_status_conquered.png
  default/data/art/icons/planet_status_supply.png
  default/data/art/icons/planet_status_unhappy.png
  default/data/art/icons/planet_status_warning.png
  default/stringtables/en.txt
Labels: category:tweak, component:UI
