Repository freeorion/freeorion, pull requests merged in 2019-04, with the labels that each got.

#2415 Remove ALLOW_NO_STARLANES
  UI/GalaxySetupWnd.cpp
Labels: category:tweak, component:internal

#2374 Introduce new AI Mission Type: PROTECT_REGION
  default/python/AI/AIFleetMission.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/EnumsAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/turn_state.py
Labels: category:feature, component:AI

#2420 Fix test in case if empire id isn't equal player id
  test/system/ClientAppFixture.cpp
Labels: category:bug, component:infrastructure

#2419 Add more games and turns to test
  test/system/SmokeTestGame.cpp
  test/system/SmokeTestHostless.cpp
Labels: category:tweak, component:infrastructure, status:merged

#2414 Save game when playing game went to shutdown
  client/human/HumanClientApp.cpp
  default/stringtables/en.txt
  server/ServerFSM.cpp
  util/MultiplayerCommon.cpp
Labels: category:feature, component:internal, component:network

#2426 Use map of game rules instead vector of pairs
  UI/GalaxySetupWnd.cpp
  UI/GalaxySetupWnd.h
  util/GameRules.cpp
  util/GameRules.h
  util/MultiplayerCommon.cpp
  util/MultiplayerCommon.h
Labels: category:tweak, component:internal

#2421 Remove unused player ID from PLAYER_STATUS message.
  client/human/HumanClientFSM.cpp
  network/Message.cpp
  network/Message.h
  server/ServerApp.cpp
  server/ServerFSM.cpp
  test/system/ClientAppFixture.cpp
Labels: category:feature, component:network

#2424 Options game rules
  server/ServerFSM.cpp
  util/GameRules.h
Labels: category:feature, component:internal

#2428 Fedora changed rpm pkgdb
  README.md
Labels: category:tweak, component:deployment

#2423 Common galaxy options
  UI/GalaxySetupWnd.cpp
  server/ServerApp.cpp
  server/ServerFSM.cpp
  test/system/SmokeTestHostless.cpp
  util/MultiplayerCommon.cpp
Labels: category:refactoring, component:internal

#2429 Fix game rules wrapper for ai
  default/python/AI/FreeOrionAI.py
  default/python/AI/freeOrionAIInterface.pyi
  default/python/AI/freeorion_tools/extend_freeorion_AI_interface.py
  python/UniverseWrapper.cpp
Labels: category:bug, component:AI

#2422 Refactor game initialization so it allowed to have disconnected player
  server/ServerApp.cpp
  server/ServerFSM.cpp
  server/ServerFSM.h
  universe/UniverseGenerator.cpp
  universe/UniverseGenerator.h
Labels: category:feature, component:internal, component:network

#2432 Show error message in tests
  test/system/ClientAppFixture.cpp
Labels: category:feature, component:internal, status:merged

#2393 Enter/leave chat messages
  default/stringtables/en.txt
  default/stringtables/ru.txt
  server/ServerFSM.cpp
Labels: category:feature, component:UI, component:network

#2433 Try to fix Bad file descriptor error in CI
  network/ClientNetworking.cpp
Labels: category:bug, component:infrastructure

#2434 Add testing flag to AI to use it in tests
  client/AI/camain.cpp
  server/ServerApp.cpp
  server/dmain.cpp
Labels: category:feature, component:infrastructure
