Repository freeorion/freeorion, pull requests merged in 2019-05, with the labels that each got.

#2417 Hostless quickstart
  client/human/chmain.cpp
  default/stringtables/en.txt
  server/ServerFSM.cpp
  util/MultiplayerCommon.cpp
Labels: category:feature, component:internal

#2285 Remove AIInterface::DoneTurn() calls from Python AI
  default/python/AI/FreeOrionAI.py
  python/AI/AIFramework.cpp
  python/AI/AIWrapper.cpp
Labels: category:refactoring, component:AI

#2436 Fix potential out of bounds access in Production/ResearchQueue
  Empire/ProductionQueue.cpp
  Empire/ResearchQueue.cpp
Labels: category:bug, component:internal

#2440 Catch system error in tests
  test/system/CMakeLists.txt
Labels: category:tweak, component:build system

#2441 Initial turn timeout implementation
  UI/MapWnd.cpp
  UI/MapWnd.h
  client/AI/AIClientApp.cpp
  client/ClientFSMEvents.h
  client/human/HumanClientApp.cpp
  client/human/HumanClientFSM.cpp
  client/human/HumanClientFSM.h
  default/stringtables/en.txt
  network/Message.cpp
  network/Message.h
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
  server/ServerFSM.h
  server/dmain.cpp
  test/system/ClientAppFixture.cpp
Labels: category:feature, component:internal

#2445 Require MacOS 10.7 or higher as target deployment of Cocoa interface
  Xcode/main.xib
Labels: category:bug, component:internal

#2446 Set rules to quickstart game
  server/ServerFSM.cpp
Labels: category:feature, component:internal, component:network

#2448 Fix turn expiration status
  server/ServerApp.cpp
Labels: category:bug, component:internal, component:network

#2430 German translation (ships, monsters, buildings, specials)
  default/stringtables/de.txt
Labels: category:feature, component:translation

#2453 Handle TurnTimeout in PlayingGame state
  client/human/HumanClientFSM.cpp
  client/human/HumanClientFSM.h
Labels: category:tweak, component:internal, component:network

#2452 Clean orders only on turn update
  client/AI/AIClientApp.cpp
  client/ClientApp.cpp
  client/human/HumanClientFSM.cpp
  server/ServerFSM.cpp
Labels: category:bug, component:game mechanic, component:internal

#2447 Fix count of disconnected human players
  server/ServerApp.cpp
Labels: category:bug, component:internal, component:network
