Repository freeorion/freeorion, pull requests merged in 2019-11, with the labels that each got.

#2627 Describe fuel efficiency/list of tags in hull description
  UI/EncyclopediaDetailPanel.cpp
  default/content_specific_parameters.txt
  default/stringtables/en.txt
Labels: category:bug, component:UI, component:content scripting, component:internal

#2623 Add tooltip to turn button
  UI/MapWnd.cpp
  UI/MapWnd.h
  default/stringtables/en.txt
Labels: category:feature, component:UI

#2600 Apply newly added techs before final meter estimation
  server/ServerApp.cpp
Labels: category:bug, component:internal, priority:high, status:testing requested

#2616 Use outgoing message queue and asynchronously send messages from the server
  network/ServerNetworking.cpp
  network/ServerNetworking.h
Labels: category:bug, component:internal, component:network

#2611 Make synchronous sending in io context queue
  network/ServerNetworking.cpp
  network/ServerNetworking.h
Labels: category:refactoring, component:internal, component:network

#2635 Allow CMake to failure on Appveyor
  appveyor.yml
Labels: category:tweak, component:infrastructure

#2625 Fix exception warning
  UI/OptionsWnd.cpp
  combat/CombatLogManager.cpp
Labels: category:bug, component:internal

#2631 Adjust MIN_PERP_DIST & MAX_LANE_DOT_PRODUCT to avoid Starlane Nexus c…
  universe/Condition.cpp
Labels: category:tweak, component:content scripting, component:internal

#2617 Add support to delegate empire access
  default/python/auth/auth.py
  python/server/ServerFramework.cpp
  python/server/ServerFramework.h
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
Labels: category:feature, component:UI, component:network

#2592 Queue items at top from object list
  UI/ObjectListWnd.cpp
  default/stringtables/en.txt
Labels: category:feature, component:UI

#2606 Copy lobby chat to game chat
  UI/ChatWnd.cpp
  UI/ChatWnd.h
  UI/MultiplayerLobbyWnd.cpp
  UI/MultiplayerLobbyWnd.h
  client/human/HumanClientFSM.cpp
Labels: category:feature, component:UI, component:network, status:testing requested

#2638 Use empire ID instead of incorrect player ID for diplomacy
  UI/PlayerListWnd.cpp
Labels: category:bug, component:UI, component:network

#2639 Show and flash message window if other player send message
  UI/ChatWnd.cpp
Labels: category:bug, component:UI, component:network

#2644 Fix compilation for boost 1.72
  GG/CMakeLists.txt
  GG/src/Texture.cpp
Labels: category:bug, component:build system, component:internal, priority:high

#2640 Fallback to IPv4 if cannot open UPD or TCP socket
  network/ServerNetworking.cpp
Labels: category:bug, component:network, status:testing requested

#2651 201911 fix basic hull descriptions
  default/stringtables/de.txt
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets

#2647 OpenURL: handle error in system()
  client/human/HumanClientApp.cpp
Labels: category:tweak, component:internal

#2628 Balance - double base hull cost, but triple internal slots
  default/scripting/ship_designs/SD_BASE_DECOY.focs.txt
  default/scripting/ship_designs/required/SD_COLONY_BASE.focs.txt
  default/scripting/ship_designs/required/SD_CRYONIC_COLONY_BASE.focs.txt
  default/scripting/ship_designs/required/SD_OUTPOST_BASE.focs.txt
  default/scripting/ship_designs/required/SD_TROOP_DROP.focs.txt
  default/scripting/ship_designs/required/SD_TROOP_DROP_HEAVY.focs.txt
  default/scripting/ship_hulls/SH_COLONY_BASE.focs.txt
Labels: category:tweak, component:content scripting

#2655 Don't fail on player info
  test/system/ClientAppFixture.cpp
Labels: category:tweak, component:infrastructure
