Repository freeorion/freeorion, pull requests merged in 2019-07, with the labels that each got.

#2494 add missing frames to planet environment images
  default/data/art/encyclopedia/planet_environments/pt_barren02.png
  default/data/art/encyclopedia/planet_environments/pt_desert02.png
  default/data/art/encyclopedia/planet_environments/pt_gasgiant02.png
  default/data/art/encyclopedia/planet_environments/pt_inferno02.png
  default/data/art/encyclopedia/planet_environments/pt_swamp02.png
  default/data/art/encyclopedia/planet_environments/pt_toxic02.png
Labels: category:bug, component:art music text assets

#2466 add diplomatic status indicator
  UI/PlayerListWnd.cpp
  default/stringtables/en.txt
Labels: component:UI, status:help wanted, status:work in progress

#2496 remove gap from diplomatic status indicator after one or more empires were eliminated
  Empire/EmpireManager.cpp
  Empire/EmpireManager.h
  UI/PlayerListWnd.cpp
Labels: category:bug, component:UI

#2499 fix planet status indicator (supply)
  UI/SidePanel.cpp
Labels: category:bug, component:UI

#2501 Count disconnected (human) players on condede
  server/ServerApp.cpp
Labels: category:bug, component:internal, component:network, status:merged

#2498 Target infrastructure by ShortRange weapons and ensure combat
  combat/CombatSystem.cpp
  default/scripting/species/common/general.macros
Labels: category:bug, category:tweak, component:game mechanic, status:testing requested

#2502 new line for each empire in psi tooltip
  UI/PlayerListWnd.cpp
Labels: category:tweak, component:UI

#2506 Hhhoh art.
  default/data/art/species/hhhoh.png
  default/data/art/species/preview/hhhoh.png
  default/stringtables/en.txt
  default/stringtables/fr.txt
  default/stringtables/ru.txt
Labels: category:feature, component:art music text assets

#2457 extend UI to notify player about diplomatic changes
  UI/ChatWnd.cpp
  UI/ChatWnd.h
  UI/PlayerListWnd.cpp
  UI/PlayerListWnd.h
  default/stringtables/en.txt
Labels: category:feature, component:UI

#2509 Show saved galaxy setup data in multiplayer lobby
  server/SaveLoad.cpp
  server/SaveLoad.h
  server/ServerFSM.cpp
Labels: category:feature, component:UI, component:network

#2511 Don't save private messages
  server/ServerFSM.cpp
Labels: category:bug, component:network

#2514 Show unassigned empires in multiplayer lobby
  UI/MultiplayerLobbyWnd.cpp
  server/ServerFSM.cpp
Labels: category:feature, component:UI, component:network

#2513 Show saved current turn
  server/SaveLoad.cpp
  server/SaveLoad.h
  server/ServerFSM.cpp
  util/MultiplayerCommon.h
  util/SerializeMultiplayerCommon.cpp
Labels: category:feature, component:internal, component:network

#2507 ChatWnd and PlayerListWnd stop flashing when dragged
  UI/ChatWnd.cpp
  UI/ChatWnd.h
  UI/PlayerListWnd.cpp
  UI/PlayerListWnd.h
Labels: category:tweak, component:UI

#2492 Hull size dependent fuel
  default/python/AI/AIDependencies.py
  default/python/AI/ShipDesignAI.py
  default/scripting/encyclopedia/game_concepts/FUEL.focs.txt
  default/scripting/ship_hulls/SH_BASIC_LARGE.focs.txt
  default/scripting/ship_hulls/SH_BASIC_MEDIUM.focs.txt
  default/scripting/ship_hulls/SH_BASIC_SMALL.focs.txt
  default/scripting/ship_hulls/asteroid/SH_AGREGATE_ASTEROID.disabled
  default/scripting/ship_hulls/asteroid/SH_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_CAMOUFLAGE_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_CRYSTALLIZED_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_HEAVY_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_MINIASTEROID_SWARM.focs.txt
  default/scripting/ship_hulls/asteroid/SH_SCATTERED_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_SMALL_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_SMALL_CAMOUFLAGE_ASTEROID.focs.txt
  default/scripting/ship_hulls/energy/SH_COMPRESSED_ENERGY.focs.txt
  default/scripting/ship_hulls/energy/SH_ENERGY_FRIGATE.focs.txt
  default/scripting/ship_hulls/energy/SH_FRACTAL_ENERGY.focs.txt
  default/scripting/ship_hulls/energy/SH_QUANTUM_ENERGY.focs.txt
  default/scripting/ship_hulls/energy/SH_SOLAR.focs.txt
  default/scripting/ship_hulls/organic/SH_BIOADAPTIVE.focs.txt
  default/scripting/ship_hulls/organic/SH_ENDOMORPHIC.focs.txt
  default/scripting/ship_hulls/organic/SH_ENDOSYMBIOTIC.focs.txt
  default/scripting/ship_hulls/organic/SH_ORGANIC.focs.txt
  default/scripting/ship_hulls/organic/SH_PROTOPLASMIC.focs.txt
  default/scripting/ship_hulls/organic/SH_RAVENOUS.focs.txt
  default/scripting/ship_hulls/organic/SH_SENTIENT.focs.txt
  default/scripting/ship_hulls/organic/SH_STATIC_MULTICELLULAR.focs.txt
  default/scripting/ship_hulls/organic/SH_SYMBIOTIC.focs.txt
  default/scripting/ship_hulls/robotic/SH_LOGITICS_FACILITATOR.focs.txt
  default/scripting/ship_hulls/robotic/SH_NANOROBOTIC.focs.txt
  default/scripting/ship_hulls/robotic/SH_ROBOTIC.focs.txt
  default/scripting/ship_hulls/robotic/SH_SELF_GRAVITATING.focs.txt
  default/scripting/ship_hulls/robotic/SH_SPACE_FLUX_BUBBLE.focs.txt
  default/scripting/ship_hulls/robotic/SH_SPATIAL_FLUX.focs.txt
  default/scripting/ship_hulls/robotic/SH_TITANIC.focs.txt
  default/scripting/ship_hulls/robotic/SH_TRANSSPATIAL.focs.txt
  default/scripting/ship_hulls/ship_hulls.macros
  default/scripting/ship_parts/Fuel/FU_BASIC_TANK.focs.txt
  default/scripting/species/common/fuel.macros
  default/scripting/techs/growth/ENERGY_META.focs.txt
  default/scripting/techs/ship_parts/fuel/SHP_ANTIMATTER_TANK.focs.txt
  default/scripting/techs/ship_parts/fuel/SHP_DEUTERIUM_TANK.focs.txt
  default/stringtables/en.txt
Labels: category:feature, component:content scripting, component:game mechanic

#2512 Save information if empire was eliminated or won
  server/SaveLoad.cpp
  server/ServerFSM.cpp
  util/MultiplayerCommon.h
  util/SerializeMultiplayerCommon.cpp
Labels: category:feature, component:internal, component:network

#2516 Send empire data in ingame lobby
  server/SaveLoad.cpp
  server/SaveLoad.h
  server/ServerFSM.cpp
Labels: category:feature, component:internal, component:network

#2518 Fix AI division by zero
  default/python/AI/DynamicResearchAI.py
  default/python/AI/MilitaryAI.py
Labels: category:bug, component:AI
