Repository freeorion/freeorion, pull requests merged in 2020-04, with the labels that each got.

#2818 Fix behaviour of cookies storage with new config policy
  client/human/HumanClientApp.cpp
  client/human/HumanClientFSM.cpp
Labels: category:bug, component:internal, component:network, priority:high

#2821 Update build docs
  BUILD.md
  CONTRIBUTING.md
Labels: category:tweak, component:deployment, component:technical docs

#2819 Replace some boost libraries with c++14 features
  GG/GG/BrowseInfoWnd.h
  GG/GG/Font.h
  GG/GG/ListBox.h
  GG/src/GUI.cpp
  GG/src/ListBox.cpp
  GG/src/Texture.cpp
  GG/src/gilext/io/png_io.hpp
  GG/src/gilext/io/png_io_private.hpp
  UI/CUIControls.cpp
  UI/CUIControls.h
  UI/CombatReport/GraphicalSummary.cpp
  UI/DesignWnd.cpp
  UI/FleetWnd.cpp
  UI/MapWnd.cpp
  UI/MapWnd.h
  UI/ObjectListWnd.cpp
  UI/ShaderProgram.cpp
  combat/CombatLogManager.cpp
  combat/CombatSystem.cpp
  msvc2017/Common/StdAfx.h
  msvc2017/FreeOrion/StdAfx.h
  msvc2017/FreeOrionCA/StdAfx.h
  msvc2017/FreeOrionD/StdAfx.h
  msvc2017/GiGi/StdAfx.h
  parse/BuildingsParser.cpp
  parse/CommonParamsParser.cpp
  parse/ConditionParser.cpp
  parse/EffectParser.cpp
  parse/FieldsParser.cpp
  parse/FleetPlansParser.cpp
  parse/MonsterFleetPlansParser.cpp
  parse/ReportParseError.cpp
  parse/ReportParseError.h
  parse/ShipDesignsParser.cpp
  parse/ShipHullsParser.cpp
  parse/ShipPartsParser.cpp
  parse/SpecialsParser.cpp
  parse/SpeciesParser.cpp
  parse/TechsParser.cpp
  python/EmpireWrapper.cpp
  python/UniverseWrapper.cpp
  server/ServerApp.cpp
  server/ServerFSM.cpp
  server/ServerNetworking.cpp
  server/ServerNetworking.h
  universe/Conditions.cpp
  universe/Effects.cpp
  universe/Field.cpp
  universe/Fleet.cpp
  universe/Pathfinder.cpp
  universe/Pathfinder.h
  universe/ShipDesign.cpp
  universe/Species.cpp
  util/OptionsDB.h
  util/ScopedTimer.cpp
  util/VarText.cpp
Labels: category:refactoring, component:internal

#2823 Test if gcc compiler suffers from c++/94190 bug
  CMakeLists.txt
  cmake/TestForBug2795.cmake
Labels: category:bug, component:build system

#2812 Unify GG::Clr operations
  GG/GG/Clr.h
  GG/GG/DrawUtil.h
  GG/GG/Spin.h
  GG/src/Button.cpp
  GG/src/Cursor.cpp
  GG/src/DrawUtil.cpp
  GG/src/DropDownList.cpp
  GG/src/Font.cpp
  GG/src/GroupBox.cpp
  GG/src/SDL/SDLGUI.cpp
  GG/src/TabWnd.cpp
  GG/src/dialogs/ColorDlg.cpp
  UI/BuildDesignatorWnd.cpp
  UI/BuildingsPanel.cpp
  UI/CUIControls.cpp
  UI/CUIStyle.cpp
  UI/CUIWnd.cpp
  UI/ClientUI.cpp
  UI/CombatReport/GraphicalSummary.cpp
  UI/DesignWnd.cpp
  UI/EncyclopediaDetailPanel.cpp
  UI/FieldIcon.cpp
  UI/FleetButton.cpp
  UI/FleetWnd.cpp
  UI/GalaxySetupWnd.cpp
  UI/GraphControl.cpp
  UI/IconTextBrowseWnd.cpp
  UI/InGameMenu.cpp
  UI/IntroScreen.cpp
  UI/LinkText.cpp
  UI/MapWnd.cpp
  UI/MeterBrowseWnd.cpp
  UI/MultiplayerLobbyWnd.cpp
  UI/ObjectListWnd.cpp
  UI/PlayerListWnd.cpp
  UI/ProductionWnd.cpp
  UI/QueueListBox.cpp
  UI/ResearchWnd.cpp
  UI/SaveFileDialog.cpp
  UI/SidePanel.cpp
  UI/SitRepPanel.cpp
  UI/SystemIcon.cpp
  UI/TechTreeWnd.cpp
Labels: category:refactoring, component:internal

#2826 Appdata metainfo
  CMakeLists.txt
  ChangeLog.md
  packaging/org.freeorion.FreeOrion.desktop
  packaging/org.freeorion.FreeOrion.metainfo.xml
Labels: category:tweak, component:deployment

#2825 Fix #2809
  default/python/AI/FreeOrionAI.py
Labels: category:bug, component:AI

#2831 Fix Arc Disruptor description
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets

#2810 Make AI aware of allowed combat targets
  default/python/AI/AIDependencies.py
  default/python/AI/AIstate.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/ShipDesignAI.py
Labels: category:tweak, component:AI

#2832 Replace XMLElement::NoSuchChild with std::out_of_range
  util/XMLDoc.cpp
  util/XMLDoc.h
Labels: category:refactoring, component:internal

#2752 String table tool for CI linting
  .travis.yml
  check/st-tool.py
  default/stringtables/en.txt
  default/stringtables/fr.txt
  default/stringtables/ru.txt
Labels: category:feature, component:infrastructure, component:translation, status:work in progress

#2847 Add option to manage if empire should drop readiness on joining
  default/stringtables/en.txt
  server/ServerApp.cpp
  server/ServerFSM.cpp
  server/dmain.cpp
Labels: category:feature, component:network

#2835 Remove GG:::ListBox::Row constructor default parameters
  GG/GG/ListBox.h
  GG/src/ListBox.cpp
  UI/BuildDesignatorWnd.cpp
  UI/CUIControls.cpp
  UI/CensusBrowseWnd.cpp
  UI/DesignWnd.cpp
  UI/FleetWnd.cpp
  UI/GalaxySetupWnd.cpp
  UI/MeterBrowseWnd.cpp
  UI/MultiplayerLobbyWnd.cpp
  UI/ObjectListWnd.cpp
  UI/OptionsWnd.cpp
  UI/PlayerListWnd.cpp
  UI/ProductionWnd.cpp
  UI/QueueListBox.cpp
  UI/ResearchWnd.cpp
  UI/SidePanel.cpp
  UI/SitRepPanel.cpp
  UI/TechTreeWnd.cpp
Labels: category:refactoring, component:internal

#2845 Add options to disable disclosure of galaxy seed
  default/stringtables/en.txt
  network/Message.cpp
  network/Message.h
  server/SaveLoad.cpp
  server/SaveLoad.h
  server/dmain.cpp
  util/MultiplayerCommon.cpp
  util/MultiplayerCommon.h
  util/SerializeMultiplayerCommon.cpp
  util/SerializeUniverse.cpp
Labels: category:feature, component:game mechanic

#2841 Improve AI Turn times
  default/python/AI/AIDependencies.py
  default/python/AI/ColonisationAI.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/EspionageAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/AI/pathfinding.py
  default/python/AI/turn_state.py
  default/python/common/configure_logging.py
Labels: category:refactoring, component:AI

#2848 Format en stringtable
  .travis.yml
  default/stringtables/en.txt
Labels: category:refactoring, component:art music text assets

#1332 Kobuntura should prefer the industry focus
  default/scripting/species/SP_KOBUNTURA.focs.txt
Labels: category:tweak, component:content scripting, status:invalid

#2850 Fix flake8 warnings
  default/python/AI/AIDependencies.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/turn_state.py
  default/python/auth/auth.py
  default/python/common/charting/charts.py
  default/python/common/configure_logging.py
  default/python/stub_generator/parse_docs.py
  default/python/tests/AI/test_savegame_manager.py
Labels: category:refactoring, component:AI

#2745 Start industry and research growth only if happiness is at least five
  default/scripting/species/common/general.macros
  default/scripting/techs/construction/FORCE_ENERGY_STRC.focs.txt
  default/stringtables/en.txt
Labels: category:feature, component:game mechanic, status:testing requested

#2852 [AI] Update flake to newest version
  .travis.yml
  default/python/AI/FreeOrionAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/common/charting/charts.py
  default/python/common/configure_logging.py
  default/python/tox.ini
  default/python/universe_generation/planets.py
  default/python/universe_generation/starsystems.py
Labels: category:refactoring, component:AI

#2853 [AI] Update pytest to newest version
  .travis.yml
  default/python/tests/AI/character_test/character_test.py
  default/python/tests/AI/test_read_only_dict.py
  default/python/tests/AI/test_savegame_manager.py
Labels: category:refactoring, component:AI

#2859 Make COMBAT_TARGETS_PLANET_WITH_DEFENSE macro consider infrastructure
  default/scripting/ship_parts/targeting.macros
Labels: category:bug, component:content scripting, component:game mechanic

#2860 Remove python2 compatilility
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/ColonisationAI.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/EnumsAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/PriorityAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/character/character_module.py
  default/python/AI/freeorion_tools/__init__.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/AI/freeorion_tools/extend_freeorion_AI_interface.py
  default/python/AI/freeorion_tools/interactive_shell.py
  default/python/AI/freeorion_tools/timers.py
  default/python/AI/savegame_codec/__init__.py
  default/python/AI/savegame_codec/_decoder.py
  default/python/AI/savegame_codec/_encoder.py
  default/python/README.md
  default/python/common/charting/charts.py
  default/python/common/configure_logging.py
  default/python/common/listeners.py
  default/python/common/option_tools.py
  default/python/common/print_utils.py
  default/python/common/profiling.py
  default/python/common/six.py
  default/python/common/timers.py
  default/python/mypy.ini
  default/python/py3_migration_pylint_config.ini
  default/python/py3_migration_pylint_runner.py
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/interface_inspector.py
  default/python/stub_generator/parse_docs.py
  default/python/tests/AI/test_savegame_manager.py
  default/python/tox.ini
  default/python/turn_events/turn_events.py
  default/python/universe_generation/empires.py
  default/python/universe_generation/fields.py
  default/python/universe_generation/galaxy.py
  default/python/universe_generation/monsters.py
  default/python/universe_generation/natives.py
  default/python/universe_generation/specials.py
  default/python/universe_generation/starnames.py
  default/python/universe_generation/starsystems.py
  default/python/universe_generation/universe_generator.py
  default/python/universe_generation/universe_statistics.py
  default/python/universe_generation/util.py
Labels: category:refactoring, component:AI

#2863 Start new colonies with some happiness
  default/scripting/species/common/happiness.macros
  default/stringtables/en.txt
Labels: category:tweak, component:content scripting, component:game mechanic

#2846 Stop the game after having winners
  default/stringtables/en.txt
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
Labels: category:feature, component:internal

#2866 Use new LastTurnColonized property for #2862 fix
  default/scripting/species/common/happiness.macros
Labels: category:tweak, component:content scripting

#2865 [AI] Remove old save compatibility
  default/python/AI/savegame_codec/_decoder.py
  default/python/AI/savegame_codec/_encoder.py
  default/python/tests/AI/test_save_game_decoding.py
Labels: category:refactoring, component:AI

#2867 Do not inherit python classes from object
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/ColonisationAI.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/DiplomaticCorp.py
  default/python/AI/EnumsAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/TechsListsAI.py
  default/python/AI/character/character_strings_module.py
  default/python/AI/fleet_orders.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/AI/freeorion_tools/timers.py
  default/python/AI/target.py
  default/python/AI/turn_state.py
  default/python/common/configure_logging.py
  default/python/common/print_utils.py
  default/python/common/timers.py
  default/python/stub_generator/parse_docs.py
  default/python/universe_generation/empires.py
  default/python/universe_generation/galaxy.py
  default/python/universe_generation/monsters.py
Labels: category:refactoring, component:AI

#2864 Don't install unneeded for headless build files
  CMakeLists.txt
Labels: category:feature, component:build system

#2868 Fix missing relevant techs in ShipDesignAI
  default/python/AI/AIDependencies.py
  default/python/AI/ShipDesignAI.py
Labels: category:bug, component:AI

#2870 Rename ItemSpec class to UnlockableItem and move to separate TU files
  Empire/Empire.cpp
  Empire/Empire.h
  UI/EncyclopediaDetailPanel.cpp
  UI/TechTreeWnd.cpp
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/handlers/inspect_freeOrionAIInterface.py
  default/python/stub_generator/parse_docs.py
  default/python/universe_generation/empires.py
  msvc2017/Common/Common.vcxproj
  msvc2017/Common/Common.vcxproj.filters
  parse/EnumParser.cpp
  parse/EnumParser.h
  parse/ItemsParser.cpp
  parse/Parse.cpp
  parse/Parse.h
  parse/TechsParser.cpp
  python/EmpireWrapper.cpp
  python/EnumWrapper.cpp
  server/ServerApp.cpp
  server/ServerWrapper.cpp
  test/parse/TestEnumParser.cpp
  universe/CMakeLists.txt
  universe/Enums.h
  universe/Tech.cpp
  universe/Tech.h
  universe/Universe.cpp
  universe/Universe.h
  universe/UnlockableItem.cpp
  universe/UnlockableItem.h
Labels: category:refactoring, component:internal

#2869 Rename PartType class to ShipPart and move to separate TU files
  Empire/Empire.cpp
  Empire/Empire.h
  Empire/ProductionQueue.cpp
  UI/BuildDesignatorWnd.cpp
  UI/BuildDesignatorWnd.h
  UI/ClientUI.cpp
  UI/DesignWnd.cpp
  UI/DesignWnd.h
  UI/EncyclopediaDetailPanel.cpp
  UI/EncyclopediaDetailPanel.h
  UI/MapWnd.cpp
  UI/MapWnd.h
  UI/MeterBrowseWnd.cpp
  UI/ProductionWnd.cpp
  UI/ProductionWnd.h
  combat/CombatSystem.cpp
  default/python/AI/CombatRatingsAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/handlers/inspect_freeOrionAIInterface.py
  default/python/handlers/inspect_universe_generation.py
  default/python/stub_generator/parse_docs.py
  default/python/stub_generator/stub_functions.py
  default/scripting/ship_parts/Shield/SH_ROBOTIC_INTERFACE_SHIELDS.focs.txt
  msvc2017/Common/Common.vcxproj
  msvc2017/Common/Common.vcxproj.filters
  parse/EnumParser.cpp
  parse/Parse.h
  parse/ShipPartsParser.cpp
  parse/Tokens.h
  python/EnumWrapper.cpp
  python/UniverseWrapper.cpp
  test/parse/TestEnumParser.cpp
  universe/CMakeLists.txt
  universe/CommonParams.h
  universe/Conditions.cpp
  universe/Enums.h
  universe/Ship.cpp
  universe/ShipDesign.cpp
  universe/ShipDesign.h
  universe/ShipPart.cpp
  universe/ShipPart.h
  universe/ShipPartHull.h
  universe/Universe.cpp
  universe/ValueRefs.cpp
  util/AppInterface.cpp
  util/SerializeEmpire.cpp
  util/VarText.cpp
  util/VarText.h
Labels: category:refactoring, component:internal

#2858 Merge EventPump logic into GG::GUI::RunModal
  GG/GG/CMakeLists.txt
  GG/GG/DropDownList.h
  GG/GG/EventPump.h
  GG/GG/GUI.h
  GG/GG/Wnd.h
  GG/doc/GGDoc.txt
  GG/src/CMakeLists.txt
  GG/src/DropDownList.cpp
  GG/src/EventPump.cpp
  GG/src/GUI.cpp
  GG/src/Wnd.cpp
  UI/SDLGUI.cpp
  UI/SDLGUI.h
  UI/SidePanel.cpp
  client/AI/AIClientApp.cpp
  client/AI/AIClientApp.h
  client/AI/camain.cpp
  client/human/HumanClientFSM.cpp
  client/human/chmain.cpp
  msvc2017/GiGi/GiGi.vcxproj
  msvc2017/GiGi/GiGi.vcxproj.filters
  test/UI/runner/Application.cpp
Labels: category:refactoring, component:internal

#2873 Fix st-tool bug and improve documentation
  check/st-tool.py
Labels: category:bug, component:infrastructure

#2871 Simplify ShipDesignAI
  default/python/AI/ShipDesignAI.py
  python/UniverseWrapper.cpp
Labels: category:refactoring, component:AI

#2879 Let outposts have minimum construction one, in order to be attacked
  default/scripting/starting_unlocks/items.inf
  default/scripting/techs/construction/OUTPOST.focs.txt
  default/stringtables/en.txt
Labels: category:bug, category:tweak, component:content scripting, component:game mechanic

#2877 Move FleetPlan to separate TU files
  msvc2017/Common/Common.vcxproj
  msvc2017/Common/Common.vcxproj.filters
  msvc2017/FreeOrionD/FreeOrionD.vcxproj
  msvc2017/FreeOrionD/FreeOrionD.vcxproj.filters
  parse/FleetPlansParser.cpp
  parse/MonsterFleetPlansParser.cpp
  server/CMakeLists.txt
  server/ServerApp.cpp
  server/ServerFramework.cpp
  server/ServerWrapper.cpp
  server/UniverseGenerator.cpp
  server/UniverseGenerator.h
  universe/CMakeLists.txt
  universe/FleetPlan.cpp
  universe/FleetPlan.h
  universe/Universe.cpp
  universe/UniverseGenerator.h
Labels: category:refactoring, component:internal

#2878 Move FieldType to separate TU files
  UI/ClientUI.cpp
  UI/EncyclopediaDetailPanel.cpp
  msvc2017/Common/Common.vcxproj
  msvc2017/Common/Common.vcxproj.filters
  msvc2017/FreeOrion/FreeOrion.vcxproj
  msvc2017/FreeOrion/FreeOrion.vcxproj.filters
  parse/FieldsParser.cpp
  python/UniverseWrapper.cpp
  server/ServerWrapper.cpp
  universe/CMakeLists.txt
  universe/Effects.cpp
  universe/Field.cpp
  universe/Field.h
  universe/FieldType.cpp
  universe/FieldType.h
  universe/Universe.cpp
  util/AppInterface.cpp
Labels: category:refactoring, component:internal

#2880 Simplify public logger interface
  python/LoggingWrapper.cpp
  util/Logger.cpp
  util/Logger.h
Labels: category:refactoring, component:internal

#2884 Use more Markdown documentation in Doxygen
  BUILD.md
  CONTRIBUTING.md
  ChangeLog.md
  README.md
  doc/CMakeLists.txt
  doc/Doxyfile.in
  doc/all_tags.dox.in
  doc/content_tags.md
  doc/content_tags_alias.dox
  doc/tag_parser.py
Labels: category:refactoring, component:build system, component:deployment, component:technical docs

#2876 Move BuildingType to separate TU files
  Empire/Empire.cpp
  Empire/ProductionQueue.cpp
  UI/BuildDesignatorWnd.cpp
  UI/BuildingsPanel.cpp
  UI/ChatWnd.cpp
  UI/ClientUI.cpp
  UI/EncyclopediaDetailPanel.cpp
  UI/ProductionWnd.cpp
  client/AI/AIFramework.cpp
  msvc2017/Common/Common.vcxproj
  msvc2017/Common/Common.vcxproj.filters
  parse/BuildingsParser.cpp
  python/UniverseWrapper.cpp
  server/ServerWrapper.cpp
  universe/Building.cpp
  universe/Building.h
  universe/BuildingType.cpp
  universe/BuildingType.h
  universe/CMakeLists.txt
  universe/Conditions.cpp
  universe/Effects.cpp
  universe/Planet.cpp
  universe/Universe.cpp
  util/AppInterface.cpp
Labels: category:refactoring, component:internal

#2888 Use different variable name to avoid variable shadowing
  UI/DesignWnd.cpp
Labels: category:bug, component:UI

#2891 Rename Fighter (FT_HANGAR_2) to Strike Fighter
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets

#2885 Exclude engines from colony base hull
  default/scripting/ship_parts/Fuel/FU_BASIC_TANK.focs.txt
  default/scripting/ship_parts/Fuel/FU_RAMSCOOP.focs.txt
  default/scripting/ship_parts/Fuel/FU_ZERO_FUEL.focs.txt
  default/scripting/ship_parts/Speed/FU_IMPROVED_ENGINE_COUPLINGS.focs.txt
  default/scripting/ship_parts/Speed/FU_N_DIMENSIONAL_ENGINE_MATRIX.focs.txt
  default/scripting/ship_parts/Speed/FU_SINGULARITY_ENGINE_CORE.focs.txt
  default/scripting/ship_parts/Speed/FU_TRANSPATIAL_DRIVE.focs.txt
Labels: category:tweak, component:content scripting

#2886 Make AI aware of excluded parts in SH_COLONY_BASE
  default/python/AI/AIDependencies.py
  default/python/AI/ShipDesignAI.py
Labels: category:tweak, component:AI

#2837 better words for various sorts of exiting the game
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets

#2894 Add codeowners for russian translation
  .github/CODEOWNERS
Labels: component:infrastructure

#2904 Restrict interceptor launch bay upgrade to tech of own empire
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_1.focs.txt
Labels: category:bug, component:content scripting

#2911 Add comment about readonly dict implementation
  default/python/AI/freeorion_tools/_freeorion_tools.py
Labels: category:tweak, component:AI, component:technical docs

#2889 Move ShipHull to separate TU files
  Empire/Empire.cpp
  Empire/Empire.h
  Empire/ProductionQueue.cpp
  UI/BuildDesignatorWnd.cpp
  UI/ClientUI.cpp
  UI/DesignWnd.cpp
  UI/DesignWnd.h
  UI/EncyclopediaDetailPanel.cpp
  UI/EncyclopediaDetailPanel.h
  UI/MapWnd.cpp
  UI/MapWnd.h
  default/python/AI/ShipDesignAI.py
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/handlers/inspect_freeOrionAIInterface.py
  default/python/handlers/inspect_universe_generation.py
  default/python/stub_generator/parse_docs.py
  default/python/stub_generator/stub_functions.py
  default/python/universe_generation/monsters.py
  msvc2017/Common/Common.vcxproj
  parse/Parse.h
  parse/ShipHullsParser.cpp
  parse/Tokens.h
  python/UniverseWrapper.cpp
  universe/CMakeLists.txt
  universe/CommonParams.h
  universe/Conditions.cpp
  universe/Ship.cpp
  universe/ShipDesign.cpp
  universe/ShipDesign.h
  universe/ShipHull.cpp
  universe/ShipHull.h
  universe/ShipPartHull.h
  universe/Universe.cpp
  universe/ValueRefs.cpp
  util/AppInterface.cpp
  util/SerializeEmpire.cpp
  util/VarText.cpp
  util/VarText.h
Labels: category:refactoring, component:internal

#2896 Set ship speed for new ships to be affected by Interstellar Logistics
  Empire/Empire.cpp
Labels: category:tweak, component:game mechanic

#2890 Cheaper shields
  default/scripting/ship_parts/Shield/SH_BLACK.focs.txt
  default/scripting/ship_parts/Shield/SH_DEFENSE_GRID.focs.txt
  default/scripting/ship_parts/Shield/SH_DEFLECTOR.focs.txt
  default/scripting/ship_parts/Shield/SH_MULTISPEC.focs.txt
  default/scripting/ship_parts/Shield/SH_PLASMA.focs.txt
  default/scripting/ship_parts/Shield/SH_ROBOTIC_INTERFACE_SHIELDS.focs.txt
Labels: category:tweak, component:content scripting

#2913 Don't overwrite ship design with same ID
  universe/Universe.cpp
  util/Order.cpp
Labels: category:bug, priority:high
