Repository freeorion/freeorion, pull requests merged in 2020-08, with the labels that each got.

#3130 Nonintrusive serialization combat
  combat/CombatEvent.h
  combat/CombatSystem.h
  util/SerializeCombat.cpp
Labels: category:refactoring, component:internal, status:merged

#3128 Improve DAMAGE_TEXT for average/total fighter damage and four bouts
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets, component:content scripting

#3127 Apply SHIP_WEAPON_DAMAGE_FACTOR scaling to species weapon bonus
  default/python/AI/AIDependencies.py
  default/scripting/species/common/weapons.macros
  default/stringtables/en.txt
Labels: category:bug, component:content scripting, status:cherry-pick for release, status:merged

#3141 Don't make max shield meter effects depend on combat conditions in system
  default/scripting/techs/defense/BarrierShield.focs.txt
Labels: category:bug, component:content scripting, status:cherry-pick for release

#3132 Rename tests
  .gitignore
  default/python/AI/savegame_codec/_encoder.py
  default/python/tests/AI/test_parse_ai_tag_grade.py
  default/python/tests/AI/test_read_only_dict.py
  default/python/tests/AI/test_save_game_decoding.py
Labels: category:refactoring, component:AI

#3117 Add tech group tests
  default/python/AI/TechsListsAI.py
  default/python/tests/AI/test_tech_groups.py
Labels: category:bug, component:AI

#2920 Improve chat debugging
  default/python/AI/FreeOrionAI.py
  default/python/AI/freeorion_tools/__init__.py
  default/python/AI/freeorion_tools/chat_handler/__init__.py
  default/python/AI/freeorion_tools/chat_handler/base_chat_handler.py
  default/python/AI/freeorion_tools/chat_handler/chat_formatter.py
  default/python/AI/freeorion_tools/chat_handler/debug_chat_handler.py
  default/python/AI/freeorion_tools/chat_handler/interpreter.py
  default/python/AI/freeorion_tools/chat_handler/normal_chat_handler.py
  default/python/AI/freeorion_tools/chat_handler/shell_variable.py
  default/python/AI/freeorion_tools/fo_chat_handler.py
  default/python/AI/freeorion_tools/interactive_shell.py
  default/python/common/option_tools.py
  default/python/tests/AI/test_debug_chat.py
  default/python/tox.ini
Labels: category:refactoring, component:AI, status:work in progress

#3142 Revert "Make serialization of Meter less intrusive"
  universe/Meter.h
  util/Serialize.h
  util/SerializeUniverse.cpp
Labels: category:bug, component:internal, status:merged

#3150 Fix Fleet Crash
  UI/ClientUI.cpp
  universe/Pathfinder.cpp
Labels: category:bug, component:UI, status:cherry-pick for release

#3149 Icons for Arc Disruptor resaved with GIMP
  default/data/art/icons/ship_parts/pulse-laser-1.png
  default/data/art/icons/ship_parts/pulse-laser-2.png
  default/data/art/icons/ship_parts/pulse-laser-3.png
  default/data/art/icons/ship_parts/pulse-laser-4.png
Labels: category:bug, component:art music text assets, status:cherry-pick for release

#3146 Collection of fixes for Flathub submission
  packaging/org.freeorion.FreeOrion.metainfo.xml
Labels: category:bug, component:deployment

#3145 cmake: Ignore Git errors when generating version
  cmake/make_versioncpp.py
Labels: category:bug, component:build system, status:cherry-pick for release
