Repository freeorion/freeorion, pull requests merged in 2020-02, with the labels that each got.

#2718 Empire readiness refactoring
  Empire/Empire.cpp
  Empire/Empire.h
  UI/PlayerListWnd.cpp
  UI/PlayerListWnd.h
  client/AI/AIClientApp.cpp
  client/ClientApp.cpp
  client/ClientApp.h
  client/human/HumanClientApp.cpp
  client/human/HumanClientFSM.cpp
  server/ServerApp.cpp
  server/ServerFSM.cpp
  test/system/ClientAppFixture.cpp
  util/MultiplayerCommon.h
  util/SerializeEmpire.cpp
  util/SerializeMultiplayerCommon.cpp
Labels: category:refactoring, component:internal, component:network

#2729 Alliances
  default/python/AI/AIstate.py
  default/python/AI/DiplomaticCorp.py
  default/python/AI/character/character_module.py
  default/stringtables/en.txt
  test/parse/TestEnumParser.cpp
  universe/Condition.cpp
Labels: category:feature, component:AI, component:game mechanic, component:internal

#2737 Fix unit test dict items comparison
  default/python/tests/AI/test_read_only_dict.py
Labels: category:bug, component:internal

#2738 Optimizing Effect Accounting
  universe/EffectAccounting.cpp
  universe/EffectAccounting.h
  universe/Universe.cpp
  universe/Universe.h
Labels: category:tweak, component:internal

#2739 Align indentation.
  default/python/AI/AIDependencies.py
Labels: category:tweak, component:AI

#2741 Use boost::ranges for ObjectMap::all function
  Empire/Empire.cpp
  UI/BuildDesignatorWnd.cpp
  UI/ChatWnd.cpp
  UI/EncyclopediaDetailPanel.cpp
  UI/MapWnd.cpp
  UI/MapWnd.h
  UI/ObjectListWnd.cpp
  combat/CombatLogManager.cpp
  combat/CombatSystem.cpp
  python/UniverseWrapper.cpp
  server/ServerApp.cpp
  universe/ObjectMap.cpp
  universe/ObjectMap.h
  universe/Universe.cpp
  universe/UniverseGenerator.cpp
  util/ModeratorAction.cpp
Labels: category:refactoring, component:internal

#2735 Use Ubuntu Bionic for Travis jobs
  .travis.yml
Labels: category:tweak, component:infrastructure

#2742 Replace boost::timer
  AI/AIInterface.cpp
  UI/DesignWnd.cpp
  UI/EncyclopediaDetailPanel.cpp
  UI/MapWnd.cpp
  UI/TechTreeWnd.cpp
  msvc2017/Parsers/StdAfx.h
  network/Message.cpp
  parse/ParseImpl.h
  python/AI/AIFramework.cpp
  python/AI/AIWrapper.cpp
  universe/Fleet.cpp
  universe/Universe.cpp
  util/ScopedTimer.cpp
  util/ScopedTimer.h
Labels: category:refactoring, component:internal

#2743 cmake: make make_versioncpp.py be py2&3 compatible
  cmake/make_versioncpp.py
Labels: category:tweak, component:build system

#2733 [AI] Add mypy config scripts and ignore comment for non game files
  .gitignore
  default/python/AI/freeOrionAIInterface.pyi
  default/python/README.md
  default/python/common/six.py
  default/python/freeorion.pyi
  default/python/mypy.ini
  default/python/stub_generator/generate_stub.py
Labels: category:tweak, component:AI

#2736 Expose option to append fleet move orders.
  python/AI/AIWrapper.cpp
Labels: category:tweak, component:AI, component:internal

#2749 Merge duplicate ValueRef code for logging unknown properties
  universe/ValueRefs.cpp
Labels: category:refactoring, component:internal

#2754 Simplify predicates
  Empire/Supply.cpp
  UI/EncyclopediaDetailPanel.cpp
  UI/MapWnd.cpp
  UI/SidePanel.cpp
  python/UniverseWrapper.cpp
  server/ServerApp.cpp
  universe/Predicates.cpp
  universe/Predicates.h
Labels: category:refactoring, component:internal

#2755 Use objectmap interface
  Empire/Empire.cpp
  Empire/PopulationPool.cpp
  Empire/ProductionQueue.cpp
  Empire/Supply.cpp
  UI/BuildDesignatorWnd.cpp
  UI/BuildingsPanel.cpp
  UI/ClientUI.cpp
  UI/CombatReport/CombatLogWnd.cpp
  UI/CombatReport/GraphicalSummary.cpp
  UI/DesignWnd.cpp
  UI/EncyclopediaDetailPanel.cpp
  UI/FieldIcon.cpp
  UI/FleetButton.cpp
  UI/FleetWnd.cpp
  UI/MapWnd.cpp
  UI/MeterBrowseWnd.cpp
  UI/MilitaryPanel.cpp
  UI/MilitaryPanel.h
  UI/MultiIconValueIndicator.cpp
  UI/MultiMeterStatusBar.cpp
  UI/ObjectListWnd.cpp
  UI/PopulationPanel.cpp
  UI/PopulationPanel.h
  UI/ProductionWnd.cpp
  UI/ResourcePanel.cpp
  UI/ResourcePanel.h
  UI/SidePanel.cpp
  UI/SpecialsPanel.cpp
  UI/SystemIcon.cpp
  UI/SystemResourceSummaryBrowseWnd.cpp
  combat/CombatEvents.cpp
  combat/CombatSystem.cpp
  python/EmpireWrapper.cpp
  python/UniverseWrapper.cpp
  python/server/ServerWrapper.cpp
  server/ServerApp.cpp
  universe/Building.cpp
  universe/Conditions.cpp
  universe/Effects.cpp
  universe/Fleet.cpp
  universe/Pathfinder.cpp
  universe/Planet.cpp
  universe/Ship.cpp
  universe/ShipDesign.cpp
  universe/Special.cpp
  universe/Species.cpp
  universe/System.cpp
  universe/Universe.cpp
  universe/UniverseGenerator.cpp
  universe/UniverseObject.cpp
  universe/ValueRefs.cpp
  util/AppInterface.h
  util/ModeratorAction.cpp
  util/Order.cpp
  util/SitRepEntry.cpp
  util/VarText.cpp
Labels: category:refactoring, component:internal

#2757 Slnko is a Slovak Sun
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets

#2748 Fix pylint warnings part 2
  default/python/AI/AIstate.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/EnumsAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/PriorityAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/character/character_module.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/AI/target.py
  default/python/py3_migration_pylint_config.ini
  default/python/universe_generation/galaxy.py
  default/python/universe_generation/starnames.py
  default/python/universe_generation/starsystems.py
Labels: category:refactoring, component:AI

#2751 Simplify CMake buildsystem
  CMakeLists.txt
  GG/CMakeLists.txt
  GG/GG/Export.h
  GG/GG/Flags.h
  GG/GG/SDL/SDLGUI.h
  GG/test/acceptance/CMakeLists.txt
  GG/test/unit/CMakeLists.txt
  cmake/FindBoost.cmake
  test/parse/CMakeLists.txt
  test/system/CMakeLists.txt
  test/util/CMakeLists.txt
Labels: category:tweak, component:build system

#2750 Ignore failures of unittest
  .travis.yml
Labels: category:tweak, component:infrastructure

#2761 Check both python versions lints
  .travis.yml
  default/python/common/charting/charts.py
  default/python/universe_generation/empires.py
Labels: category:refactoring, component:AI, component:content scripting, component:infrastructure, priority:high

#2746 Move packaging files
  .appveyor.yml
  CMakeLists.txt
  client/human/CMakeLists.txt
  client/human/FreeOrion.icns
  client/human/FreeOrion.ico
  client/human/FreeOrion.rc
  client/human/main.xib
  cmake/make_versioncpp.py
  msvc2015/FreeOrion/FreeOrion.vcxproj
  msvc2015/FreeOrion/FreeOrion.vcxproj.filters
  msvc2017/FreeOrion/FreeOrion.vcxproj
  msvc2017/FreeOrion/FreeOrion.vcxproj.filters
  packaging/Info.plist.in
  packaging/freeorion.desktop
  packaging/windows_installer.nsi.in
  snap/snapcraft.yaml
Labels: category:refactoring, component:infrastructure

#2760 Prune stale translations
  default/stringtables/cz.txt
  default/stringtables/de.txt
  default/stringtables/es.txt
  default/stringtables/fi.txt
  default/stringtables/it.txt
  default/stringtables/nl.txt
  default/stringtables/pl.txt
  default/stringtables/sv.txt
Labels: category:bug, component:translation

#2747 Move AI client, general client and server sources to place of use
  AI/CMakeLists.txt
  CMakeLists.txt
  UI/ChatWnd.cpp
  UI/MapWnd.cpp
  UI/MultiplayerLobbyWnd.cpp
  UI/ObjectListWnd.cpp
  UI/PasswordEnterWnd.cpp
  UI/PlayerListWnd.cpp
  UI/ServerConnectWnd.cpp
  client/AI/AIClientApp.cpp
  client/AI/AIFramework.cpp
  client/AI/AIFramework.h
  client/AI/AIInterface.cpp
  client/AI/AIInterface.h
  client/AI/AIWrapper.cpp
  client/AI/AIWrapper.h
  client/AI/CMakeLists.txt
  client/CMakeLists.txt
  client/ClientApp.cpp
  client/ClientNetworking.cpp
  client/ClientNetworking.h
  client/human/HumanClientApp.cpp
  client/human/HumanClientFSM.cpp
  msvc2015/FreeOrion/FreeOrion.vcxproj
  msvc2015/FreeOrion/FreeOrion.vcxproj.filters
  msvc2015/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2015/FreeOrionCA/FreeOrionCA.vcxproj.filters
  msvc2015/FreeOrionD/FreeOrionD.vcxproj
  msvc2015/FreeOrionD/FreeOrionD.vcxproj.filters
  msvc2017/FreeOrion/FreeOrion.vcxproj
  msvc2017/FreeOrion/FreeOrion.vcxproj.filters
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj.filters
  msvc2017/FreeOrionD/FreeOrionD.vcxproj
  msvc2017/FreeOrionD/FreeOrionD.vcxproj.filters
  network/CMakeLists.txt
  python/AI/CMakeLists.txt
  python/CMakeLists.txt
  python/server/CMakeLists.txt
  python/server/ServerWrapper.h
  server/CMakeLists.txt
  server/ServerApp.h
  server/ServerFSM.cpp
  server/ServerFramework.cpp
  server/ServerFramework.h
  server/ServerNetworking.cpp
  server/ServerNetworking.h
  server/ServerWrapper.cpp
  server/ServerWrapper.h
  test/system/CMakeLists.txt
  test/system/ClientAppFixture.cpp
Labels: category:refactoring, component:internal

#2762 Enable unittests on MacOS
  .travis.yml
  GG/test/acceptance/CMakeLists.txt
Labels: category:tweak, component:infrastructure, status:help wanted

#2766 Python3 compatibility fixes
  default/python/AI/character/character_module.py
  default/python/AI/freeorion_tools/timers.py
  default/python/common/charting/charts.py
  default/python/common/option_tools.py
  default/python/common/profiling.py
  default/python/universe_generation/empires.py
  default/python/universe_generation/starnames.py
  default/python/universe_generation/universe_generator.py
Labels: category:refactoring, component:AI, component:content scripting, priority:high

#2768 [AI] fix warnings about division
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/character/character_module.py
  default/python/universe_generation/galaxy.py
  default/python/universe_generation/monsters.py
  default/python/universe_generation/specials.py
  default/python/universe_generation/starnames.py
  default/python/universe_generation/universe_statistics.py
Labels: category:refactoring, component:AI, priority:high

#2764 Simplify AI client
  client/AI/AIClientApp.cpp
  client/AI/AIClientApp.h
  client/AI/AIFramework.cpp
  client/AI/AIFramework.h
  client/AI/AIInterface.cpp
  client/AI/AIInterface.h
  client/AI/AIWrapper.cpp
  client/AI/CMakeLists.txt
  default/python/AI/FreeOrionAI.py
  msvc2015/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2015/FreeOrionCA/FreeOrionCA.vcxproj.filters
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj.filters
Labels: category:refactoring, component:AI, component:internal

#2767 Yet another set of python fixes.
  default/python/AI/ColonisationAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/savegame_codec/_decoder.py
  default/python/AI/savegame_codec/_encoder.py
  default/python/common/print_utils.py
Labels: category:refactoring, component:AI, component:content scripting, priority:high

#2770 Allocate list from iterator to fix python3 errors
  default/python/AI/AIstate.py
  default/python/AI/ColonisationAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/ResourcesAI.py
Labels: category:refactoring, component:AI, priority:high

#2771 [AI] Fix pylint warnings
  default/python/AI/CombatRatingsAI.py
  default/python/AI/ShipDesignAI.py
  default/python/universe_generation/galaxy.py
Labels: category:refactoring, component:AI, priority:high

#2772 [AI] Fix pylint warnings
  default/python/AI/ColonisationAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/ResourcesAI.py
Labels: category:refactoring, component:AI, priority:high

#2773 [AI] Fix pylint warnings
  default/python/AI/PriorityAI.py
  default/python/AI/ProductionAI.py
Labels: category:refactoring, component:AI, priority:high

#2774 Enable sharing of special visibility between allied empires
  universe/Universe.cpp
Labels: category:bug, component:game mechanic, component:internal

#2763 Simplify Travis CI configuration
  .travis.yml
Labels: category:tweak, component:infrastructure

#2759 Produce error if checksum on the server and the client or AI differs
  client/AI/AIClientApp.cpp
  client/human/HumanClientFSM.cpp
  default/stringtables/en.txt
  test/system/ClientAppFixture.cpp
Labels: category:feature, component:internal, component:network

#2698 Add CombatBout ValueRef
  combat/CombatSystem.cpp
  combat/CombatSystem.h
  parse/IntValueRefParser.cpp
  parse/Tokens.h
  universe/Conditions.cpp
  universe/ScriptingContext.h
  universe/Universe.cpp
  universe/Universe.h
  universe/ValueRefs.cpp
Labels: category:feature, component:content scripting, component:internal

#2778 Hopefully fix linker warnings.
  universe/ScriptingContext.h
Labels: category:bug, component:internal

#2780 Fix gcc warnings
  GG/src/nanovg/stb_image.h
  UI/DesignWnd.cpp
  util/SerializeMultiplayerCommon.cpp
Labels: category:tweak, component:internal

#2779 Match GG::Key enum values to USB HID key{board,pad} scancodes
  GG/GG/Base.h
  GG/GG/SDL/SDLGUI.h
  GG/GG/Slider.h
  GG/GG/Spin.h
  GG/src/Base.cpp
  GG/src/Edit.cpp
  GG/src/EventPump.cpp
  GG/src/GUI.cpp
  GG/src/SDL/SDLGUI.cpp
  GG/src/WndEvent.cpp
  UI/Hotkeys.cpp
  UI/MapWnd.cpp
  UI/OptionsWnd.cpp
Labels: category:refactoring, component:internal

#2783 Remove seemingly unnecessary use of deprecated std::unary_function.
  GG/GG/ListBox.h
Labels: category:refactoring, component:internal
