Repository freeorion/freeorion, pull requests merged in 2020-10, with the labels that each got.

#3179 Give Trith influence focus
  default/scripting/species/SP_TRITH.focs.txt
Labels: category:bug, category:tweak, component:content scripting, status:merged

#3183 Tag template instantiations of NamedRef also as struct like declared
  universe/NamedValueRefManager.cpp
Labels: category:refactoring, component:internal

#3187 change to python3
  default/python/common/charting/charts.py
Labels: category:tweak, component:infrastructure

#3185 Colo threshold sitrep takes growth rate from macro
  default/scripting/techs/ship_hulls/SHP_GAL_EXPLO.focs.txt
Labels: category:bug, component:content scripting

#3194 Use expr instead of primary_expr when parsing NamedReal in the middle…
  parse/DoubleValueRefParser.cpp
Labels: category:bug, component:content scripting

#3196 Use std::array instead of GG::Clr in common and server code
  Empire/Empire.cpp
  Empire/Empire.h
  Empire/EmpireManager.cpp
  Empire/EmpireManager.h
  GG/GG/Clr.h
  UI/MultiplayerLobbyWnd.cpp
  client/human/HumanClientApp.cpp
  combat/CombatEvents.cpp
  default/python/AI/FreeOrionAI.py
  default/python/chat/chat.py
  parse/Parse.cpp
  parse/Parse.h
  parse/ParseImpl.h
  parse/TechsParser.cpp
  python/EmpireWrapper.cpp
  server/SaveLoad.cpp
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
  server/ServerFramework.cpp
  server/ServerWrapper.cpp
  server/UniverseGenerator.cpp
  test/system/ClientAppFixture.cpp
  universe/Tech.cpp
  universe/Tech.h
  util/MultiplayerCommon.h
  util/SaveGamePreviewUtils.h
  util/Serialize.h
  util/Serialize.ipp
  util/SerializeEmpire.cpp
  util/SerializeMultiplayerCommon.cpp
Labels: category:refactoring, component:internal, component:network

#3198 Remove usage of GiGi's utf8 in common and server code
  client/AI/camain.cpp
  server/dmain.cpp
  util/Directories.cpp
Labels: category:refactoring, category:tweak, component:internal

#3197 Removes usage of GG_ENUM in common and server code.
  Empire/Diplomacy.h
  Empire/Empire.h
  Empire/ProductionQueue.h
  Empire/ResourcePool.h
  UI/BuildDesignatorWnd.h
  UI/EncyclopediaDetailPanel.h
  UI/ModeratorActionsWnd.h
  msvc2017/Common/Common.vcxproj
  network/Message.h
  server/ServerNetworking.cpp
  universe/BuildingType.h
  universe/CMakeLists.txt
  universe/Conditions.h
  universe/Effect.h
  universe/Enums.h
  universe/Fleet.h
  universe/Planet.h
  universe/ResourceCenter.h
  universe/ShipHull.h
  universe/ShipPart.h
  universe/Species.h
  universe/System.h
  universe/UniverseObject.h
  universe/UnlockableItem.h
  util/CMakeLists.txt
  util/Directories.h
  util/Enum.h
  util/MultiplayerCommon.h
Labels: category:refactoring, component:internal, component:network

#3200 Don't use GG in a headless build
  CMakeLists.txt
  GG/CMakeLists.txt
  client/AI/AIClientApp.cpp
  test/parse/CMakeLists.txt
  test/system/CMakeLists.txt
  test/util/CMakeLists.txt
Labels: category:refactoring, component:build system, component:internal

#3201 Use separate build option for each component
  .travis.yml
  CMakeLists.txt
  client/CMakeLists.txt
  combat/CMakeLists.txt
  python/CMakeLists.txt
  test/CMakeLists.txt
  util/CMakeLists.txt
Labels: category:refactoring, component:build system

#3208 Server's python refactoring
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
Labels: category:feature, component:internal

#3209 Iterate over all FO_ENUM values
  default/python/AI/ProductionAI.py
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  python/EnumWrapper.cpp
  util/Enum.h
Labels: category:refactoring, component:AI, component:internal

#3206 show named value user string only when hovering
  UI/EncyclopediaDetailPanel.cpp
  UI/LinkText.cpp
  check/st-tool.py
  parse/IntValueRefParser.cpp
Labels: category:bug, component:UI, component:content scripting

#3212 Cleanup GiGi usage from MSVC project
  msvc2017/Common/Common.vcxproj
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2017/FreeOrionD/FreeOrionD.vcxproj
  msvc2017/Parsers/Parsers.vcxproj
  util/Process.cpp
Labels: category:refactoring, component:build system
