Repository freeorion/freeorion, pull requests merged in 2020-07, with the labels that each got.

#3078 Use CMake targets to do CI linting checks
  .travis.yml
  check/CMakeLists.txt
  check/pep8.ini.in
  cmake/FindCPPCheck.cmake
  cmake/FindFlake8.cmake
  cmake/FindPyCodestyle.cmake
  default/python/tox.ini
Labels: category:refactoring, component:infrastructure

#3034 Remove redundant prereq from Nova Bomb, substitute Stellar Tomography
  default/scripting/techs/ship_weapons/SHP_NOVA_BOMB.focs.txt
Labels: category:bug, component:content scripting

#3081 Stop Duplicate Production UUID and Grooming
  Empire/Empire.cpp
  Empire/ProductionQueue.cpp
  UI/ObjectListWnd.cpp
  UI/ProductionWnd.cpp
  server/ServerApp.cpp
  util/Order.cpp
  util/OrderSet.cpp
  util/OrderSet.h
  util/SerializeOrderSet.cpp
Labels: category:bug, category:tweak, component:game mechanic, status:cherry-pick for release

#3079 Exclude data for universe generator from checksum
  universe/Special.cpp
Labels: category:tweak, component:content scripting, component:internal, status:cherry-pick for release, status:merged

#3088 Fix Sly refueling
  default/scripting/species/SP_SLY.focs.txt
Labels: category:bug, component:content scripting, status:cherry-pick for release, status:merged

#3084 Nonintrusive serialization remove unused serialization features
  universe/ShipHull.h
  universe/ShipPart.h
  universe/Special.h
Labels: category:refactoring, component:internal

#3002 Sly & Gaia special - prevent type cycling, reweight colonization
  default/python/AI/ColonisationAI.py
  default/scripting/specials/planet/GAIA.focs.txt
  universe/Species.cpp
Labels: category:bug, component:content scripting

#3092 Update README.md
  default/python/README.md
Labels: category:tweak, component:technical docs

#3096 Remove unused ProductionQueue::Element constructors
  Empire/ProductionQueue.cpp
  Empire/ProductionQueue.h
Labels: category:refactoring, component:internal

#3095 Rename DiplomaticMessage::{DiplomaticMessageType,Type}; convert to enum class
  Empire/Diplomacy.cpp
  Empire/Diplomacy.h
  Empire/EmpireManager.cpp
  UI/PlayerListWnd.cpp
  python/EmpireWrapper.cpp
  python/EnumWrapper.cpp
Labels: category:refactoring, component:internal

#3097 Use python namespace alias consistent
  client/AI/AIFramework.cpp
  client/AI/AIWrapper.cpp
  python/CommonFramework.cpp
  python/ConfigWrapper.cpp
  python/EmpireWrapper.cpp
  python/EnumWrapper.cpp
  python/SetWrapper.h
  python/UniverseWrapper.cpp
  server/ServerFramework.cpp
  server/ServerWrapper.cpp
Labels: category:refactoring, component:internal

#3022 v0.4.10 changelog update
  ChangeLog.md
Labels: component:deployment

#3094 AI determine Colony ship build time and build cost from available parts
  default/python/AI/AIDependencies.py
  default/python/AI/ColonisationAI.py
  default/python/AI/PriorityAI.py
Labels: category:bug, component:AI

#3101 Remove unnecessary step (check-python)
  .travis.yml
  check/CMakeLists.txt
Labels: category:refactoring, component:infrastructure

#3100 Refactor Python bindings
  client/AI/AIFramework.cpp
  client/AI/AIWrapper.cpp
  python/ConfigWrapper.cpp
  python/EmpireWrapper.cpp
  python/UniverseWrapper.cpp
  server/ServerFramework.cpp
  server/ServerWrapper.cpp
Labels: category:refactoring, component:AI, component:internal

#3107 Nonintrusive serialization universe
  universe/Building.cpp
  universe/Building.h
  universe/Field.cpp
  universe/Field.h
  universe/Fleet.cpp
  universe/Fleet.h
  universe/IDAllocator.h
  universe/Meter.h
  universe/ObjectMap.h
  universe/Planet.cpp
  universe/Planet.h
  universe/PopCenter.h
  universe/ResourceCenter.h
  universe/Ship.h
  universe/ShipDesign.cpp
  universe/ShipDesign.h
  universe/System.cpp
  universe/System.h
  universe/Universe.h
  universe/UniverseObject.h
  universe/ValueRefs.h
  util/Serialize.h
  util/SerializeUniverse.cpp
Labels: category:refactoring, component:internal

#3115 Fix Experimentors sitrep about spotted monsters
  default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.txt
Labels: category:bug, component:content scripting

#3119 Fix deserialization errors of ShipDesigns
  universe/ShipDesign.cpp
  universe/ShipDesign.h
  util/SerializeUniverse.cpp
Labels: category:bug, component:internal, component:network

#3116 Tech groups better error reporting
  default/python/AI/TechsListsAI.py
Labels: category:bug, component:AI

#3123 Fixes errors with boost::placeholders::_1 and _2 and _3
  UI/FleetWnd.cpp
  UI/ObjectListWnd.cpp
Labels: category:bug, component:internal, status:cherry-pick for release

#3109 Make imperial stockpile stringtable entries slightly better
  default/scripting/encyclopedia/game_concepts/STOCKPILE.focs.txt
  default/scripting/encyclopedia/game_concepts/STOCKPILE_TRANSFER.focs.txt
  default/stringtables/en.txt
Labels: category:tweak, component:user manual

#3124 Fix some stringtable typos
  default/stringtables/en.txt
Labels: category:bug, component:art music text assets
