Repository freeorion/freeorion, pull requests merged in 2020-06, with the labels that each got.

#2998 Fix wrong variable name
  default/python/AI/PriorityAI.py
Labels: category:bug, component:AI

#2999 Typo in Ship.h
  universe/Ship.h
Labels: category:tweak, component:internal

#3011 Adjust documentation to correctly describe Academy placement limit
  default/stringtables/en.txt
Labels: category:bug, component:user manual

#2962 Set rule defaults to 4 bouts and rescale structure and damage
  combat/CombatEvents.cpp
  default/stringtables/en.txt
  universe/ShipHull.cpp
Labels: category:feature, component:content scripting, component:game mechanic

#2960 Fulver precog exploration
  default/scripting/species/SP_FULVER.focs.txt
  default/scripting/species/common/telepathic.macros
  default/stringtables/en.txt
Labels: category:feature, component:content scripting

#2921 Make Chato BAD_POPULATION
  default/scripting/species/SP_CHATO.focs.txt
Labels: category:tweak, component:content scripting

#2910 Add local variables to python exception logging
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/common/configure_logging.py
Labels: category:tweak, component:internal

#3007 Set minimum window sizes on design screen
  UI/DesignWnd.cpp
  UI/EncyclopediaDetailPanel.cpp
Labels: category:bug, component:UI

#3010 Random Refactoring
  Empire/Empire.cpp
  UI/ClientUI.cpp
  UI/ClientUI.h
  UI/SidePanel.cpp
  UI/SitRepPanel.cpp
  client/AI/AIClientApp.cpp
  combat/CombatSystem.cpp
  server/ServerFSM.cpp
  universe/Conditions.cpp
  universe/Effects.cpp
  universe/IDAllocator.cpp
  universe/Ship.cpp
  universe/Species.cpp
  universe/ValueRefs.cpp
  universe/ValueRefs.h
  util/MultiplayerCommon.cpp
  util/Random.cpp
  util/Random.h
Labels: category:refactoring, component:internal

#2991 Hide some sensible info from enemy empires
  default/stringtables/en.txt
  default/stringtables/es.txt
  default/stringtables/fr.txt
  util/MultiplayerCommon.cpp
  util/SerializeEmpire.cpp
Labels: category:bug, component:network

#2982 Separate UniverseObjectVisitor into separate TU files
  Empire/Supply.cpp
  UI/EncyclopediaDetailPanel.cpp
  UI/FleetWnd.cpp
  UI/MapWnd.cpp
  UI/SidePanel.cpp
  UI/SystemIcon.cpp
  combat/CombatSystem.cpp
  msvc2017/Common/Common.vcxproj
  msvc2017/Common/Common.vcxproj.filters
  msvc2017/FreeOrion/FreeOrion.vcxproj
  msvc2017/FreeOrion/FreeOrion.vcxproj.filters
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj.filters
  msvc2017/FreeOrionD/FreeOrionD.vcxproj
  msvc2017/FreeOrionD/FreeOrionD.vcxproj.filters
  python/EmpireWrapper.cpp
  python/UniverseWrapper.cpp
  server/ServerApp.cpp
  universe/Building.cpp
  universe/CMakeLists.txt
  universe/Field.cpp
  universe/Fighter.cpp
  universe/Fleet.cpp
  universe/Pathfinder.cpp
  universe/Planet.cpp
  universe/Predicates.cpp
  universe/Predicates.h
  universe/Ship.cpp
  universe/System.cpp
  universe/Universe.cpp
  universe/UniverseObject.cpp
  universe/UniverseObjectVisitor.cpp
  universe/UniverseObjectVisitor.h
  universe/UniverseObjectVisitors.cpp
  universe/UniverseObjectVisitors.h
  universe/ValueRefs.cpp
  util/Order.cpp
  util/SitRepEntry.cpp
Labels: category:refactoring, component:internal

#3013 further adjust minimum window sizes
  UI/DesignWnd.cpp
Labels: category:tweak, component:UI

#3004 UI tweak - display planet wheel only for real planets
  UI/EncyclopediaDetailPanel.cpp
Labels: category:tweak, component:UI

#2940 Delay SINGULARITY_GEN, reduce ART_BLACK_HOLE build time
  default/python/AI/ResearchAI.py
  default/scripting/buildings/ART_BLACK_HOLE.focs.txt
  default/scripting/techs/production/SINGULAR_GEN.focs.txt
Labels: category:tweak, component:content scripting

#3021 Remove unused SpeciesID concept
  parse/IntValueRefParser.cpp
  parse/Tokens.h
  universe/Species.cpp
  universe/Species.h
  universe/ValueRefs.cpp
Labels: category:tweak, component:internal

#3020 Refactor directory functions
  UI/CUIWnd.cpp
  UI/ChatWnd.cpp
  UI/ClientUI.cpp
  UI/GalaxySetupWnd.cpp
  UI/GovernmentWnd.cpp
  UI/InGameMenu.cpp
  UI/MapWnd.cpp
  UI/SaveFileDialog.cpp
  UI/ServerConnectWnd.cpp
  UI/SidePanel.cpp
  UI/TechTreeWnd.cpp
  msvc2017/FreeOrion/FreeOrion.vcxproj
  msvc2017/FreeOrion/FreeOrion.vcxproj.filters
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj.filters
  msvc2017/FreeOrionD/FreeOrionD.vcxproj
  msvc2017/FreeOrionD/FreeOrionD.vcxproj.filters
  parse/FleetPlansParser.cpp
  parse/GameRulesParser.cpp
  parse/ItemsParser.cpp
  parse/MonsterFleetPlansParser.cpp
  universe/Effects.cpp
  universe/Enums.cpp
  universe/Enums.h
  universe/EnumsFwd.h
  universe/Planet.cpp
  universe/PopCenter.cpp
  universe/ResourceCenter.cpp
  util/Directories.cpp
  util/Directories.h
  util/ModeratorAction.cpp
  util/SaveGamePreviewUtils.h
Labels: category:refactoring, component:internal

#3024 Remove Asteroid processor(s) after artificial planet creation
  default/scripting/buildings/shipyards/ASTEROID.focs.txt
  default/scripting/buildings/shipyards/ASTEROID_REF.focs.txt
Labels: category:bug, component:content scripting, status:cherry-pick for release

#2979 Remove unused serialization code from ValueRef, Condition and Effect …
  universe/Condition.h
  universe/ConditionAll.h
  universe/ConditionSource.h
  universe/Conditions.h
  universe/Effect.h
  universe/Effects.h
  universe/ValueRef.h
  universe/ValueRefs.h
Labels: category:refactoring, component:internal

#3019 Artificial Black Hole - prevent multiple sitreps
  default/scripting/buildings/ART_BLACK_HOLE.focs.txt
Labels: category:bug, component:content scripting

#3018 Nerf flat bonuses
  default/python/AI/AIDependencies.py
  default/scripting/techs/learning/ARTIF_MINDS.focs.txt
  default/scripting/techs/production/SENTIENT_AUTOMATION.focs.txt
  default/stringtables/de.txt
  default/stringtables/en.txt
  default/stringtables/fr.txt
  default/stringtables/ru.txt
Labels: category:tweak, component:content scripting

#3026 Simplify special-based population bonuses in AIDependencies.py
  default/python/AI/AIDependencies.py
  default/python/AI/ColonisationAI.py
Labels: category:refactoring, component:AI

#3030 Effect Condition Fixes
  default/scripting/species/common/advanced_focus.macros
  universe/Conditions.cpp
  universe/Conditions.h
  universe/Effects.cpp
Labels: category:bug, component:content scripting, component:internal

#3027 Use list initialization for structs declared in MultiplayerCommon.h
  server/SaveLoad.cpp
  server/ServerApp.cpp
  server/ServerFSM.cpp
  util/MultiplayerCommon.h
Labels: category:refactoring, component:internal

#3033 Remove redundant prerequisite from Zero Point Generation
  default/scripting/techs/production/ZERO_GEN.focs.txt
Labels: category:bug, component:content scripting

#3005 Sitrep for supernova
  default/scripting/ship_parts/General/SP_NOVA_BOMB.focs.txt
  default/stringtables/en.txt
Labels: category:feature, component:content scripting

#3025 Add ROBOTIC_HULL tag to Space Flux Bubble hull
  default/scripting/ship_hulls/robotic/SH_SPACE_FLUX_BUBBLE.focs.txt
Labels: category:bug, component:content scripting

#3049 Ensure python log messages end with \n
  default/python/common/configure_logging.py
Labels: category:bug, component:internal

#3050 Fix Python logging memory leak
  python/LoggingWrapper.cpp
Labels: category:bug, component:internal, status:cherry-pick for release

#3052 Fix typo in auth.py debug message
  default/python/auth/auth.py
Labels: category:bug, component:network, status:merged

#3047 Gave some techs some effects to add policy slots
  default/scripting/techs/learning/DISTRIB_THOUGHT.focs.txt
  default/scripting/techs/learning/TEMPORAL_MECH.focs.txt
  default/scripting/techs/production/SENTIENT_AUTOMATION.focs.txt
  default/stringtables/en.txt
Labels: category:tweak, component:content scripting

#3054 Fields affect target meter, add standard meter change for ships
  default/scripting/fields/FLD_METEOR_BLIZZARD.focs.txt
  default/scripting/fields/FLD_NANITE_SWARM.focs.txt
  default/scripting/species/common/general.macros
Labels: category:feature, component:internal

#2986 fix of issue 2985
  util/Order.cpp
Labels: category:bug, component:game mechanic

#3032 Fix encyclopedia graph axis label precision.
  UI/GraphControl.cpp
Labels: category:bug, component:UI

#3029 Additional entries for Encyclopedia planetary focus game concept page
  default/scripting/encyclopedia/game_concepts/planetary_focus/DISTORTION_FOCUS.focs.txt
  default/scripting/encyclopedia/game_concepts/planetary_focus/INDUSTRY_FOCUS.focs.txt
  default/scripting/encyclopedia/game_concepts/planetary_focus/LOGISTICS_FOCUS.focs.txt
  default/scripting/encyclopedia/game_concepts/planetary_focus/PLANETDRIVE_FOCUS.focs.txt
  default/scripting/encyclopedia/game_concepts/planetary_focus/PSYCHIC_FOCUS.focs.txt
  default/stringtables/en.txt
Labels: category:feature, component:art music text assets

#3051 Use non-intrusive serialization for util/MultiplayerCommon.h structs
  util/MultiplayerCommon.h
  util/Serialize.h
  util/SerializeMultiplayerCommon.cpp
Labels: category:refactoring, component:internal

#3046 ValueRef Optimization
  universe/ValueRef.h
  universe/ValueRefs.cpp
  universe/ValueRefs.h
Labels: category:refactoring, component:internal

#3061 Public struct attribute names
  UI/EncyclopediaDetailPanel.cpp
  UI/GalaxySetupWnd.cpp
  UI/MultiplayerLobbyWnd.cpp
  client/AI/AIClientApp.cpp
  client/human/HumanClientApp.cpp
  client/human/HumanClientFSM.cpp
  network/Message.cpp
  server/SaveLoad.cpp
  server/ServerApp.cpp
  server/ServerFSM.cpp
  server/ServerFramework.cpp
  server/ServerWrapper.cpp
  server/UniverseGenerator.cpp
  test/system/ClientAppFixture.cpp
  test/system/SmokeTestHostless.cpp
  util/MultiplayerCommon.cpp
  util/MultiplayerCommon.h
  util/SaveGamePreviewUtils.cpp
  util/SerializeMultiplayerCommon.cpp
Labels: category:refactoring, component:internal

#3058 Remove CombatLogManager pointer-to-implementation pattern.
  combat/CombatLogManager.cpp
  combat/CombatLogManager.h
  universe/Fleet.h
Labels: category:refactoring, component:internal

#3044 Add missing structure scales for growth of Symbiotic and Tree hulls
  default/scripting/buildings/shipyards/ORBITAL_DRYDOCK.focs.txt
  default/scripting/fields/FLD_NANITE_SWARM.focs.txt
  default/scripting/ship_hulls/monster/SH_TREE_BODY.focs.txt
  default/scripting/ship_hulls/organic/SH_BIOADAPTIVE.focs.txt
  default/scripting/ship_hulls/organic/SH_ENDOMORPHIC.focs.txt
  default/scripting/ship_hulls/organic/SH_ENDOSYMBIOTIC.focs.txt
  default/scripting/ship_hulls/organic/SH_ORGANIC.focs.txt
  default/scripting/ship_hulls/organic/SH_PROTOPLASMIC.focs.txt
  default/scripting/ship_hulls/organic/SH_RAVENOUS.focs.txt
  default/scripting/ship_hulls/organic/SH_SENTIENT.focs.txt
  default/scripting/ship_hulls/organic/SH_SYMBIOTIC.focs.txt
  default/scripting/ship_hulls/robotic/SH_LOGITICS_FACILITATOR.focs.txt
  default/scripting/ship_hulls/ship_hulls.macros
Labels: category:bug, component:content scripting

#3028 Planetary Starlane Drive - Beacon placement limit & Encyclopedia Text
  default/scripting/buildings/PLANET_BEACON.focs.txt
  default/stringtables/en.txt
Labels: category:feature, component:art music text assets, component:content scripting

#3064 Don't shutdown dedicated server
  server/ServerFSM.cpp
Labels: category:bug, component:network, status:cherry-pick for release

#3063 Allow galaxy setup panel of multiplayer lobby to scale with window size
  UI/MultiplayerLobbyWnd.cpp
Labels: category:bug, component:UI

#3065 Use non-intrusive serialization for combat related classes
  combat/CombatEvent.cpp
  combat/CombatEvent.h
  combat/CombatEvents.cpp
  combat/CombatEvents.h
  combat/CombatLogManager.cpp
  combat/CombatLogManager.h
  msvc2017/Common/Common.vcxproj
  msvc2017/Common/Common.vcxproj.filters
  network/Message.cpp
  util/CMakeLists.txt
  util/Serialize.h
  util/SerializeCombat.cpp
Labels: category:refactoring, component:internal

#3067 Serialization cleanup
  UI/IntroScreen.cpp
  UI/MultiplayerLobbyWnd.cpp
  client/AI/AIClientApp.cpp
  client/ClientApp.cpp
  client/human/HumanClientApp.cpp
  msvc2017/FreeOrion/FreeOrion.vcxproj
  msvc2017/FreeOrion/FreeOrion.vcxproj.filters
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj.filters
  msvc2017/FreeOrionD/FreeOrionD.vcxproj
  msvc2017/FreeOrionD/FreeOrionD.vcxproj.filters
Labels: category:refactoring, component:internal

#3069 Fix message color in chat history
  server/ServerFSM.cpp
Labels: category:bug, component:UI, component:network

#3070 Add CMake GiGi::header import target to simplify headless build
  CMakeLists.txt
  GG/CMakeLists.txt
  GG/test/unit/CMakeLists.txt
  test/UI/CMakeLists.txt
Labels: category:refactoring, component:build system

#3071 Fix Travis CI ccache setup
  .travis.yml
Labels: category:bug, component:infrastructure

#3072 TravisCI drop Docker usage
  .travis.yml
Labels: category:refactoring, component:infrastructure

#3068 Treat empire without population and ships as eliminated
  server/ServerApp.cpp
  universe/PopCenter.cpp
  universe/PopCenter.h
Labels: category:feature, component:game mechanic

#3076 Fix typo paramaters -> parameters
  parse/CommonParamsParser.cpp
Labels: category:tweak, component:internal, status:merged

#3077 Refactor credits rendering
  UI/IntroScreen.cpp
Labels: category:refactoring, component:UI

#3075 Move parser helper structs
  parse/CommonParamsParser.h
  parse/ShipHullsParser.cpp
  parse/ShipPartsParser.cpp
  parse/SpeciesParser.cpp
  universe/CommonParams.h
  universe/ShipHull.cpp
  universe/ShipHull.h
  universe/ShipPart.cpp
  universe/ShipPart.h
  universe/Species.cpp
  universe/Species.h
Labels: category:refactoring, component:internal

#3073 Delay Experimentor outpost 50 turns, spawn monsters on pairs
  default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.txt
Labels: category:tweak, component:content scripting, status:cherry-pick for release

#3074 Don't hard code button widths in GG::TabBar
  GG/GG/TabWnd.h
  GG/src/TabWnd.cpp
Labels: category:refactoring, component:UI

#3083 Nonintrusive serialization - hide Archive implementiation
  Empire/EmpireManager.h
  universe/Species.h
  util/SaveGamePreviewUtils.cpp
  util/SaveGamePreviewUtils.h
  util/Serialize.h
  util/SerializeEmpire.cpp
  util/SerializeMultiplayerCommon.cpp
  util/SerializeUniverse.cpp
Labels: category:refactoring, component:internal

#3087 Production Queue Safety
  UI/ProductionWnd.cpp
  UI/QueueListBox.cpp
  UI/QueueListBox.h
  UI/ResearchWnd.cpp
Labels: category:bug, component:UI, status:cherry-pick for release

#3085 Move outpost troop effect into tech/construction/OUTPOST.focs.txt
  default/scripting/species/common/troops.macros
  default/scripting/techs/construction/OUTPOST.focs.txt
Labels: category:bug, category:refactoring, component:content scripting, status:cherry-pick for release
