Repository freeorion/freeorion, pull requests merged in 2020-11, with the labels that each got.

#3215 Inform about missing optional "value" reference (instead of error)
  util/StringTable.cpp
Labels: category:bug, component:internal

#3170 Make Bad..Ultimate Def. Troops start at minimum 6 troops
  default/scripting/common/named_values.focs.txt
  default/scripting/policies/CONFEDERATION.focs.txt
  default/scripting/species/common/troops.macros
  default/scripting/techs/construction/OUTPOST.focs.txt
  default/scripting/techs/defense/Defense.focs.txt
  default/scripting/techs/defense/Garrison.focs.txt
  default/scripting/techs/growth/CYBORG.focs.txt
  default/stringtables/en.txt
Labels: category:tweak, component:content scripting

#3195 Named Valuerefs for Research modifiers
  default/scripting/buildings/AUTO_HISTORY_ANALYSER.focs.txt
  default/scripting/buildings/COLLECTIVE_NET.focs.txt
  default/scripting/buildings/CULTURE_ARCHIVES.focs.txt
  default/scripting/buildings/CULTURE_LIBRARY.focs.txt
  default/scripting/buildings/ENCLAVE_VOID.focs.txt
  default/scripting/common/named_values.focs.txt
  default/scripting/specials/planet/ANCIENT_RUINS.focs.txt
  default/scripting/specials/planet/ANCIENT_RUINS_DEPLETED.focs.txt
  default/scripting/specials/planet/COMPUTRONIUM.focs.txt
  default/scripting/specials/planet/ECCENTRIC_ORBIT.focs.txt
  default/scripting/specials/planet/PHILOSOPHER.focs.txt
  default/scripting/specials/planet/TEMPORAL_ANOMOLY.focs.txt
  default/scripting/techs/growth/ENERGY_META.focs.txt
  default/scripting/techs/learning/ALGO_ELEGANCE.focs.txt
  default/scripting/techs/learning/ARTIF_MINDS.focs.txt
  default/scripting/techs/learning/DISTRIB_THOUGHT.focs.txt
  default/scripting/techs/learning/NASCENT_AI.focs.txt
  default/scripting/techs/learning/QUANT_NET.focs.txt
  default/scripting/techs/learning/STELLAR_TOMOGRAPHY.focs.txt
  default/stringtables/en.txt
Labels: category:refactoring, component:content scripting

#3214 Fix MacOS CI
  .travis.yml
Labels: category:bug, component:infrastructure

#3219 Lower monster&special freq., fine-tuned native freq.
  default/python/universe_generation/universe_tables.py
Labels: category:tweak, component:content scripting

#3216 Named Values for most Industry modifiers
  default/scripting/buildings/BLACK_HOLE_POW_GEN.focs.txt
  default/scripting/buildings/CONC_CAMP.focs.txt
  default/scripting/buildings/GAS_GIANT_GEN.focs.txt
  default/scripting/buildings/HYPER_DAM.focs.txt
  default/scripting/buildings/INDUSTRY_CENTER.focs.txt
  default/scripting/buildings/SOL_ORB_GEN.focs.txt
  default/scripting/fields/FLD_NANITE_SWARM.focs.txt
  default/scripting/policies/CENTRALIZATION.focs.txt
  default/scripting/policies/ENVIRONMENTALISM.focs.txt
  default/scripting/policies/EXOBOT_PRODUCTIVITY.focs.txt
  default/scripting/policies/INDUSTRIALISM.focs.txt
  default/scripting/policies/RACIAL_PURITY.focs.txt
  default/scripting/specials/planet/HONEYCOMB.focs.txt
  default/scripting/specials/planet/TIDAL_LOCK.focs.txt
  default/scripting/specials/planet/growth/growth.macros
  default/scripting/species/SP_KILANDOW.focs.txt
  default/scripting/species/common/general.macros
  default/scripting/species/common/industry.macros
  default/scripting/species/common/troops.macros
  default/scripting/species/common/xenophobic.macros
  default/scripting/techs/production/ADAPTIVE_AUTOMATION.focs.txt
  default/scripting/techs/production/FUSION_GEN.focs.txt
  default/scripting/techs/production/MICRO_MANUF.focs.txt
  default/scripting/techs/production/ROBOTIC_PROD.focs.txt
  default/scripting/techs/production/SENTIENT_AUTOMATION.focs.txt
  default/stringtables/en.txt
Labels: category:refactoring, component:content scripting

#3184 Haiku support proposal.
  CMakeLists.txt
  client/human/chmain.cpp
  util/Directories.cpp
Labels: category:feature, component:internal

#3222 Make Organic Hull a useful very small hull
  default/python/AI/AIDependencies.py
  default/scripting/ship_designs/SD_ORG_OUTPOST_SHIP.focs.txt
  default/scripting/ship_hulls/organic/SH_ORGANIC.focs.txt
  default/stringtables/en.txt
Labels: category:refactoring, component:content scripting

#3230 Fix display of named value refs without string table entry
  util/StringTable.cpp
Labels: category:bug, component:UI

#3231 Fix turn advance when last player conceded
  server/ServerFSM.cpp
Labels: category:bug, component:internal, component:network

#3232 Nerf Trith: medium planet, bad supply&industry
  default/scripting/species/SP_TRITH.focs.txt
Labels: category:tweak, component:content scripting

#3213 Introduce server-side auto-turn
  Empire/Empire.cpp
  Empire/Empire.h
  network/Message.cpp
  network/Message.h
  server/ServerApp.cpp
  server/ServerFSM.cpp
  server/ServerFSM.h
  util/SerializeEmpire.cpp
Labels: category:feature, component:network

#3234 Self-sustaining metabolism nerf - population boost only on good planets
  default/scripting/species/common/population.macros
  default/stringtables/en.txt
Labels: category:tweak, component:content scripting

#3239 Fix slow MacOS homebrew update
  .travis.yml
Labels: category:tweak, component:infrastructure

#3221 Mitigate race conditions, towards supporting invariant named value refs
  default/scripting/common/misc.macros
  default/scripting/common/named_values.focs.txt
  default/scripting/policies/CONFEDERATION.focs.txt
  default/scripting/species/common/influence.macros
  default/stringtables/en.txt
  default/stringtables/fr.txt
  parse/ArithmeticRules.cpp
  parse/DoubleValueRefParser.cpp
  parse/IntValueRefParser.cpp
  parse/NamedValueRefParser.cpp
  universe/FieldType.cpp
  universe/NamedValueRefManager.cpp
  universe/NamedValueRefManager.h
  universe/Universe.cpp
  universe/ValueRefs.h
  util/AppInterface.cpp
  util/Pending.h
Labels: category:bug, component:content scripting, component:internal

#3241 Fix empire readiness when unset auto turn
  Empire/Empire.cpp
  Empire/Empire.h
  server/ServerFSM.cpp
Labels: category:bug, component:network, priority:high

#3237 Some Godot fixes
  .travis.yml
  CMakeLists.txt
  godot/client/gdcpptest.gdnlib
  godot/gdfreeorion.cpp
Labels: category:bug, component:UI
