Repository freeorion/freeorion, pull requests merged in 2020-01, with the labels that each got.

#2685 Fix spelling/grammar in pedia.
  default/stringtables/en.txt
Labels: category:bug, component:user manual, status:cherry-pick for release

#2687 Make Chato bad pilots
  default/scripting/species/SP_CHATO.focs.txt
Labels: category:tweak, component:content scripting, status:cherry-pick for release, status:merged

#2678 Reset Rules to Defaults in Client when Returning to Intro Screen
  client/human/HumanClientFSM.cpp
Labels: category:bug, category:tweak, component:UI, component:internal

#2692 Fix spelling of 'military'.
  default/python/AI/ColonisationAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/MilitaryAI.py
Labels: category:tweak, component:AI

#2689 Supply Obstruction Update Before Fleet Movement
  server/ServerApp.cpp
Labels: category:bug, component:internal, priority:high, status:cherry-pick for release

#2696 Use std type traits
  GG/GG/Flags.h
  GG/GG/StrongTypedef.h
  universe/ObjectMap.h
Labels: category:refactoring, component:internal

#2695 Simplify StatisticIcon
  UI/CUIControls.cpp
  UI/CUIControls.h
Labels: category:refactoring, component:UI

#2654 Added combat forces accordion panels
  UI/CombatReport/CombatLogWnd.cpp
Labels: category:feature, component:UI

#2700 Fix finalization segfaults for upcoming python3
  python/CommonFramework.cpp
  python/CommonFramework.h
  server/ServerApp.cpp
Labels: category:bug, component:internal, priority:high

#2701 Replace some boost::spirit::classic implementations with spirit::qi or xpressive
  UI/ChatWnd.cpp
  UI/ClientUI.cpp
  UI/OptionsWnd.cpp
Labels: category:refactoring, component:internal

#2703 Fix spelling of 'specified'.
  universe/Ship.h
  universe/UniverseObject.h
Labels: category:tweak, component:internal

#2707 Remove duplicate template code for arithmetic expression parser
  parse/ValueRefParser.cpp
Labels: category:tweak, component:internal

#2706 Changelog update
  ChangeLog.md
Labels: category:tweak, component:technical docs

#2704 Fix G++ warnings
  Empire/Empire.cpp
  GG/src/Font.cpp
  GG/src/nanovg/stb_image.h
  python/server/ServerWrapper.cpp
  util/Serialize.ipp
  util/i18n.cpp
Labels: category:tweak, component:internal

#2699 Fix python3 incompatiable code
  default/python/AI/ColonisationAI.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/MoveUtilsAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/AI/savegame_codec/_decoder.py
  default/python/AI/savegame_codec/_encoder.py
  default/python/AI/turn_state.py
  default/python/auth/auth.py
  default/python/common/charting/charts.py
  default/python/common/option_tools.py
  default/python/tests/AI/test_read_only_dict.py
  default/python/turn_events/turn_events.py
  default/python/universe_generation/empires.py
  default/python/universe_generation/fields.py
  default/python/universe_generation/galaxy.py
  default/python/universe_generation/monsters.py
  default/python/universe_generation/names.py
  default/python/universe_generation/natives.py
  default/python/universe_generation/specials.py
  default/python/universe_generation/starnames.py
  default/python/universe_generation/starsystems.py
  default/python/universe_generation/universe_generator.py
  default/python/universe_generation/universe_statistics.py
  default/python/universe_generation/util.py
Labels: category:refactoring, component:AI, priority:high, status:merged

#2705 Make UniverseObject's dump Python API don't accept arguments
  python/UniverseWrapper.cpp
Labels: category:refactoring, component:internal

#2694 Use boost signals to handle context menu in StatisticIcon
  UI/CUIControls.cpp
  UI/CUIControls.h
  UI/FleetWnd.cpp
  UI/MilitaryPanel.cpp
  UI/MilitaryPanel.h
  UI/MultiIconValueIndicator.cpp
  UI/MultiIconValueIndicator.h
  UI/PopulationPanel.cpp
  UI/PopulationPanel.h
  UI/ResourcePanel.cpp
  UI/ResourcePanel.h
  UI/SpecialsPanel.cpp
  UI/SpecialsPanel.h
Labels: category:refactoring, component:UI

#2708 Fix species variable name 'SP_LEMBALALAM'.
  default/python/AI/AIDependencies.py
Labels: category:tweak, component:content scripting

#2713 Remove cmp method usages (removed in python3)
  default/python/AI/ColonisationAI.py
  default/python/AI/PriorityAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ResourcesAI.py
Labels: category:refactoring, component:AI, priority:high

#2712 Fix FleetMoveOrder::Check when appending a route
  util/Order.cpp
Labels: category:bug, component:internal

#2711 Make tests python3 compatiable
  .travis.yml
  default/python/AI/freeorion_tools/__init__.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/AI/freeorion_tools/extend_freeorion_AI_interface.py
  default/python/AI/freeorion_tools/interactive_shell.py
  default/python/AI/savegame_codec/__init__.py
  default/python/AI/savegame_codec/_decoder.py
  default/python/AI/savegame_codec/_encoder.py
  default/python/common/option_tools.py
  default/python/common/print_utils.py
  default/python/common/profiling.py
  default/python/common/six.py
  default/python/tests/AI/test_read_only_dict.py
  default/python/tests/AI/test_savegame_manager.py
  default/python/tox.ini
Labels: category:refactoring, component:AI

#2716 Let AI scrap Gateway to the void
  default/python/AI/ProductionAI.py
Labels: category:bug, component:AI

#2709 Add pylint python3 check runner
  default/python/README.md
  default/python/py3_migration_pylint_config.ini
  default/python/py3_migration_pylint_runner.py
Labels: category:refactoring, component:AI, component:infrastructure

#2629 Add ShipDesignsInProduction ValueRef and use it for upkeep
  Empire/Empire.cpp
  Empire/Empire.h
  default/scripting/common/upkeep.macros
  parse/IntComplexValueRefParser.cpp
  parse/Tokens.h
  universe/ValueRef.cpp
  util/SerializeEmpire.cpp
Labels: category:feature, component:content scripting, component:game mechanic

#2717 Fix python 3 incompatibilities found by pylint
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/ColonisationAI.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/EnumsAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/PriorityAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/fleet_orders.py
  default/python/AI/freeorion_tools/timers.py
  default/python/README.md
  default/python/common/option_tools.py
  default/python/common/print_utils.py
  default/python/common/profiling.py
  default/python/common/timers.py
  default/python/py3_migration_pylint_runner.py
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/interface_inspector.py
  default/python/stub_generator/parse_docs.py
  default/python/tests/AI/test_read_only_dict.py
  default/python/universe_generation/empires.py
  default/python/universe_generation/galaxy.py
  default/python/universe_generation/specials.py
  default/python/universe_generation/starnames.py
  default/python/universe_generation/starsystems.py
  default/python/universe_generation/util.py
Labels: category:refactoring, component:AI, priority:high

#2721 Fix compile error in GCC 5.4.0
  UI/CUIControls.cpp
Labels: category:bug, component:internal

#2723 corrected Colony Base hull description re slots
  default/stringtables/en.txt
Labels: category:bug, category:tweak, component:art music text assets, status:cherry-pick for release

#2724 Fix use of lane-wormhole flag as system id
  Empire/Empire.cpp
Labels: category:bug, component:game mechanic, component:internal, priority:high, status:cherry-pick for release

#2591 Add macros for easier adjustment of native detection, defense, shield…
  default/scripting/species/SP_KOBUNTURA.focs.txt
  default/scripting/species/SP_MUURSH.focs.txt
  default/scripting/species/common/detection.macros
  default/scripting/species/common/native_fortification.macros
  default/scripting/species/common/planet_defense.macros
  default/scripting/species/common/planet_shields.macros
  default/scripting/species/common/troops.macros
  default/stringtables/en.txt
Labels: category:tweak, component:content scripting

#2726 Make starter ship designs required.
  default/scripting/ship_designs/required/SD_MARK_1.focs.txt
  default/scripting/ship_designs/required/SD_SCOUT.focs.txt
Labels: category:tweak, component:content scripting

#2727 Changelog update
  ChangeLog.md
Labels: category:tweak, component:technical docs

#2730 Use uniform begin/end naming for constant iterators
  Empire/Empire.cpp
  GG/GG/ZList.h
  UI/OptionsWnd.cpp
  combat/CombatLogManager.cpp
  combat/CombatSystem.cpp
  universe/ObjectMap.cpp
  universe/ObjectMap.h
  universe/Universe.cpp
Labels: category:refactoring, component:internal, status:merged

#2722 Simplify ObjectMap interface
  AI/AIInterface.cpp
  Empire/Empire.cpp
  Empire/ResourcePool.cpp
  Empire/Supply.cpp
  UI/BuildDesignatorWnd.cpp
  UI/ChatWnd.cpp
  UI/ClientUI.cpp
  UI/CombatReport/CombatLogWnd.cpp
  UI/CombatReport/GraphicalSummary.cpp
  UI/EncyclopediaDetailPanel.cpp
  UI/FleetWnd.cpp
  UI/LinkText.cpp
  UI/MapWnd.cpp
  UI/ObjectListWnd.cpp
  UI/PlayerListWnd.cpp
  UI/SidePanel.cpp
  UI/SystemIcon.cpp
  UI/SystemResourceSummaryBrowseWnd.cpp
  client/ClientApp.cpp
  combat/CombatSystem.cpp
  python/UniverseWrapper.cpp
  python/server/ServerWrapper.cpp
  server/ServerApp.cpp
  universe/Condition.cpp
  universe/Effect.cpp
  universe/Fleet.cpp
  universe/ObjectMap.cpp
  universe/ObjectMap.h
  universe/Pathfinder.cpp
  universe/Planet.cpp
  universe/System.cpp
  universe/Universe.cpp
  universe/Universe.h
  universe/UniverseGenerator.cpp
  util/AppInterface.h
  util/ModeratorAction.cpp
  util/Order.cpp
  util/SerializeUniverse.cpp
Labels: category:refactoring, component:internal

#2732 Research deuterium tank in TechList3 (List1 for sparse galaxy) and antimatter tank in TechList4
  default/python/AI/TechsListsAI.py
Labels: category:tweak, component:AI, priority:high, status:cherry-pick for release
