Repository freeorion/freeorion, pull requests merged in 2020-03, with the labels that each got.

#2785 Add NoDefaultFuelEffect to hulls where it is missing
  default/scripting/ship_hulls/SH_BASIC_LARGE.focs.txt
  default/scripting/ship_hulls/SH_BASIC_MEDIUM.focs.txt
  default/scripting/ship_hulls/SH_BASIC_SMALL.focs.txt
  default/scripting/ship_hulls/SH_COLONY_BASE.focs.txt
  default/scripting/ship_hulls/SH_XENTRONIUM.focs.txt
  default/scripting/ship_hulls/asteroid/SH_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_CAMOUFLAGE_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_CRYSTALLIZED_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_HEAVY_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_MINIASTEROID_SWARM.focs.txt
  default/scripting/ship_hulls/asteroid/SH_SCATTERED_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_SMALL_ASTEROID.focs.txt
  default/scripting/ship_hulls/asteroid/SH_SMALL_CAMOUFLAGE_ASTEROID.focs.txt
  default/scripting/ship_hulls/energy/SH_COMPRESSED_ENERGY.focs.txt
  default/scripting/ship_hulls/energy/SH_ENERGY_FRIGATE.focs.txt
  default/scripting/ship_hulls/energy/SH_FRACTAL_ENERGY.focs.txt
  default/scripting/ship_hulls/energy/SH_QUANTUM_ENERGY.focs.txt
  default/scripting/ship_hulls/energy/SH_SOLAR.focs.txt
  default/scripting/ship_hulls/monster/SH_BLACK_KRAKEN_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_BLOATED_JUGGERNAUT_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_COSMIC_DRAGON_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_DAMPENING_CLOUD_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_DRONE_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_EXP_OUTPOST_HULL.focs.txt
  default/scripting/ship_hulls/monster/SH_FLOATER.focs.txt
  default/scripting/ship_hulls/monster/SH_GUARD_0_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_GUARD_1_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_GUARD_3_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_GUARD_MONSTER_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_IMMOBILE_FACTOR.focs.txt
  default/scripting/ship_hulls/monster/SH_JUGGERNAUT_1_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_JUGGERNAUT_2_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_JUGGERNAUT_3_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRAKEN_1_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRAKEN_2_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRAKEN_3_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRILL_1_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRILL_2_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRILL_3_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_KRILL_4_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_NEBULOUS.focs.txt
  default/scripting/ship_hulls/monster/SH_PSIONIC_SNOWFLAKE_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_SNOWFLAKE_1_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_SNOWFLAKE_2_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_SNOWFLAKE_3_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_STRONG_MONSTER_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_TREE_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_WHITE_KRAKEN_BODY.focs.txt
  default/scripting/ship_hulls/organic/SH_BIOADAPTIVE.focs.txt
  default/scripting/ship_hulls/organic/SH_ENDOMORPHIC.focs.txt
  default/scripting/ship_hulls/organic/SH_ENDOSYMBIOTIC.focs.txt
  default/scripting/ship_hulls/organic/SH_ORGANIC.focs.txt
  default/scripting/ship_hulls/organic/SH_PROTOPLASMIC.focs.txt
  default/scripting/ship_hulls/organic/SH_RAVENOUS.focs.txt
  default/scripting/ship_hulls/organic/SH_SENTIENT.focs.txt
  default/scripting/ship_hulls/organic/SH_STATIC_MULTICELLULAR.focs.txt
  default/scripting/ship_hulls/organic/SH_SYMBIOTIC.focs.txt
Labels: category:bug, category:feature, category:tweak, component:content scripting, status:merged

#2784 Use std::thread::hardware_concurrency to set default # of effects threads
  universe/Universe.cpp
Labels: category:tweak, component:internal

#2781 Fix MSVC project for SDK 11 and Use SDK 11 with CMake for Apple
  .appveyor.yml
  CMakeLists.txt
  cmake/make_versioncpp.py
  msvc2015/Common/Common.vcxproj
  msvc2015/Common/Common.vcxproj.filters
  msvc2015/FreeOrion.sln
  msvc2015/FreeOrion/FreeOrion.vcxproj
  msvc2015/FreeOrion/FreeOrion.vcxproj.filters
  msvc2015/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2015/FreeOrionCA/FreeOrionCA.vcxproj.filters
  msvc2015/FreeOrionD/FreeOrionD.vcxproj
  msvc2015/FreeOrionD/FreeOrionD.vcxproj.filters
  msvc2015/GiGi/GiGi.vcxproj
  msvc2015/GiGi/GiGi.vcxproj.filters
  msvc2015/GiGiSDL/GiGiSDL.vcxproj
  msvc2015/GiGiSDL/GiGiSDL.vcxproj.filters
  msvc2015/Parsers/Parsers.vcxproj
  msvc2015/Parsers/Parsers.vcxproj.filters
  msvc2015/boost.dependency.props
  msvc2015/cpp.lang.props
  msvc2015/freetype.dependency.props
  msvc2015/glew.dependency.props
  msvc2015/libpng.dependency.props
  msvc2015/openal.dependency.props
  msvc2015/opengl.dependency.props
  msvc2015/sdl.dependency.props
  msvc2015/vorbis.dependency.props
  msvc2015/warnings.props
  msvc2015/win32.dependency.props
  msvc2015/zlib.dependency.props
  msvc2017/Common/Common.vcxproj
  msvc2017/GiGi/GiGi.vcxproj
  msvc2017/boost.dependency.props
  msvc2017/win32.dependency.props
Labels: category:bug, category:refactoring, component:build system, priority:high

#2714 Raise C++ language version to C++14
  BUILD.md
  CMakeLists.txt
  ChangeLog.md
  GG/CMakeLists.txt
  msvc2017/cpp.lang.props
Labels: category:tweak, component:internal

#2789 Updating MSVC 2017 Project Configurations
  msvc2017/Common/Common.vcxproj
  msvc2017/FreeOrion.sln
  msvc2017/FreeOrion/FreeOrion.vcxproj
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2017/FreeOrionD/FreeOrionD.vcxproj
  msvc2017/GiGi/GiGi.vcxproj
  msvc2017/GiGiSDL/GiGiSDL.vcxproj
  msvc2017/Parsers/Parsers.vcxproj
Labels: category:refactoring, component:internal

#2653 Build freeorion with python3
  .travis.yml
  CMakeLists.txt
  client/AI/AIFramework.cpp
  client/AI/AIFramework.h
  cmake/make_versioncpp.py
  default/python/mypy.ini
  doc/tag_parser.py
  msvc2017/Common/Common.vcxproj
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2017/FreeOrionD/FreeOrionD.vcxproj
  packaging/windows_installer.nsi.in
  python/CommonFramework.cpp
  python/CommonFramework.h
  python/UniverseWrapper.cpp
  server/ServerFramework.cpp
  server/ServerFramework.h
  test/system/SmokeTestHostless.cpp
  util/Directories.cpp
Labels: category:feature, category:refactoring, component:AI, component:build system, component:content scripting, component:internal, priority:high, status:help wanted, status:testing requested

#2790 Raise minimum Python requirements in build instructions to 3.5
  BUILD.md
Labels: category:tweak, component:technical docs, status:merged

#2791 Fix headless compilation
  .travis.yml
  CMakeLists.txt
  GG/CMakeLists.txt
Labels: category:bug, component:build system, priority:high

#2792 Reference Production Queue Elements by UUID
  Empire/Empire.cpp
  Empire/ProductionQueue.cpp
  Empire/ProductionQueue.h
  UI/ObjectListWnd.cpp
  UI/ProductionWnd.cpp
  client/AI/AIWrapper.cpp
  server/ServerApp.cpp
  universe/ShipDesign.cpp
  util/Order.cpp
  util/Order.h
  util/SerializeEmpire.cpp
  util/SerializeOrderSet.cpp
Labels: category:bug, category:feature, component:internal

#2796 Allocate list of items for mutable dictionary
  default/python/AI/ResourcesAI.py
Labels: category:bug, component:AI

#2797 Allocate list of mutable dictionary items
  default/python/AI/ResourcesAI.py
Labels: category:bug, component:AI

#2801 Add glyphs U+27F2 and U+27F3 in Roboto-Bold font
  default/data/fonts/Roboto-Bold.ttf
Labels: category:tweak, component:art music text assets

#2802 Remove boost::lexical_cast within << operator chains
  Empire/ResourcePool.cpp
  UI/BuildDesignatorWnd.cpp
  UI/FleetWnd.cpp
  UI/SystemResourceSummaryBrowseWnd.cpp
  server/ServerApp.cpp
  universe/ShipDesign.cpp
  universe/System.cpp
  universe/Universe.cpp
  universe/UniverseGenerator.cpp
  universe/UniverseObject.cpp
Labels: category:refactoring, component:internal

#2688 Add Gamma Burst Slingshot SR weapon
  default/data/art/icons/ship_parts/pulse-laser-1.png
  default/data/art/icons/ship_parts/pulse-laser-2.png
  default/data/art/icons/ship_parts/pulse-laser-3.png
  default/data/art/icons/ship_parts/pulse-laser-4.png
  default/data/art/icons/ship_parts/pulse-laser.png
  default/python/AI/AIDependencies.py
  default/python/AI/TechsListsAI.py
  default/scripting/ship_hulls/SH_COLONY_BASE.focs.txt
  default/scripting/ship_parts/ShortRange/SR_ARC_DISRUPTOR.focs.txt
  default/scripting/techs/ship_weapons/short_range/SHP_ARC_DISRUPTOR.focs.txt
  default/stringtables/en.txt
Labels: category:feature, component:content scripting

#2803 Don't expect CMake policy CMP0044 OLD behaviour anymore
  GG/CMakeLists.txt
Labels: category:tweak, component:infrastructure

#2665 [default-only] KISS hard targeting
  default/python/AI/AIDependencies.py
  default/python/AI/ShipDesignAI.py
  default/scripting/ship_parts/FighterBay/FT_BAY_1.focs.txt
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_1.focs.txt
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_2.focs.txt
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_3.focs.txt
  default/scripting/ship_parts/FighterHangar/FT_HANGAR_4.focs.txt
  default/scripting/ship_parts/ShortRange/SR_SPINAL_ANTIMATTER.focs.txt
  default/scripting/ship_parts/ShortRange/SR_WEAPON_1_1.focs.txt
  default/scripting/ship_parts/ShortRange/SR_WEAPON_2_1.focs.txt
  default/scripting/ship_parts/ShortRange/SR_WEAPON_3_1.focs.txt
  default/scripting/ship_parts/ShortRange/SR_WEAPON_4_1.focs.txt
  default/scripting/species/common/weapons.macros
  default/scripting/techs/ship_weapons/fighters/SHP_FIGHTERS_1.focs.txt
  default/scripting/techs/ship_weapons/fighters/SHP_FIGHTERS_2.focs.txt
  default/scripting/techs/ship_weapons/fighters/SHP_FIGHTERS_3.focs.txt
  default/scripting/techs/ship_weapons/fighters/SHP_FIGHTERS_4.focs.txt
  default/stringtables/en.txt
Labels: category:feature, component:content scripting

#2804 Improve invasion description to account for manual and automatic ship…
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets

#2806 Scape trigraph to avoid warning
  universe/Fleet.cpp
Labels: category:bug, category:tweak, component:internal

#2805 Remove GLU dependency
  BUILD.md
  CMakeLists.txt
  ChangeLog.md
  GG/CMakeLists.txt
  GG/GG/Texture.h
  GG/src/SDL/SDLGUI.cpp
  GG/src/Texture.cpp
  GG/test/acceptance/runner/Application.cpp
  UI/ShaderProgram.cpp
  UI/SidePanel.cpp
  msvc2017/opengl.dependency.props
  snap/snapcraft.yaml
Labels: category:refactoring, component:internal

#2811 Replace deprecated logging.warn with logging.warning
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/ColonisationAI.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/EspionageAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/MoveUtilsAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/TechsListsAI.py
  default/python/AI/character/character_module.py
  default/python/AI/fleet_orders.py
  default/python/AI/pathfinding.py
  default/python/AI/target.py
  default/python/AI/turn_state.py
  default/python/auth/auth.py
  default/python/common/configure_logging.py
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/interface_inspector.py
  default/python/tests/AI/test_assertion_fails.py
Labels: category:refactoring, component:AI
