Repository freeorion/freeorion, pull requests merged in 2020-09, with the labels that each got.

#3159 Fixes empire selection for loaded game
  UI/MultiplayerLobbyWnd.cpp
Labels: category:bug, component:UI

#3066 Use structure instead of lambda in asynchronous socket close
  server/ServerNetworking.cpp
Labels: category:bug, component:network

#3160 README.md: Add link to Flathub
  README.md
Labels: category:feature, component:deployment

#3162 Fix #3161
  UI/CombatReport/GraphicalSummary.cpp
Labels: category:bug, component:UI

#3164 Changelog update
  ChangeLog.md
Labels: category:tweak, component:technical docs

#3168 Fix Bio-Adaptive hull regeneration description.
  default/stringtables/en.txt
Labels: category:bug, component:user manual, status:cherry-pick for release

#3169 Fix 3144 (retry)
  default/data/art/icons/ship_parts/pulse-laser.png
Labels: category:bug, component:art music text assets, status:cherry-pick for release

#3174 Fix compilation for boost 1.74
  GG/src/Texture.cpp
  UI/GovernmentWnd.cpp
  UI/ObjectListWnd.cpp
Labels: category:bug, component:build system, priority:high

#3173 Bump minimum Boost version from 1.58 to 1.60
  CMakeLists.txt
  GG/CMakeLists.txt
Labels: category:bug, component:infrastructure, component:internal

#3175 Fix compilation for boost 1.74
  GG/src/Texture.cpp
  UI/ObjectListWnd.cpp
Labels: category:bug, component:infrastructure, component:internal

#3177 Fix compatibility with ubuntu 16.04 xenial
  .travis.yml
  CMakeLists.txt
  GG/CMakeLists.txt
  GG/GG/Spin.h
  GG/src/DropDownList.cpp
  GG/src/Font.cpp
  GG/src/GUI.cpp
  GG/src/ListBox.cpp
  GG/src/MultiEdit.cpp
  GG/src/ScrollPanel.cpp
  GG/src/TabWnd.cpp
  GG/src/Timer.cpp
  GG/src/dialogs/ColorDlg.cpp
  GG/src/dialogs/FileDlg.cpp
  UI/BuildDesignatorWnd.cpp
  UI/ChatWnd.cpp
  UI/CombatReport/CombatLogWnd.cpp
  UI/CombatReport/CombatReportWnd.cpp
  UI/DesignWnd.cpp
  UI/EncyclopediaDetailPanel.cpp
  UI/FleetWnd.cpp
  UI/GalaxySetupWnd.cpp
  UI/MapWnd.cpp
  UI/MultiplayerLobbyWnd.cpp
  UI/ObjectListWnd.cpp
  UI/OptionsWnd.cpp
  UI/PlayerListWnd.cpp
  UI/ProductionWnd.cpp
  UI/QueueListBox.cpp
  UI/ResearchWnd.cpp
  UI/SaveFileDialog.cpp
  UI/ServerConnectWnd.cpp
  UI/SidePanel.cpp
  UI/SitRepPanel.cpp
  UI/TechTreeWnd.cpp
  client/human/HumanClientApp.cpp
  python/EmpireWrapper.cpp
  server/ServerApp.cpp
  server/ServerNetworking.cpp
  universe/Conditions.cpp
  universe/Fleet.cpp
  universe/Pathfinder.cpp
  universe/ValueRefs.cpp
  util/Logger.cpp
Labels: category:bug, component:build system, component:internal

#3000 Reference Named ValueRefs in stringtables
  UI/CUILinkTextBlock.cpp
  UI/ClientUI.cpp
  UI/ClientUI.h
  UI/EncyclopediaDetailPanel.cpp
  UI/LinkText.cpp
  UI/LinkText.h
  UI/OptionsWnd.cpp
  UI/SitRepPanel.cpp
  check/st-tool.py
  default/customizations/custom_sitreps.txt
  default/scripting/common/named_values.focs.txt
  default/scripting/techs/ship_parts/damage_control/SHP_REINFORCED_HULL.focs.txt
  default/scripting/techs/ship_parts/fuel/fuel.macros
  default/stringtables/en.txt
  msvc2017/Common/Common.vcxproj
  msvc2017/Common/Common.vcxproj.filters
  msvc2017/Parsers/Parsers.vcxproj
  msvc2017/Parsers/Parsers.vcxproj.filters
  parse/ArithmeticRules.cpp
  parse/CMakeLists.txt
  parse/DoubleValueRefParser.cpp
  parse/EnumValueRefRules.h
  parse/IntComplexValueRefParser.cpp
  parse/IntValueRefParser.cpp
  parse/NamedValueRefParser.cpp
  parse/Parse.h
  parse/Tokens.h
  parse/ValueRefParser.h
  universe/CMakeLists.txt
  universe/NamedValueRefManager.cpp
  universe/NamedValueRefManager.h
  universe/Universe.cpp
  universe/ValueRef.h
  universe/ValueRefs.cpp
  universe/ValueRefs.h
  util/AppInterface.cpp
  util/VarText.cpp
  util/VarText.h
Labels: category:feature, component:art music text assets, component:content scripting
