Repository freeorion/freeorion, pull requests merged in 2021-06, with the labels that each got.

#3469 Add pre-commit hooks
  .pre-commit-config.yaml
  default/python/README.md
Labels: category:feature, component:infrastructure

#3475 Update table prints
  default/python/AI/AIstate.py
  default/python/AI/ColonisationAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ResourcesAI.py
  default/python/common/print_utils/__init__.py
  default/python/common/print_utils/_base_field.py
  default/python/common/print_utils/_fields.py
  default/python/common/print_utils/_table.py
  default/python/stub_generator/stub_generator/class_generator.py
  default/python/tests/common/test_print_utils.py
  default/python/universe_generation/universe_statistics.py
Labels: category:refactoring, component:AI

#3478 Extract nest rating
  default/python/AI/ColonisationAI.py
  default/python/AI/colonization/__init__.py
  default/python/AI/colonization/nest_rating.py
Labels: category:refactoring, component:AI

#3481 fixed a typo
  default/stringtables/en.txt
Labels: category:tweak, component:art music text assets

#3431 Start the server with Godot client
  .github/workflows/build-ubuntu.yml
  .github/workflows/build-windows.yml
  CMakeLists.txt
  client/godot/CMakeLists.txt
  client/godot/FreeOrionNode.cpp
  client/godot/FreeOrionNode.h
  client/godot/GodotClientApp.cpp
  client/godot/GodotClientApp.h
  client/godot/cgmain.cpp
  godot/.gitignore
  godot/FreeOrionClient.gd
  godot/FreeOrionClient.tscn
  godot/GameSetup.gd
  godot/GameSetup.tscn
  godot/StartingSpeciesInput.gd
  godot/assets/audio/artificial_intelligence_v3.ogg
  godot/assets/fonts
  godot/assets/image/FO_Icon_256x256.png
  godot/assets/image/gp_box.png
  godot/assets/image/gp_cluster.png
  godot/assets/image/gp_disc.png
  godot/assets/image/gp_elliptical.png
  godot/assets/image/gp_irregular.png
  godot/assets/image/gp_random.png
  godot/assets/image/gp_ring.png
  godot/assets/image/gp_spiral2.png
  godot/assets/image/gp_spiral3.png
  godot/assets/image/gp_spiral4.png
  godot/assets/image/logo.png
  godot/assets/image/randomize.png
  godot/assets/image/randomize_clicked.png
  godot/assets/image/randomize_mouseover.png
  godot/assets/image/species
  godot/assets/image/splash.png
  godot/freeoriongodot.gdnlib
  godot/freeoriongodot.gdns
  godot/project.godot
  godot/resources/fonts/DejaVuSans-Bold.tres
  godot/test/integration/test_quickstart.gd
Labels: category:feature, component:godot-client

#3483 Re-enable clang for CI
  .github/workflows/build-ubuntu.yml
Labels: category:tweak, component:infrastructure

#3484 Extract evaluate_planet and helper functions to the separate files
  default/python/AI/ColonisationAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/colonization/calculate_planet_colonization_rating.py
  default/python/AI/colonization/calculate_population.py
  default/python/AI/colonization/colony_score.py
Labels: category:refactoring, component:AI

#3476 Nerf inf. malus of Indoctrination and Checkpoints
  default/scripting/policies/CHECKPOINTS.focs.txt
  default/scripting/policies/INDOCTRINATION.focs.txt
  default/scripting/species/common/influence.macros
Labels: category:tweak, component:content scripting

#3486 Destroy on capture and set visibility for abandon outpost and independence
  default/scripting/buildings/ABANDON_OUTPOST.focs.txt
  default/scripting/buildings/COLONY_INDEPENDENCE_DECREE.focs.txt
Labels: category:bug, component:content scripting

#3487 Import priorities.macros in indoctrination policy
  default/scripting/policies/INDOCTRINATION.focs.txt
Labels: category:bug, component:content scripting

#3480 Change "maximum" for "target" in Populaton Pedia article
  default/scripting/common/misc.macros
  default/scripting/common/misc.py
  default/scripting/common/named_values.focs.txt
  default/stringtables/de.txt
  default/stringtables/en.txt
  default/stringtables/es.txt
  default/stringtables/fr.txt
  default/stringtables/ru.txt
Labels: category:tweak, component:art music text assets

#3489 Avoid linking against libvorbisenc
  CMakeLists.txt
Labels: category:tweak, component:build system

#3493 Add stability species trait plus some rebalance
  default/scripting/species/SP_ABADDONI.focs.txt
  default/scripting/species/SP_BANFORO.focs.txt
  default/scripting/species/SP_CRAY.focs.txt
  default/scripting/species/SP_CYNOS.focs.txt
  default/scripting/species/SP_DERTHREAN.focs.txt
  default/scripting/species/SP_EAXAW.focs.txt
  default/scripting/species/SP_EGASSEM.focs.txt
  default/scripting/species/SP_ETTY.focs.txt
  default/scripting/species/SP_EXOBOT.focs.txt
  default/scripting/species/SP_FULVER.focs.txt
  default/scripting/species/SP_GEORGE.focs.txt
  default/scripting/species/SP_GISGUSGTHRIM.focs.txt
  default/scripting/species/SP_HAPPY.focs.txt
  default/scripting/species/SP_HHOH.focs.txt
  default/scripting/species/SP_KOBUNTURA.focs.txt
  default/scripting/species/SP_MISIORLA.focs.txt
  default/scripting/species/SP_MUURSH.focs.txt
  default/scripting/species/SP_PHINNERT.focs.txt
  default/scripting/species/SP_REPLICON.focs.txt
  default/scripting/species/SP_SCYLIOR.focs.txt
  default/scripting/species/SP_SETINON.focs.txt
  default/scripting/species/SP_SILEXIAN.focs.txt
  default/scripting/species/SP_SLY.focs.txt
  default/scripting/species/SP_SUPERTEST.focs.txt
  default/scripting/species/SP_TAEGHIRUS.focs.txt
  default/scripting/species/SP_TRITH.focs.txt
  default/scripting/species/SP_UGMORS.focs.txt
  default/scripting/species/SP_VOLP.focs.txt
  default/scripting/species/common/happiness.macros
  default/stringtables/en.txt
Labels: category:feature, component:content scripting

#3496 Fix compilation
  universe/Conditions.cpp
Labels: category:bug, component:internal

#3491 Introduce fo specific type annotations
  default/python/AI/AIFleetMission.py
  default/python/AI/CombatRatingsAI/_fleet_combat_stats.py
  default/python/AI/CombatRatingsAI/_ratings.py
  default/python/AI/CombatRatingsAI/_ship_combat_stats.py
  default/python/AI/ExplorationAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/MoveUtilsAI.py
  default/python/AI/freeOrionAIInterface.pyi
  default/python/AI/freeorion_tools/_fleet_position.py
  default/python/AI/target.py
  default/python/AI/turn_state/_dry_dock_state.py
  default/python/AI/turn_state/_planet_state.py
  default/python/AI/turn_state/_supply_state.py
  default/python/common/fo_typing.py
  default/python/freeorion.pyi
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/stub_generator/class_generator.py
  default/python/stub_generator/stub_generator/function_generator.py
Labels: category:refactoring, component:AI

#3488 Combine list of identical building effects into one
  UI/MeterBrowseWnd.cpp
Labels: category:feature, component:UI

#3502 Update AI annotations
  default/python/AI/FleetUtilsAI.py
  default/python/AI/PlanetUtilsAI.py
  default/python/AI/colonization/calculate_planet_colonization_rating.py
  default/python/AI/freeOrionAIInterface.pyi
  default/python/common/fo_typing.py
  default/python/freeorion.pyi
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/stub_generator/base_generator.py
  default/python/stub_generator/stub_generator/class_generator.py
  default/python/stub_generator/stub_generator/enum_generator.py
Labels: category:refactoring, component:AI

#3501 Fix compilation (#3496)
  universe/Conditions.cpp
Labels: category:bug, component:internal

#3490 cmake: hide PATH-Variables in the advanced section
  cmake/FindFreetype.cmake
  cmake/FindSDL.cmake
Labels: category:tweak, component:build system

#3503 Fixed calculation for (dis-)liked building in other systems
  default/scripting/buildings/buildings.macros
Labels: category:bug, category:tweak, component:content scripting

#3504 document stability requirements
  default/scripting/buildings/BLACK_HOLE_POW_GEN.focs.txt
  default/scripting/buildings/COLLECTIVE_NET.focs.txt
  default/scripting/buildings/CULTURE_ARCHIVES.focs.txt
  default/scripting/buildings/CULTURE_LIBRARY.focs.txt
  default/scripting/buildings/ENCLAVE_VOID.focs.txt
  default/scripting/buildings/GAS_GIANT_GEN.focs.txt
  default/scripting/buildings/HYPER_DAM.focs.txt
  default/scripting/buildings/INDUSTRY_CENTER.focs.txt
  default/scripting/buildings/INTERSPECIES_ACADEMY.focs.txt
  default/scripting/buildings/SOL_ORB_GEN.focs.txt
  default/scripting/policies/AUTOMATED_RESEARCH.focs.txt
  default/scripting/policies/CENTRALIZATION.focs.txt
  default/scripting/policies/CONFORMANCE.focs.txt
  default/scripting/policies/DIVERSITY.focs.txt
  default/scripting/policies/INDUSTRIALISM.focs.txt
  default/scripting/policies/LIBERTY.focs.txt
  default/scripting/specials/planet/COMPUTRONIUM.focs.txt
  default/scripting/specials/planet/ECCENTRIC_ORBIT.focs.txt
  default/scripting/specials/planet/PHILOSOPHER.focs.txt
  default/scripting/specials/planet/TEMPORAL_ANOMOLY.focs.txt
  default/scripting/techs/learning/DISTRIB_THOUGHT.focs.txt
  default/scripting/techs/learning/NASCENT_AI.focs.txt
  default/scripting/techs/learning/QUANT_NET.focs.txt
  default/scripting/techs/production/ADAPTIVE_AUTOMATION.focs.txt
  default/scripting/techs/production/FUSION_GEN.focs.txt
  default/scripting/techs/production/MICRO_MANUF.focs.txt
  default/scripting/techs/production/ROBOTIC_PROD.focs.txt
  default/stringtables/en.txt
Labels: category:feature, component:user manual
