Repository freeorion/freeorion, pull requests merged in 2021-04, with the labels that each got.

#3378 Fix multiplayer issues
  server/ServerApp.cpp
  server/ServerFSM.cpp
Labels: category:bug, component:network, priority:high

#3376 Detect boost python library from python library instead of python executable [0.4.10]
  CMakeLists.txt
  cmake/make_versioncpp.py
Labels: category:bug, category:refactoring, component:build system

#3375 Detect boost python library from python library instead of python executable
  CMakeLists.txt
  cmake/make_versioncpp.py
Labels: category:bug, category:refactoring, component:build system

#3380 [AI] Simplify enums
  default/python/AI/EnumsAI.py
  default/python/tests/AI/test_enum_implementation.py
Labels: category:refactoring, component:AI

#3382 Update generated stubs
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
Labels: category:tweak, component:infrastructure

#3365 Move single content files to appropriate folders
  .travis.yml
  default/README.md
  default/customizations/README.md
  default/scripting/README.md
  default/scripting/custom_sitreps.txt
  default/scripting/empire_colors.xml
  default/scripting/techs/spy/CUSTOM_ADVISORIES.focs.txt
  default/stringtables/common_user_customizations.txt
  default/stringtables/content_specific_parameters.txt
  default/stringtables/cz.txt
  default/stringtables/da.txt
  default/stringtables/de.txt
  default/stringtables/en.txt
  default/stringtables/es.txt
  default/stringtables/fi.txt
  default/stringtables/fr.txt
  default/stringtables/it.txt
  default/stringtables/nl.txt
  default/stringtables/pl.txt
  default/stringtables/ru.txt
  default/stringtables/sv.txt
  util/AppInterface.cpp
Labels: category:refactoring, component:content scripting

#3385 Refactor stub generator
  default/python/handlers/inspect_freeOrionAIInterface.py
  default/python/handlers/inspect_universe_generation.py
  default/python/stub_generator/__init__.py
  default/python/stub_generator/constants.py
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/interface_inspector.py
  default/python/stub_generator/interface_inspector/__init__.py
  default/python/stub_generator/interface_inspector/class_processor.py
  default/python/stub_generator/interface_inspector/enum_processor.py
  default/python/stub_generator/interface_inspector/function_processor.py
  default/python/stub_generator/interface_inspector/inspection_helpers.py
  default/python/stub_generator/interface_inspector/instance_processing.py
  default/python/stub_generator/interface_inspector/module_inspector.py
  default/python/stub_generator/parse_docs.py
Labels: category:refactoring, component:infrastructure

#3381 Replace type: in docstring with type annotation
  default/python/AI/ResearchAI.py
  default/python/AI/ShipDesignAI.py
Labels: category:refactoring, component:AI

#3368 Read resource files on Android from APK
  CMakeLists.txt
  Empire/EmpireManager.cpp
  parse/DummyParsers.cpp
  parse/Parse.cpp
  parse/Parse.h
  util/AppInterface.cpp
  util/Directories.cpp
  util/Directories.h
  util/MultiplayerCommon.cpp
  util/StringTable.cpp
  util/i18n.cpp
  util/i18n.h
Labels: category:feature, component:internal, status:merged

#3391 Remove misleading log entry
  universe/ShipDesign.cpp
Labels: category:refactoring, component:internal

#3336 Add BLD_COLONY_INDEPENDENCE_DECREE to unown your colony (MAX DEFENSE version)
  default/scripting/buildings/COLONY_INDEPENDENCE_DECREE.focs.txt
  default/scripting/specials/INDEPENDENT_COLONY_DEFENSE.focs.txt
  default/scripting/specials/INDEPENDENT_COLONY_POPULATION.focs.txt
  default/scripting/specials/INDEPENDENT_COLONY_SHIELD.focs.txt
  default/scripting/specials/INDEPENDENT_COLONY_TROOPS.focs.txt
  default/scripting/starting_unlocks/items.inf
  default/stringtables/en.txt
Labels: category:feature, component:content scripting

#3379 Send background parsing to separate thread
  client/AI/AIClientApp.cpp
  client/human/GGHumanClientApp.cpp
  server/ServerApp.cpp
  server/ServerApp.h
  test/parse/TestScriptParser.cpp
  test/system/ClientAppFixture.cpp
  util/AppInterface.cpp
  util/AppInterface.h
  util/Pending.h
Labels: category:refactoring, component:internal

#3393 Print internal enums as names
  default/python/AI/EnumsAI.py
  default/python/tests/AI/test_enum_implementation.py
Labels: category:refactoring, component:AI

#3394 Cleanup production
  default/python/AI/ProductionAI.py
Labels: category:refactoring, component:AI

#3371 Test number of all parsed techs
  test/parse/TestScriptParser.cpp
Labels: category:refactoring, component:internal

#3395 Fix random chosing of the colonization planets
  default/python/AI/ProductionAI.py
Labels: category:bug, component:AI

#3402 Refactored distance to capital stability
  default/scripting/species/common/happiness.macros
Labels: category:bug, category:refactoring, component:content scripting

#3403 Fixes installation layout of snap package
  .github/snap-xvfb-launch.sh
  .github/workflows/snapcraft.yml
  snap/local/20210308_core20_unexpanded__snapcraft.yaml
  snap/snapcraft.yaml
Labels: category:tweak, component:build system, status:merged

#3406 Fix typo for android
  util/i18n.cpp
Labels: category:bug, component:internal, status:merged

#3404 Add cache directory access
  util/Directories.cpp
  util/Directories.h
Labels: category:tweak, component:internal, status:merged

#3397 Build Location Regional Administration
  default/scripting/buildings/REGIONAL_ADMIN.focs.txt
Labels: category:bug, component:content scripting

#3408 Use Github Actions for Ubuntu builds
  .github/workflows/build-ubuntu.yml
  .github/workflows/ubuntu-18.04-install-build.sh
  .github/workflows/ubuntu-20.04-install-build.sh
Labels: category:feature, component:infrastructure

#3260 Download godot-cpp from git if Godot client enabled
  .github/workflows/build-ubuntu.yml
  .github/workflows/ubuntu-20.04-install-build.sh
  .travis.yml
  CMakeLists.txt
  client/CMakeLists.txt
  util/CMakeLists.txt
Labels: category:feature, component:build system

#3411 Use Github Actions for MacOS build
  .github/workflows/build-macos.yml
  .github/workflows/mono-uninstall.sh
  CMakeLists.txt
Labels: category:tweak, component:infrastructure

#3409 Use Github Actions for Windows CMake build
  .appveyor.yml
  .github/workflows/build-windows.yml
  CMakeLists.txt
  util/Enum.h
  util/OrderSet.h
Labels: category:tweak, component:infrastructure

#3342 Make python into freeorioncommon dependency
  CMakeLists.txt
  msvc2017/Common/Common.vcxproj
  msvc2017/FreeOrion/FreeOrion.vcxproj
  msvc2019/Common/Common.vcxproj
  msvc2019/FreeOrion/FreeOrion.vcxproj
  msvc2019/Test/Test.vcxproj
  util/DependencyVersions.cpp
  util/Directories.cpp
Labels: category:refactoring, component:build system, component:internal

#3420 Fix use of boost placeholders
  UI/TechTreeWnd.cpp
Labels: category:bug, priority:high

#3418 Re-added reverse connection check to JUMPS_TO_CAPITAL_OR_REGAD
  default/scripting/species/common/happiness.macros
Labels: category:bug, component:content scripting

#3413 Fix small issues in CMake for Godot project
  CMakeLists.txt
Labels: category:tweak, component:build system, status:merged

#3419 Fix mklink usage on windows
  cmake/TargetDependencies.cmake
Labels: category:bug, component:build system, status:merged

#3405 Add options to set path to freeoriond executable
  client/human/GGHumanClientApp.cpp
  client/human/chmain.cpp
  default/stringtables/en.txt
  test/system/ClientAppFixture.cpp
  test/system/ClientAppFixture.h
  test/system/SmokeTestGame.cpp
  test/system/SmokeTestHostless.cpp
Labels: category:tweak, component:internal

#3414 Fix cache name for Gihhub Actions on Ubuntu
  .github/workflows/build-ubuntu.yml
Labels: category:bug, component:infrastructure

#3410 Add list of ignored paths to snap build
  .github/workflows/snapcraft.yml
Labels: category:tweak, component:infrastructure

#3423 Display ValueRef floating points with only 3 digits in UI
  universe/ValueRef.h
Labels: category:tweak, component:UI

#3301 [AI] Extract work with designs from production to separate module
  default/python/AI/ColonisationAI.py
  default/python/AI/FreeOrionAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/PriorityAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/turn_state/design.py
Labels: category:refactoring, component:AI

#3417 Enable testing and Godot for MacOS CI
  .github/workflows/build-macos.yml
Labels: category:tweak, component:infrastructure, status:merged

#3384 Remove unused enum value from EnumWrapper
  python/EnumWrapper.cpp
Labels: category:bug, component:internal

#3416 Update xvfb-action to use Xvfb server options
  .github/workflows/snapcraft.yml
Labels: category:tweak, component:infrastructure, status:merged

#3412 Fixed Exobot Productivity effect
  default/scripting/policies/EXOBOT_PRODUCTIVITY.focs.txt
Labels: category:bug, component:content scripting

#3425 Godot singleplayer and multiplayer windows
  .gitignore
  godot/.gitignore
  godot/AIAggressionInput.gd
  godot/FOWindow.gd
  godot/FOWindow.tscn
  godot/FreeOrionClient.gd
  godot/GalaxyAgeInput.gd
  godot/GalaxySetupOptionInput.gd
  godot/GalaxyShapeInput.gd
  godot/GameSetup.gd
  godot/GameSetup.tscn
  godot/MultiplayerClientTypeInput.gd
  godot/MultiplayerSetup.gd
  godot/MultiplayerSetup.tscn
  godot/MultiplayerSetupJoinButtonGroup.tres
  godot/SeedInput.gd
  godot/StartingSpeciesInput.gd
  godot/assets/fonts
  godot/assets/fonts/Roboto-Regular.ttf
  godot/assets/image/WindowFrameCloseWidget.png
  godot/assets/image/WindowFramePinWidgetOFF.png
  godot/assets/image/WindowFramePinWidgetON.png
  godot/assets/image/WindowFrameResizeWidget.png
  godot/assets/image/frames/FOSimpleFrame.png
  godot/assets/image/frames/FOWindowFrame.png
  godot/assets/image/gp_box.png
  godot/assets/image/gp_cluster.png
  godot/assets/image/gp_disc.png
  godot/assets/image/gp_elliptical.png
  godot/assets/image/gp_irregular.png
  godot/assets/image/gp_random.png
  godot/assets/image/gp_ring.png
  godot/assets/image/gp_spiral2.png
  godot/assets/image/gp_spiral3.png
  godot/assets/image/gp_spiral4.png
  godot/assets/image/randomize.png
  godot/assets/image/randomize_clicked.png
  godot/assets/image/randomize_mouseover.png
  godot/assets/image/species
  godot/global.gd
  godot/project.godot
  godot/resources/fonts/DejaVuSans-Bold.tres
  godot/resources/fonts/Roboto-Regular.tres
  godot/resources/materials/starlane_material.tres
Labels: category:feature, component:godot-client

#3415 Fix techs button issue
  util/AppInterface.cpp
  util/Pending.h
Labels: category:bug, component:UI, status:merged
