Repository freeorion/freeorion, pull requests merged in 2021-09, with the labels that each got.

#3474 Remove old code fromCMakesList
  CMakeLists.txt
Labels: component:build system, category:tweak

#3560 Fix star based colonization value calculation
  default/python/AI/colonization/calculate_planet_colonization_rating.py
Labels: category:bug, component:AI

#3559 Improve AI systems_connected performance
  default/python/AI/universe/system_network.py
Labels: category:refactoring, component:AI

#3526 Don't save game with incorrect turn number
  server/ServerFSM.cpp
Labels: category:bug, status:merged, component:internal

#3497 Return false from auth.py result to mark unallowed player names
  default/python/auth/auth.py
  server/ServerFramework.cpp
Labels: category:feature, component:network

#3567 Connect to remote server from Godot
  godot/FreeOrionClient.gd
  godot/GalaxyMap.gd
  godot/GalaxyMap.tscn
  godot/MultiplayerSetup.gd
  godot/MultiplayerSetup.tscn
  godot/test/integration/test_quickstart.gd
Labels: category:feature, component:godot-client

#3569 [AI] Replace stub with mock
  default/python/tests/conftest.py
  default/python/tests/freeOrionAIInterface.py
Labels: category:refactoring, component:AI
