Repository freeorion/freeorion, pull requests merged in 2021-03, with the labels that each got.

#3338 Add initial tests for parser
  msvc2019/Test/Test.vcxproj
  msvc2019/Test/Test.vcxproj.filters
  test-scripting/game_rules.focs.txt
  test-scripting/techs/Categories.inf
  test-scripting/techs/growth/ORBITAL_HAB.focs.txt
  test-scripting/techs/learning/ALGO_ELEGANCE.focs.txt
  test/CMakeLists.txt
  test/parse/CMakeLists.txt
  test/parse/ParserAppFixture.cpp
  test/parse/ParserAppFixture.h
  test/parse/TestScriptParser.cpp
Labels: category:tweak, component:internal

#3249 Enable test build on MacOS CI
  .travis.yml
  test/parse/CMakeLists.txt
Labels: category:bug, component:build system

#3344 Allow AI to delegate player
  server/ServerApp.cpp
  server/ServerFSM.cpp
Labels: category:feature, component:network

#3346 snapcraft.yaml update with base:core20
  snap/local/20210308_core20_unexpanded__snapcraft.yaml
  snap/snapcraft.yaml
Labels: category:feature, component:deployment

#3345 Add clone method to value ref and condition
  universe/Condition.h
  universe/ConditionAll.h
  universe/ConditionSource.h
  universe/Conditions.cpp
  universe/Conditions.h
  universe/NamedValueRefManager.h
  universe/ValueRef.h
  universe/ValueRefs.h
Labels: category:feature, component:internal, status:help wanted

#3347 Implement Clone for Effect
  universe/Effect.h
  universe/Effects.cpp
  universe/Effects.h
  universe/ValueRef.h
Labels: category:refactoring, component:internal

#3351 Relaxed authentication should be allowed only for AI, not for non-AI
  server/ServerFSM.cpp
Labels: category:bug, component:network

#3348 Kill AI process of eliminated empire
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
Labels: category:feature, component:AI, component:internal

#3352 Fix crash on clone ComplexVariable
  universe/ValueRefs.h
Labels: category:bug

#3353 Kick out other players controls same empire
  server/ServerApp.cpp
Labels: category:feature, component:network

#3355 Raise python version for tests
  .travis.yml
Labels: category:tweak, component:infrastructure

#3357 Add option to allow human player to take over any AI
  default/stringtables/en.txt
  server/ServerApp.cpp
  server/dmain.cpp
Labels: category:feature, component:network

#3361 Update BUILD.md
  BUILD.md
Labels: category:tweak, component:build system, component:technical docs

#3364 Add CI test for snap packages
  .github/workflows/snapcraft.yml
  snap/snapcraft.yaml
Labels: category:tweak, component:infrastructure

#3363 Economic Policies
  Empire/Empire.cpp
  Empire/Empire.h
  Empire/Government.cpp
  Empire/Government.h
  UI/EncyclopediaDetailPanel.cpp
  default/data/art/icons/policies/interstellar_infrastructure.png
  default/data/art/icons/policies/planetary_infrastructure.png
  default/data/art/icons/policies/system_infrastructure.png
  default/data/art/icons/policies/traffic_control.png
  default/python/AI/AIDependencies.py
  default/python/AI/ResearchAI.py
  default/python/AI/TechsListsAI.py
  default/scripting/buildings/REGIONAL_ADMIN.focs.txt
  default/scripting/common/base_prod.macros
  default/scripting/common/upkeep.macros
  default/scripting/policies/CENTRALIZATION.focs.txt
  default/scripting/policies/COLONIZATION.focs.txt
  default/scripting/policies/INTERSTELLAR_INFRASTRUCTURE.focs.txt
  default/scripting/policies/PLANETARY_INFRASTRUCTURE.focs.txt
  default/scripting/policies/SYSTEM_INFRASTRUCTURE.focs.txt
  default/scripting/policies/TRAFFIC_CONTROL.focs.txt
  default/scripting/species/common/influence.macros
  default/scripting/starting_unlocks/items.inf
  default/scripting/techs/construction/ART_HEAVEN.focs.txt
  default/scripting/techs/construction/ART_PLANET.focs.txt
  default/scripting/techs/construction/GALACTIC_INFRA.focs.txt
  default/scripting/techs/construction/INTERSTELLAR_LOG.focs.txt
  default/scripting/techs/construction/ORGANIC_STRUCT.focs.txt
  default/scripting/techs/construction/OUTPOST.focs.txt
  default/scripting/techs/construction/PLANET_DRIVE.focs.txt
  default/scripting/techs/construction/STARGATE.focs.txt
  default/scripting/techs/learning/GATEWAY_VOID.focs.txt
  default/scripting/techs/ship_hulls/robotic/SHP_MIDCOMB_LOG.focs.txt
  default/scripting/techs/ship_parts/damage_control/SHP_ADV_DAM_CONT.focs.txt
  default/stringtables/cz.txt
  default/stringtables/de.txt
  default/stringtables/en.txt
  default/stringtables/es.txt
  default/stringtables/fr.txt
  default/stringtables/ru.txt
  parse/BuildingsParser.cpp
  parse/ParseImpl.h
  parse/PoliciesParser.cpp
  parse/SpeciesParser.cpp
  parse/TechsParser.cpp
  server/ServerApp.cpp
  universe/Tech.cpp
  universe/Tech.h
  universe/Universe.h
Labels: category:feature, component:content scripting

#3369 Fix first turn advance time without fixed turn interval
  default/stringtables/en.txt
  server/ServerFSM.cpp
Labels: category:bug, component:internal, component:network
