Repository freeorion/freeorion, pull requests merged in 2021-08, with the labels that each got.

#3537 Fix sign switch on xenophobic self malus
  default/scripting/species/common/xenophobic.macros
Labels: category:bug, component:content scripting

#3505 Didn't kick out current player connection
  server/ServerApp.cpp
Labels: category:bug, component:network

#3541 Added TurnsSinceLastConquered, used in for Indoctrination
  default/scripting/policies/INDOCTRINATION.focs.txt
  default/scripting/techs/growth/ENERGY_META.focs.txt
  default/stringtables/en.txt
  parse/IntValueRefParser.cpp
  parse/Tokens.h
  universe/Planet.cpp
  universe/Planet.h
  universe/ValueRefs.cpp
Labels: category:feature, component:content scripting, category:tweak, component:user manual

#3542 Defined build and enqueue location for translator
  default/scripting/buildings/TRANSLATOR.focs.txt
Labels: component:content scripting, category:tweak

#3543 Fix calculation for conquered planets
  default/scripting/policies/INDOCTRINATION.focs.txt
Labels: category:bug, component:content scripting

#3531 Add black formatter
  .github/workflows/python-check.yml
  .github/workflows/python-format-check.yml
  .pre-commit-config.yaml
  check/st-tool.py
  cmake/make_versioncpp.py
  default/python/requirements-dev.txt
  default/python/stub_generator/stub_generator/function_generator.py
  default/python/tox.ini
  default/scripting/tox.ini
  doc/tag_parser.py
  msvc2017/update_stdafx.py
  msvc2019/update_stdafx.py
  pyproject.toml
  test-scripting/common/base_prod.py
  test-scripting/game_rules.focs.py
  test-scripting/techs/Categories.inf.py
  test-scripting/techs/growth/ORBITAL_HAB.focs.py
  test-scripting/techs/learning/ALGO_ELEGANCE.focs.py
  test-scripting/tox.ini
Labels: category:feature, component:infrastructure

#3538 Extract public module variables from ColonizationAI
  default/python/AI/ColonisationAI.py
  default/python/AI/FreeOrionAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/PlanetUtilsAI.py
  default/python/AI/PriorityAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/colonization/calculate_planet_colonization_rating.py
  default/python/AI/empire/README.md
  default/python/AI/empire/__init__.py
  default/python/AI/empire/buildings_locations.py
  default/python/AI/empire/colony_builders.py
  default/python/AI/empire/colony_status.py
  default/python/AI/empire/growth_specials.py
  default/python/AI/empire/pilot_rating.py
  default/python/AI/empire/ship_builders.py
  default/python/AI/turn_state/__init__.py
  default/python/AI/turn_state/_pilot_ratings.py
  default/python/AI/turn_state/_planet_state.py
  default/python/AI/turn_state/design.py
  default/python/common/fo_typing.py
Labels: category:refactoring, component:AI

#3509 Add Godot methods to connect to remote server and get universe objects
  client/godot/CMakeLists.txt
  client/godot/FreeOrionNode.cpp
  client/godot/FreeOrionNode.h
  client/godot/GodotFleet.cpp
  client/godot/GodotFleet.h
  client/godot/GodotSystem.cpp
  client/godot/GodotSystem.h
  client/godot/cgmain.cpp
Labels: category:feature, component:godot-client

#3550 Remove unused uid generation
  default/python/AI/AIstate.py
  default/python/AI/FreeOrionAI.py
Labels: category:refactoring, component:AI

#3548 [AI] Use caches to speedup invasion calculations
  default/python/AI/ExplorationAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/PlanetUtilsAI.py
  default/python/AI/freeorion_tools/_profile.py
  default/python/AI/universe/__init__.py
  default/python/AI/universe/system_network.py
  default/python/common/profiling.py
Labels: category:refactoring, component:AI

#3551 Round values to avoid saving too many digist after point
  default/python/AI/MilitaryAI.py
  default/python/AI/colonization/calculate_planet_colonization_rating.py
Labels: category:refactoring, component:AI

#3552 Preparation to have multiple prefixes for codecs
  default/python/AI/savegame_codec/_decoder.py
  default/python/AI/savegame_codec/_encoder.py
Labels: category:refactoring, component:AI

#3553 Cache shortest distance
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/ExplorationAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/pathfinding.py
  default/python/AI/universe/system_network.py
Labels: category:refactoring, component:AI
