Repository freeorion/freeorion, pull requests merged in 2021-01, with the labels that each got.

#3269 Show values of valuerefs in building tooltips
  UI/IconTextBrowseWnd.cpp
  UI/LinkText.cpp
  UI/LinkText.h
Labels: category:bug, component:UI

#3262 Rename GG's client class HumanClientApp to GGHumanClientApp
  UI/BuildDesignatorWnd.cpp
  UI/BuildingsPanel.cpp
  UI/CUIControls.cpp
  UI/CUIWnd.cpp
  UI/ChatWnd.cpp
  UI/ClientUI.cpp
  UI/CombatReport/CombatLogWnd.cpp
  UI/DesignWnd.cpp
  UI/EncyclopediaDetailPanel.cpp
  UI/FleetButton.cpp
  UI/FleetWnd.cpp
  UI/GalaxySetupWnd.cpp
  UI/GovernmentWnd.cpp
  UI/InGameMenu.cpp
  UI/IntroScreen.cpp
  UI/MapWnd.cpp
  UI/MeterBrowseWnd.cpp
  UI/MilitaryPanel.cpp
  UI/MultiIconValueIndicator.cpp
  UI/MultiMeterStatusBar.cpp
  UI/MultiplayerLobbyWnd.cpp
  UI/ObjectListWnd.cpp
  UI/OptionsWnd.cpp
  UI/PasswordEnterWnd.cpp
  UI/PlayerListWnd.cpp
  UI/PopulationPanel.cpp
  UI/ProductionWnd.cpp
  UI/ResearchWnd.cpp
  UI/ResourcePanel.cpp
  UI/SaveFileDialog.cpp
  UI/ServerConnectWnd.cpp
  UI/ShaderProgram.cpp
  UI/SidePanel.cpp
  UI/SitRepPanel.cpp
  UI/SpecialsPanel.cpp
  UI/SystemIcon.cpp
  UI/SystemResourceSummaryBrowseWnd.cpp
  UI/TechTreeArcs.cpp
  UI/TechTreeWnd.cpp
  client/human/CMakeLists.txt
  client/human/GGHumanClientApp.cpp
  client/human/GGHumanClientApp.h
  client/human/HumanClientFSM.cpp
  client/human/HumanClientFSM.h
  client/human/chmain.cpp
  msvc2017/FreeOrion/FreeOrion.vcxproj
Labels: category:refactoring, component:internal

#3271 Fix zero division in shield factor calculation see #3257
  default/python/AI/CombatRatingsAI.py
Labels: category:bug, component:AI, status:cherry-pick for release

#3273 Rename function.
  default/python/AI/AIstate.py
  default/python/AI/CombatRatingsAI.py
Labels: category:refactoring, component:AI, priority:low

#3274 Rename consider_refueling to max_stats
  default/python/AI/CombatRatingsAI.py
Labels: category:refactoring, component:AI

#3275 Move combine_ratings to tools
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/fleet_orders.py
  default/python/AI/freeorion_tools/__init__.py
  default/python/AI/freeorion_tools/combine_ratings.py
  default/python/tests/AI/test_combine_ratings.py
Labels: category:refactoring, component:AI

#3277 Refactor savegame codec tests
  default/python/tests/AI/save_game_codec/conftest.py
  default/python/tests/AI/save_game_codec/test_save_game_decoding.py
  default/python/tests/AI/save_game_codec/test_savegame_manager.py
Labels: category:refactoring, component:AI

#3278 Split CombatRatingsAi to submodules
  default/python/AI/AIstate.py
  default/python/AI/CombatRatingsAI.py
  default/python/AI/CombatRatingsAI/__init__.py
  default/python/AI/CombatRatingsAI/_fleet_combat_stats.py
  default/python/AI/CombatRatingsAI/_ratings.py
  default/python/AI/CombatRatingsAI/_ship_combat_stats.py
  default/python/AI/CombatRatingsAI/_targets.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/AI/savegame_codec/_definitions.py
Labels: category:refactoring, component:AI

#3279 Rebalance research
  default/scripting/specials/planet/TEMPORAL_ANOMOLY.focs.txt
  default/scripting/techs/learning/PSIONICS.focs.txt
Labels: category:tweak, component:content scripting

#3276 Build with C++17
  BUILD.md
  CMakeLists.txt
  GG/CMakeLists.txt
  msvc2017/Common/Common.vcxproj
  msvc2017/FreeOrion/FreeOrion.vcxproj
  msvc2017/FreeOrion/FreeOrion.vcxproj.filters
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2017/FreeOrionCA/FreeOrionCA.vcxproj.filters
  msvc2017/FreeOrionD/FreeOrionD.vcxproj
  msvc2017/GiGi/GiGi.vcxproj
  msvc2017/Parsers/Parsers.vcxproj
  msvc2017/cpp.lang.props
Labels: category:tweak, component:build system, status:help wanted

#3281 Fix savegame compatibility for AI
  default/python/AI/AIstate.py
  default/python/AI/CombatRatingsAI/_ratings.py
  default/python/AI/CombatRatingsAI/_ship_combat_stats.py
Labels: category:bug, component:AI

#3282 Reduce Conc. Camps industry boost
  default/scripting/buildings/CONC_CAMP.focs.txt
Labels: category:tweak, component:content scripting

#3283 Fix Industrialism value name
  default/scripting/policies/INDUSTRIALISM.focs.txt
  default/stringtables/en.txt
Labels: category:bug, component:content scripting

#3287 Fix issues related to skeleton generation and update skeleton
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/handlers/inspect_freeOrionAIInterface.py
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/interface_inspector.py
Labels: category:tweak, component:AI

#3289 Fix error message
  server/ServerWrapper.cpp
Labels: category:refactoring

#3290 Extract shared code for AI and universe generation
  default/python/AI/freeOrionAIInterface.pyi
  default/python/README.md
  default/python/freeorion.pyi
  default/python/handlers/inspect_freeOrionAIInterface.py
  default/python/handlers/inspect_universe_generation.py
  default/python/handlers/shared_instances_code.py
  default/python/stub_generator/__init__.py
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/interface_inspector.py
  default/python/stub_generator/parse_docs.py
  default/python/stub_generator/stub_functions.py
Labels: category:refactoring, component:AI

#3288 Remove getOrders from AI interface
  client/AI/AIWrapper.cpp
  default/python/AI/FreeOrionAI.py
Labels: category:refactoring, component:AI

#3286 Convert turn state to submodules
  default/python/AI/ColonisationAI.py
  default/python/AI/FreeOrionAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/MoveUtilsAI.py
  default/python/AI/PriorityAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/pathfinding.py
  default/python/AI/turn_state.py
  default/python/AI/turn_state/__init__.py
  default/python/AI/turn_state/_dry_dock_state.py
  default/python/AI/turn_state/_empire_resources.py
  default/python/AI/turn_state/_pilot_ratings.py
  default/python/AI/turn_state/_planet_state.py
  default/python/AI/turn_state/_supply_state.py
Labels: category:refactoring, component:AI

#3291 Move profiling code to separate module
  default/python/AI/freeorion_tools/__init__.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/AI/freeorion_tools/_profile.py
  default/python/AI/savegame_codec/_decoder.py
  default/python/AI/savegame_codec/_encoder.py
Labels: category:refactoring, component:AI

#3292 [AI] Cleanup code
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/ColonisationAI.py
  default/python/AI/EnumsAI.py
  default/python/AI/EspionageAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/aistate_interface.py
  default/python/AI/fleet_orders.py
Labels: category:refactoring, component:AI

#3285 Unlock Divine Authority policy at Transcendend Architecture tech
  default/scripting/techs/construction/TRANSCEND_ARCH.focs.txt
Labels: category:tweak, component:content scripting
