Repository freeorion/freeorion, pull requests merged in 2022-03, with the labels that each got.

#3716 [AI] Update python skeletons
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
Labels: component:infrastructure, category:tweak

#3703 Adapted basic growth formula.
  default/scripting/species/common/population.macros
Labels: component:content scripting, component:game mechanic, category:tweak

#3685 adding universe creation options for fewer monsters
  UI/GalaxySetupWnd.cpp
  UI/GalaxySetupWnd.h
  client/godot/GodotClientApp.cpp
  client/human/GGHumanClientApp.cpp
  default/python/AI/ColonisationAI.py
  default/python/AI/ExplorationAI.py
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/turn_events/turn_events.py
  default/python/universe_generation/empires.py
  default/python/universe_generation/universe_tables.py
  default/stringtables/en.txt
  python/EnumWrapper.cpp
  server/ServerApp.cpp
  test/system/ClientAppFixture.cpp
  test/system/TestChecksum.cpp
  util/MultiplayerCommon.cpp
  util/MultiplayerCommon.h
Labels: category:feature, component:content scripting, component:game mechanic

#3719 Fixed some AI exceptions
  default/python/AI/AIFleetMission.py
  default/python/AI/InvasionAI.py
  default/python/AI/ProductionAI.py
Labels: category:bug, component:AI

#3723 More basic AI stuff
  default/python/AI/AIDependencies.py
  default/python/AI/ColonisationAI.py
  default/python/AI/freeorion_tools/_fleet_position.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/tests/AI/test_parse_ai_tag_grade.py
Labels: component:AI, category:tweak

#3727 Remove unused check
  default/python/AI/ColonisationAI.py
Labels: category:refactoring, component:AI

#3721 Update development docs
  default/python/README.md
  default/python/pytest.ini
Labels: category:tweak, component:technical docs

#3722 Native/Special Defense Tweaks
  default/scripting/specials/planet/HIGH_TECH_NATIVES.focs.txt
  default/scripting/specials/planet/MODERATE_TECH_NATIVES.focs.txt
  default/scripting/specials/planet/NATIVE_FORTIFICATION_HIGH.focs.txt
  default/scripting/specials/planet/NATIVE_FORTIFICATION_LOW.focs.txt
  default/scripting/specials/planet/NATIVE_FORTIFICATION_MEDIUM.focs.txt
  default/scripting/specials/planet/NATIVE_FORTIFICATION_MINIMAL.focs.txt
  default/scripting/specials/planet/luxury/FRACTAL_GEODES.focs.txt
  default/scripting/specials/planet/luxury/MIMETIC_ALLOY.focs.txt
  default/scripting/specials/planet/luxury/SHIMMER_SILK.focs.txt
  default/scripting/specials/planet/luxury/SPARK_FOSSILS.focs.txt
  default/scripting/specials/planet/luxury/SUCCULENT_BARNACLES.focs.txt
  default/scripting/specials/planet/monster_guard.macros
  default/scripting/specials/planet/monster_nest/JUGGERNAUT_NEST.focs.txt
  default/scripting/specials/planet/monster_nest/KRAKEN_NEST.focs.txt
  default/scripting/specials/planet/monster_nest/SNOWFLAKE_NEST.focs.txt
  default/scripting/species/SP_BEIGEGOO.focs.txt
  default/scripting/species/SP_CELESTEPHYTE.focs.txt
  default/scripting/species/SP_CYNOS.focs.txt
  default/scripting/species/SP_DERTHREAN.focs.txt
  default/scripting/species/SP_FIFTYSEVEN.focs.txt
  default/scripting/species/SP_FURTHEST.focs.txt
  default/scripting/species/SP_GISGUSGTHRIM.focs.txt
  default/scripting/species/SP_HAPPY.focs.txt
  default/scripting/species/SP_HHOH.focs.txt
  default/scripting/species/SP_KHAKTURIAN.focs.txt
  default/scripting/species/SP_LEMBALALAM.focs.txt
  default/scripting/species/SP_NIGHTSIDERS.focs.txt
  default/scripting/species/SP_NYMNMN.focs.txt
  default/scripting/species/SP_OURBOOLS.focs.txt
  default/scripting/species/SP_PHINNERT.focs.txt
  default/scripting/species/SP_RAAAGH.focs.txt
  default/scripting/species/SP_SETINON.focs.txt
  default/scripting/species/SP_SILEXIAN.focs.txt
  default/scripting/species/SP_SLEEPERS.focs.txt
  default/scripting/species/SP_SSLITH.focs.txt
  default/scripting/species/SP_TAEGHIRUS.focs.txt
  default/scripting/species/SP_THENIAN.focs.txt
  default/scripting/species/SP_TRENCHERS.focs.txt
  default/scripting/species/SP_UGMORS.focs.txt
  default/scripting/species/SP_VOLP.focs.txt
  default/scripting/species/common/native_fortification.macros
  default/scripting/species/common/planet_size.macros
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak

#3733 Fix troopCapacity return value
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  python/UniverseWrapper.cpp
Labels: category:bug, component:content scripting, component:internal

#3734 Fix potential array access out of bounds
  UI/GovernmentWnd.cpp
Labels: category:bug, component:internal

#3735 Fix return type of ship.colonyCapacity in python API
  python/UniverseWrapper.cpp
Labels: category:bug, component:AI

#3620 Fix timeout behaviour in ConnectToServer()
  client/ClientNetworking.cpp
Labels: category:bug, component:network

#3736 Add some more files to gitignore
  .gitignore
Labels: component:infrastructure, component:build system, category:tweak

#3739 Readd a fixed version of the species check
  default/python/AI/ColonisationAI.py
Labels: category:bug, component:AI

#3740 Minor fixes
  default/python/AI/ColonisationAI.py
  default/python/common/handlers.py
Labels: category:refactoring, component:AI

#3742 Avoid repeating playable species
  default/python/universe_generation/empires.py
Labels: component:content scripting, category:tweak

#3744 [AI] Ensure colony_buildes are initialized before usage
  default/python/AI/ColonisationAI.py
  default/python/AI/empire/colony_builders.py
  default/python/AI/freeorion_tools/lazy_initializer.py
  default/python/tests/AI/test_lazy_initializer.py
Labels: category:feature, component:AI

#3741 Let split_ship_from_fleet return INVALID_ID on failure
  client/AI/AIWrapper.cpp
  default/python/AI/AIFleetMission.py
  default/python/AI/FleetUtilsAI.py
Labels: category:refactoring, component:AI

#3749 Fix char sign definition in enums
  Empire/Diplomacy.h
  GG/GG/Base.h
  client/ClientNetworking.h
  network/Networking.h
  parse/ConditionParser.h
  universe/Conditions.h
  universe/EnumsFwd.h
  universe/ValueRef.h
  universe/ValueRefs.h
  util/Directories.cpp
  util/Enum.h
  util/GameRules.h
  util/Order.h
Labels: category:bug, component:internal, priority:high

#3751 Fix policy PROPAGANDA script
  default/scripting/policies/PROPAGANDA.focs.txt
Labels: category:bug, component:content scripting

#3746 Fix #3743
  client/ClientNetworking.cpp
Labels: category:bug, component:network

#3752 Bump dev-tools versions
  .github/workflows/python-format-check.yml
  .pre-commit-config.yaml
  default/python/AI/InvasionAI.py
  default/python/AI/PriorityAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/character/character_module.py
  default/python/requirements-dev.txt
  default/scripting/common/misc.py
Labels: category:refactoring, component:AI

#3750 Fix ScriptingContext in Tech::ResearchCost
  universe/Tech.cpp
Labels: category:bug, component:internal

#3755 Two fixes
  default/python/AI/ColonisationAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/empire/colony_builders.py
Labels: category:bug, component:AI

#3759 Fix Propaganda effect on enemies
  default/scripting/policies/PROPAGANDA.focs.txt
Labels: category:bug, component:content scripting

#3754 Improve AI invasion handling
  default/python/AI/AIFleetMission.py
  default/python/AI/InvasionAI.py
  default/python/AI/PriorityAI.py
  default/python/AI/fleet_orders.py
Labels: category:bug, component:AI

#3756 Small fixes and cosmetics for PolicyAI
  default/python/AI/PolicyAI.py
Labels: category:bug, component:AI, category:tweak

#3762 Move survey_universe to empire module and call it earlier
  default/python/AI/ColonisationAI.py
  default/python/AI/FreeOrionAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/empire/buildings_locations.py
  default/python/AI/empire/colony_builders.py
  default/python/AI/empire/colony_status.py
  default/python/AI/empire/growth_specials.py
  default/python/AI/empire/pilot_rating.py
  default/python/AI/empire/ship_builders.py
  default/python/AI/empire/survey_lock.py
  default/python/AI/empire/survey_universe.py
  default/python/AI/freeorion_tools/lazy_initializer.py
Labels: category:bug, component:AI

#3764 Simplify generate orders
  default/python/AI/FreeOrionAI.py
  default/python/AI/generate_orders.py
Labels: category:refactoring, component:AI

#3771 Enable tests in Ubuntu 21.04 docker
  .github/workflows/build-ubuntu-docker.yml
Labels: category:refactoring, component:infrastructure

#3748 Add game rule to allow repeated species
  default/python/universe_generation/empires.py
  default/scripting/game_rules.focs.py
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak
