Repository freeorion/freeorion, pull requests merged in 2022-01, with the labels that each got.

#3638 Improve Bureacracy SiteRep
  default/stringtables/en.txt
Labels: category:bug, component:art music text assets, category:tweak

#3639 Make stability penalties for shipyard dislikes work
  default/scripting/buildings/shipyards/ASTEROID.focs.txt
  default/scripting/buildings/shipyards/ASTEROID_REF.focs.txt
  default/scripting/buildings/shipyards/BASE.focs.txt
  default/scripting/buildings/shipyards/CON_ADV_ENGINE.focs.txt
  default/scripting/buildings/shipyards/CON_GEOINT.focs.txt
  default/scripting/buildings/shipyards/CON_NANOROBO.focs.txt
  default/scripting/buildings/shipyards/ENERGY_COMP.focs.txt
  default/scripting/buildings/shipyards/ENERGY_SOLAR.focs.txt
  default/scripting/buildings/shipyards/ORBITAL_DRYDOCK.focs.txt
  default/scripting/buildings/shipyards/ORGANIC_CEL_GRO.focs.txt
  default/scripting/buildings/shipyards/ORGANIC_ORB_INC.focs.txt
  default/scripting/buildings/shipyards/ORGANIC_XENO_FAC.focs.txt
Labels: category:bug, component:content scripting

#3640 Start with 20 IP
  default/python/universe_generation/empires.py
  server/ServerWrapper.cpp
Labels: category:feature, component:content scripting, category:tweak

#3644 - add few more names for ships (mainly mineralogy based)
  default/stringtables/en.txt
  default/stringtables/fr.txt
Labels: component:art music text assets, category:tweak

#3637 Fix inhabited/uninhabited french translation error
  default/stringtables/fr.txt
Labels: category:bug, component:translation

#3649 Asteroid Coating Special
  default/data/art/icons/specials_huge/asteroid_coating.png
  default/scripting/specials/ASTEROID_COATING.focs.txt
  default/scripting/specials/ASTEROID_COATING_OWNED.focs.txt
  default/stringtables/en.txt
Labels: category:feature, component:content scripting

#3655 Convert techs/construction/INTERSTELLAR_LOG.focs
  default/scripting/techs/construction/INTERSTELLAR_LOG.focs.py
  default/scripting/techs/construction/INTERSTELLAR_LOG.focs.txt
Labels: category:refactoring, component:content scripting, status:merged

#3645 Unown outposts with Chaos Wave bombardement weapon
  default/scripting/ship_parts/Bombard/SP_CHAOS_WAVE.focs.txt
  default/stringtables/en.txt
Labels: category:feature, component:content scripting, status:merged, priority:high

#3657 Add dump of tested tech to Boost.Test log
  test/parse/TestPythonParser.cpp
Labels: category:feature, status:merged, component:internal

#3653 Translate a few strings into spanish
  default/stringtables/es.txt
Labels: component:translation, category:tweak

#3648 adding number of settled worlds to census report
  UI/CensusBrowseWnd.cpp
  UI/CensusBrowseWnd.h
  UI/MapWnd.cpp
  default/stringtables/de.txt
  default/stringtables/en.txt
Labels: category:feature, component:UI

#3664 Update st-toot to format files inplace
  .github/workflows/string-tables-check.yml
  .pre-commit-config.yaml
  check/st-tool.py
Labels: category:refactoring, component:infrastructure

#3654 Convert techs/construction/FORCE_ENERGY_STRC.focs
  default/scripting/techs/construction/FORCE_ENERGY_STRC.focs.py
  default/scripting/techs/construction/FORCE_ENERGY_STRC.focs.txt
  default/scripting/tox.ini
  parse/ConditionPythonParser.cpp
  parse/EffectPythonParser.cpp
  parse/PythonParser.cpp
  parse/SourcePythonParser.cpp
  parse/SourcePythonParser.h
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, component:content scripting, component:internal

#3661 - add some german translations and correct one other
  default/stringtables/de.txt
Labels: component:translation, category:tweak

#3667 Add some more spanish translations
  default/stringtables/es.txt
Labels: component:translation, category:tweak

#3668 Detection Tweaks
  default/scripting/buildings/SCANNING_FACILITY.focs.txt
  default/scripting/ship_hulls/monster/SH_PSIONIC_SNOWFLAKE_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_SNOWFLAKE_1_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_SNOWFLAKE_2_BODY.focs.txt
  default/scripting/ship_hulls/monster/SH_SNOWFLAKE_3_BODY.focs.txt
  default/scripting/ship_hulls/organic/organic.macros
  default/scripting/techs/spy/DETECT_1.focs.txt
  default/scripting/techs/spy/DETECT_2.focs.txt
  default/scripting/techs/spy/DETECT_3.focs.txt
  default/scripting/techs/spy/DETECT_4.focs.txt
  default/scripting/techs/spy/DETECT_5.focs.txt
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak

#3670 Species likes/dislikes tweaks
  default/scripting/species/SP_ABADDONI.focs.txt
  default/scripting/species/SP_ETTY.focs.txt
  default/scripting/species/SP_EXOBOT.focs.txt
  default/scripting/species/SP_FULVER.focs.txt
  default/scripting/species/SP_GEORGE.focs.txt
  default/scripting/species/SP_KOBUNTURA.focs.txt
  default/scripting/species/SP_LAENFA.focs.txt
  default/scripting/species/SP_LEMBALALAM.focs.txt
  default/scripting/species/SP_MISIORLA.focs.txt
  default/scripting/species/SP_OURBOOLS.focs.txt
  default/scripting/species/SP_REPLICON.focs.txt
  default/scripting/species/SP_SILEXIAN.focs.txt
  default/scripting/species/SP_TRITH.focs.txt
  default/scripting/species/SP_VOLP.focs.txt
  test/system/TestChecksum.cpp
Labels: component:content scripting, category:tweak

#3669 Print address to console, exit service gracefully
  check/st-tool.py
Labels: component:infrastructure, category:tweak

#3658 Add missing fileds to Tech, EffectsGroup, and Named* dump
  universe/Effects.cpp
  universe/NamedValueRefManager.h
  universe/Tech.cpp
Labels: component:internal, category:tweak

#3674 Prevent enqueing multiple Regional Administration at same planet
  default/scripting/buildings/REGIONAL_ADMIN.focs.txt
Labels: component:content scripting, category:tweak

#3671 Some more translations into spanish
  default/stringtables/es.txt
Labels: component:translation, category:tweak

#3678 Updated info about provide at ArchLinux
  README.md
Labels: component:deployment, category:tweak

#3673 Update README.md
  README.md
Labels: category:bug, category:tweak, component:user manual

#3682 Provide IP address of logging player to Python API
  default/python/auth/auth.py
  server/ServerApp.cpp
  server/ServerApp.h
  server/ServerFSM.cpp
  server/ServerFramework.cpp
  server/ServerFramework.h
  server/ServerNetworking.cpp
  server/ServerNetworking.h
Labels: category:feature, component:network, status:merged

#3660 adding unicode glyph U+22C4 "Diamond Operator" to roboto font
  default/data/fonts/Roboto-Regular.ttf
Labels: component:art music text assets, category:tweak

#3680 Translate more strings into spanish
  default/stringtables/es.txt
Labels: component:translation, category:tweak
