Repository freeorion/freeorion, pull requests merged in 2022-12, with the labels that each got.

#4340 Fix Fleet Pathing
  universe/Fleet.cpp
Labels: category:bug, component:UI, component:internal, status:cherry-pick for release

#4339 Fix Godot Android setup on CI
  .github/workflows/build-android.yml
Labels: category:bug, component:infrastructure, status:merged, status:cherry-pick for release

#4341 fix CodeQL builds:
  .github/workflows/codeql-analysis.yml
Labels: component:infrastructure, component:build system, status:cherry-pick for release, category:tweak

#4343 Correct Self grav pedia entry
  default/stringtables/en.txt
Labels: status:merged, status:cherry-pick for release, component:art music text assets, category:tweak, component:user manual

#4321 Reuse old colony base hull for space flux composite hull
  default/data/art/hulls_design/space_flux_composite_hull.png
  default/data/art/icons/ship_hulls/space_flux_composite_hull_small.png
  default/scripting/ship_hulls/spatial_flux/SH_SPACE_FLUX_COMPOSITE.focs.txt
Labels: component:art music text assets, category:tweak

#4338 Changelog v0.5
  ChangeLog.md
Labels: status:cherry-pick for release, component:deployment, category:tweak, component:technical docs, component:user manual

#4347 Forgetting deleting safely
  universe/Universe.cpp
Labels: category:bug, component:internal, status:cherry-pick for release, priority:high

#4346 bump Python min version consistent with CMakeLists.txt
  BUILD.md
Labels: component:build system, status:cherry-pick for release, category:tweak, component:technical docs
