Repository freeorion/freeorion, pull requests merged in 2022-09, with the labels that each got.

#4112 [AI] Remove old planet rating code
  default/python/AI/ColonisationAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/colonization/__init__.py
  default/python/AI/colonization/calculate_planet_colonization_rating.py
  default/python/AI/colonization/colony_score.py
  default/python/AI/colonization/rate_pilots.py
  default/python/AI/empire/survey_universe.py
Labels: category:refactoring, component:AI

#4114 Add Android build to CI
  .github/workflows/build-android.yml
  util/Order.cpp
Labels: component:infrastructure, status:merged, component:internal, category:tweak

#4111 Add compare operations to Species
  universe/Species.cpp
  universe/Species.h
Labels: category:refactoring, status:merged, component:internal

#4109 Finish testing species parser with public methods
  test/parse/TestPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4121 Start equality test for species parser
  test/parse/TestPythonParser.cpp
Labels: status:merged, component:internal, category:tweak

#4122 Add constructor taking all parameters by rvalue reference to FocusType
  universe/Species.cpp
  universe/Species.h
Labels: status:merged, component:internal, category:tweak

#4126 Return Manjaro Linux to CI
  .github/workflows/build-docker.yml
Labels: component:infrastructure, status:merged, category:tweak

#4098 Use constexpr array for PlanetType to name matching
  universe/ValueRefs.cpp
  universe/ValueRefs.h
Labels: category:refactoring, component:internal

#4130 Add missing macros to Lambala'Lam
  default/scripting/species/SP_LEMBALALAM.focs.txt
Labels: category:bug, component:content scripting

#4123 Add focuses to test species
  test/parse/TestPythonParser.cpp
Labels: status:merged, component:internal, category:tweak

#4125 Provide python parser to species parser and make it synchronous
  parse/DummyParsers.cpp
  parse/Parse.h
  parse/SpeciesParser.cpp
  test/parse/TestPythonParser.cpp
  util/AppInterface.cpp
Labels: category:refactoring, status:merged, component:internal

#4131 Fix #1571: now simultaneous colonization fails
  util/Order.cpp
Labels: category:bug, component:network

#4104 Stabilitypage
  default/scripting/encyclopedia/game_concepts/species_traits/IDEPENDENT.focs.txt
  default/scripting/species/SP_FURTHEST.focs.txt
  default/scripting/species/SP_LAENFA.focs.txt
  default/scripting/species/SP_SLY.focs.txt
  default/stringtables/en.txt
Labels: category:feature, component:art music text assets, component:user manual

#4134 Use same StdAfx files for MSVC 2019 and 2022 Parsers projects
  msvc2019/Parsers/StdAfx.h
Labels: status:merged, component:internal, category:tweak

#4135 Add precompile headers to parsers project in CMake
  CMakeLists.txt
Labels: component:build system, category:tweak

#4133 Convert default/scripting/species/SpeciesCensusOrdering.focs
  default/scripting/species/SpeciesCensusOrdering.focs.py
  default/scripting/species/SpeciesCensusOrdering.focs.txt
  default/scripting/tox.ini
  parse/SpeciesParser.cpp
  test-scripting/species/SpeciesCensusOrdering.focs.py
  test-scripting/species/SpeciesCensusOrdering.focs.txt
  test-scripting/tox.ini
Labels: category:refactoring, component:content scripting, status:merged, component:internal

#4136 Rename condition Species to HasSpecies
  default/scripting/techs/construction/N_DIMEN_STRUCT.focs.py
  default/scripting/techs/construction/OUTPOST.focs.py
  default/scripting/techs/growth/ORBITAL_HAB.focs.py
  default/scripting/techs/growth/SUBTER_HAB.focs.py
  default/scripting/techs/production/GENERIC_SUPPLIES.focs.py
  default/scripting/techs/production/INTERSTELLAR_ENTANGLEMENT_FACTORY.focs.py
  default/scripting/techs/ship_hulls/SHP_GAL_EXPLO.focs.py
  default/scripting/tox.ini
  parse/ConditionPythonParser.cpp
  test-scripting/techs/growth/ORBITAL_HAB.focs.py
  test-scripting/tox.ini
Labels: category:refactoring, component:content scripting, status:merged, component:internal

#4139 Parse species name and descriptions
  parse/SpeciesParser.cpp
  test/parse/TestPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4128 Fix planet stealth tech cost
  default/scripting/techs/spy/STEALTH_1.focs.py
  default/scripting/techs/spy/STEALTH_2.focs.py
  default/scripting/techs/spy/STEALTH_3.focs.py
Labels: category:bug, component:content scripting, status:merged

#4138 Give translator a fixed cost
  default/scripting/buildings/TRANSLATOR.focs.txt
Labels: component:content scripting, category:tweak

#4141 Simplify stealth tech cost reduction, update pedia
  default/scripting/techs/spy/STEALTH_1.focs.py
  default/scripting/techs/spy/STEALTH_2.focs.py
  default/scripting/techs/spy/STEALTH_3.focs.py
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak, component:user manual

#4146 Add FocusType to available for Python FOCS parser types
  parse/PythonParser.cpp
Labels: status:merged, component:internal, category:tweak

#4142 SetPlanetType also sets original type during universe creation
  default/scripting/specials/planet/PHILOSOPHER.focs.txt
  parse/EffectParser2.cpp
  parse/EffectParser2.h
  parse/Tokens.h
  universe/Effects.cpp
  universe/Effects.h
Labels: category:bug, component:content scripting

#4145 Fix crash in processing turn due failed check for local connection
  server/ServerNetworking.cpp
  server/ServerNetworking.h
Labels: category:bug, component:network, status:merged, component:internal, priority:high

#4147 Parse focus types for species in Python FOCS parser
  parse/SpeciesParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4143 Reduce influence produced by terraforming policy
  default/scripting/policies/TERRAFORMING.focs.txt
Labels: component:content scripting, category:tweak

#4154 Add conditions Homeworld and HasSpecial
  parse/ConditionPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4156 Test build with MacOS 12
  .github/workflows/build-macos.yml
Labels: component:infrastructure, status:merged, category:tweak

#4157 Parse defaultfocus field in Python species FOCS parser
  parse/SpeciesParser.cpp
  test/parse/TestPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4153 Add comparison float < ValueRefDouble
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, status:merged, component:internal

#4158 Package MacOS build
  .github/workflows/build-macos.yml
Labels: component:infrastructure, status:merged, category:tweak

#4159 Rename Human condition to IsHuman in Python FOCS parser
  parse/ConditionPythonParser.cpp
Labels: status:merged, component:internal, category:tweak

#4160 Parse environments field in Python species FOCS parser
  parse/EnumPythonParser.h
  parse/PythonParser.cpp
  parse/SpeciesParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4163 Add name argument to HasSpecies condition in Python FOCS parser
  default/scripting/techs/construction/N_DIMEN_STRUCT.focs.py
  default/scripting/techs/construction/OUTPOST.focs.py
  default/scripting/techs/growth/ORBITAL_HAB.focs.py
  default/scripting/techs/growth/SUBTER_HAB.focs.py
  default/scripting/techs/production/GENERIC_SUPPLIES.focs.py
  default/scripting/techs/production/INTERSTELLAR_ENTANGLEMENT_FACTORY.focs.py
  default/scripting/techs/ship_hulls/SHP_GAL_EXPLO.focs.py
  parse/ConditionPythonParser.cpp
  test-scripting/techs/growth/ORBITAL_HAB.focs.py
Labels: category:refactoring, component:content scripting, status:merged, component:internal

#4162 Parse effectsgroups field in Python species FOCS parser
  parse/SpeciesParser.cpp
  universe/Species.cpp
  universe/Species.h
Labels: category:refactoring, status:merged, component:internal

#4116 Rework Xenophobic species and Racial Purity, with fading effect at de-adoption
  default/python/AI/PolicyAI.py
  default/python/AI/colonization/calculate_stability.py
  default/scripting/buildings/IMPERIAL_PALACE.focs.txt
  default/scripting/common/named_values.focs.txt
  default/scripting/policies/RACIAL_PURITY.focs.txt
  default/scripting/specials/RACIAL_PURITY_REMNANT.focs.txt
  default/scripting/specials/RACIAL_PURITY_SENTINEL.focs.txt
  default/scripting/species/SP_EAXAW.focs.txt
  default/scripting/species/SP_TRITH.focs.txt
  default/scripting/species/common/focus.macros
  default/scripting/species/common/xenophobic.macros
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak

#4164 Implement ResourceSupplyConnected and ~Source conditions in Python FOCS parser
  parse/ConditionPythonParser.cpp
  parse/PythonParser.cpp
  parse/SourcePythonParser.cpp
  parse/SourcePythonParser.h
Labels: category:refactoring, status:merged, component:internal

#4167 Accept constants in SetMeter effects
  parse/EffectPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4166 Start to return ValueRef::Operation instead of Condition::ValueTest in Python FOCS parser
  parse/PythonParser.cpp
  parse/SourcePythonParser.cpp
  parse/SourcePythonParser.h
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, status:merged, component:internal
