Repository freeorion/freeorion, pull requests merged in 2022-07, with the labels that each got.

#3931 Add NamedValues to Nebula, Ion Storm and Molecular Cloud for Pedia
  default/scripting/common/named_values.focs.txt
  default/scripting/fields/FLD_ION_STORM.focs.txt
  default/scripting/fields/FLD_MOLECULAR_CLOUD.focs.txt
  default/scripting/fields/FLD_NEBULA_1.focs.txt
  default/scripting/fields/FLD_NEBULA_2.focs.txt
  default/scripting/fields/FLD_NEBULA_3.focs.txt
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak

#3940 [AI] Impove chart view
  default/python/charting/file_reader.py
  default/python/charting/streamlite_app.py
Labels: component:infrastructure, category:tweak

#3887 Add dependencies data to HOST_* messages
  client/godot/GodotClientApp.cpp
  client/human/GGHumanClientApp.cpp
  msvc2019/Test/Test.vcxproj
  msvc2019/Test/Test.vcxproj.filters
  msvc2022/Test/Test.vcxproj
  msvc2022/Test/Test.vcxproj.filters
  network/Message.cpp
  network/Message.h
  server/ServerFSM.cpp
  test/system/CMakeLists.txt
  test/system/ClientAppFixture.cpp
Labels: category:feature, component:network

#3941 fix a typo
  default/python/AI/ShipDesignAI.py
Labels: component:AI, category:tweak

#3939 calculate research and stability, tech_soon_available
  default/python/AI/colonization/calculate_production.py
  default/python/AI/colonization/calculate_research.py
  default/python/AI/colonization/calculate_stability.py
  default/python/AI/colonization/colony_score.py
  default/python/AI/freeorion_tools/__init__.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
Labels: category:refactoring, component:AI

#3944 Avoid division by zero
  default/python/AI/PolicyAI.py
Labels: category:bug, component:AI

#3943 Update skeleton generator
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/handlers/shared_instances_code.py
  default/python/stub_generator/stub_generator/argument_name_generator.py
  default/python/stub_generator/stub_generator/class_generator.py
Labels: category:refactoring, component:infrastructure

#3621 Buff population growth to thirdway where it was before
  default/scripting/species/common/population.macros
Labels: component:content scripting, category:tweak

#3945 Removed some unused interface functions
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  python/EmpireWrapper.cpp
Labels: category:refactoring, component:AI

#3948 [AI] Fix building iteration
  default/python/AI/buildings.py
  default/python/AI/colonization/calculate_stability.py
Labels: category:bug, component:AI

#3950 Add unique name for binary artefact
  .github/workflows/build-windows.yml
Labels: component:infrastructure, category:tweak

#3954 adding cmake build directory to .gitignore on Windows(VS Code)
  .gitignore
Labels: category:bug, component:infrastructure, component:build system

#3952 Rework species tags
  default/python/AI/EspionageAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/PolicyAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/colonization/calculate_influence.py
  default/python/AI/colonization/calculate_planet_colonization_rating.py
  default/python/AI/colonization/calculate_population.py
  default/python/AI/colonization/calculate_production.py
  default/python/AI/colonization/calculate_research.py
  default/python/AI/colonization/calculate_stability.py
  default/python/AI/colonization/rate_pilots.py
  default/python/AI/freeorion_tools/__init__.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
Labels: component:AI, category:tweak

#3965 Set proper return type in skeleton generator
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/stub_generator/class_generator.py
Labels: component:infrastructure, category:tweak

#3951 Fix artefact name
  .github/workflows/build-windows.yml
Labels: category:bug, component:infrastructure

#3955 Convert default/scripting/techs/production/ROBOTIC_PROD.focs
  default/scripting/techs/production/ROBOTIC_PROD.focs.py
  default/scripting/techs/production/ROBOTIC_PROD.focs.txt
Labels: category:refactoring, component:content scripting, status:merged

#3966 Use forgotten supply factor
  default/python/AI/colonization/calculate_planet_colonization_rating.py
Labels: category:bug, component:AI

#3968 Give white krakens a tentacle attack
  default/scripting/monster_designs/SM_WHITE_KRAKEN.focs.txt
Labels: component:content scripting, category:tweak

#3971 [AI] Simplify production orders
  default/python/AI/ProductionAI.py
Labels: category:refactoring, component:AI

#3946 Tech short desc
  default/scripting/techs/construction/ARCH_PSYCH.focs.py
  default/scripting/techs/construction/TRANSCEND_ARCH.focs.py
  default/scripting/techs/growth/NANOTECH_MED.focs.py
  default/scripting/techs/growth/TRANSORG_SENT.focs.py
  default/scripting/techs/learning/DISTRIB_THOUGHT.focs.py
  default/scripting/techs/learning/EVERYTHING.focs.py
  default/scripting/techs/learning/MIND_VOID.focs.py
  default/scripting/techs/learning/PSIONICS.focs.py
  default/scripting/techs/learning/TRANSLING_THOUGHT.focs.py
  default/scripting/techs/production/SENTIENT_AUTOMATION.focs.py
  default/scripting/techs/ship_hulls/SHP_GAL_EXPLO.focs.txt
  default/stringtables/en.txt
Labels: category:bug, component:art music text assets

#3969 Small pedia fixes
  default/scripting/encyclopedia/game_concepts/species_traits/SNEAKY.focs.txt
  default/scripting/species/SP_LAENFA.focs.txt
  default/stringtables/en.txt
Labels: category:bug, component:art music text assets

#3975 [AI] cleanup production 3
  default/python/AI/ProductionAI.py
Labels: category:refactoring, component:AI

#3970 Convert default/scripting/techs/ship_hulls/SHP_GAL_EXPLO.focs
  default/scripting/species/common/population.py
  default/scripting/techs/ship_hulls/SHP_GAL_EXPLO.focs.py
  default/scripting/techs/ship_hulls/SHP_GAL_EXPLO.focs.txt
  default/scripting/tox.ini
  parse/ConditionPythonParser.cpp
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
  universe/Conditions.cpp
  universe/Conditions.h
Labels: category:refactoring, component:content scripting, status:merged, component:internal

#3983 Convert default/scripting/techs/ship_hulls/SHP_XENTRONIUM_HULL.focs
  default/scripting/techs/construction/ARCH_MONOFIL.focs.py
  default/scripting/techs/construction/ARCH_PSYCH.focs.py
  default/scripting/techs/construction/ART_HEAVEN.focs.py
  default/scripting/techs/construction/ART_PLANET.focs.py
  default/scripting/techs/construction/CONC_CAMP.focs.py
  default/scripting/techs/construction/INTERSTELLAR_LOG.focs.py
  default/scripting/techs/construction/ORGANIC_STRUCT.focs.py
  default/scripting/techs/construction/OUTPOST.focs.py
  default/scripting/techs/construction/PLANET_DRIVE.focs.py
  default/scripting/techs/construction/STARGATE.focs.py
  default/scripting/techs/construction/TRANSCEND_ARCH.focs.py
  default/scripting/techs/defense/Defense.focs.py
  default/scripting/techs/defense/Garrison.focs.py
  default/scripting/techs/growth/BIOTERROR.focs.py
  default/scripting/techs/growth/GAIA_TRANS.focs.py
  default/scripting/techs/growth/GENETIC_MED.focs.py
  default/scripting/techs/growth/LIFECYCLE_MAN.focs.py
  default/scripting/techs/growth/MEGA_ECO.focs.py
  default/scripting/techs/growth/NANOTECH_MED.focs.py
  default/scripting/techs/growth/NANO_CYBERNET.focs.py
  default/scripting/techs/growth/SYMBIOTIC_BIO.focs.py
  default/scripting/techs/growth/TERRAFORM.focs.py
  default/scripting/techs/growth/TRANSORG_SENT.focs.py
  default/scripting/techs/learning/ALGO_ELEGANCE.focs.py
  default/scripting/techs/learning/ART_BLACK_HOLE.focs.py
  default/scripting/techs/learning/COLLAPSER.focs.py
  default/scripting/techs/learning/ENCLAVE_VOID.focs.py
  default/scripting/techs/learning/EVERYTHING.focs.py
  default/scripting/techs/learning/FORCE_FIELD.focs.py
  default/scripting/techs/learning/GATEWAY_VOID.focs.py
  default/scripting/techs/learning/GRAVITONICS.focs.py
  default/scripting/techs/learning/MIND_VOID.focs.py
  default/scripting/techs/learning/PHYSICAL_BRAIN.focs.py
  default/scripting/techs/learning/PSIONICS.focs.py
  default/scripting/techs/learning/SPATIAL_DISTORT_GEN.focs.py
  default/scripting/techs/learning/TEMPORAL_MECH.focs.py
  default/scripting/techs/learning/TRANSLING_THOUGHT.focs.py
  default/scripting/techs/learning/UNIFIED_CONC.focs.py
  default/scripting/techs/learning/XENO_ARCH.focs.py
  default/scripting/techs/production/EXOBOTS.focs.py
  default/scripting/techs/production/INDUSTRY_CENTER_I.focs.py
  default/scripting/techs/production/INTERSTELLAR_ENTANGLEMENT_FACTORY.focs.py
  default/scripting/techs/production/NEUTRONIUM_EXTRACTION.focs.py
  default/scripting/techs/production/N_DIM_ASSEM.focs.py
  default/scripting/techs/production/ORBITAL_GEN.focs.py
  default/scripting/techs/production/SINGULAR_GEN.focs.py
  default/scripting/techs/production/SOLAR_ORB_GEN.focs.py
  default/scripting/techs/production/TRANS_DESIGN.focs.py
  default/scripting/techs/production/VOID_PREDICTION.focs.py
  default/scripting/techs/ship_hulls/SHP_GAL_EXPLO.focs.py
  default/scripting/techs/ship_hulls/SHP_XENTRONIUM_HULL.focs.py
  default/scripting/techs/ship_hulls/SHP_XENTRONIUM_HULL.focs.txt
  default/scripting/tox.ini
  parse/EffectPythonParser.cpp
  parse/EnumPythonParser.cpp
  test-scripting/techs/learning/ALGO_ELEGANCE.focs.py
  test-scripting/tox.ini
Labels: category:refactoring, component:content scripting, component:internal

#3979 Shieldtrait
  default/scripting/species/SP_ACIREMA.focs.txt
  default/scripting/species/SP_CHATO.focs.txt
  default/scripting/species/SP_EXOBOT.focs.txt
  default/scripting/species/SP_TRITH.focs.txt
  default/scripting/species/common/shields.macros
  default/stringtables/en.txt
Labels: category:feature, component:content scripting

#3990 Apply SPATIAL_FLUX_STEALTH_TECH_BONUS boost for all stealth tech upgrades
  default/scripting/ship_hulls/spatial_flux/spatial_flux.macros
Labels: category:bug, component:content scripting

#3988 Add Game rule for minimum monster starting distance
  default/scripting/common/misc.macros
  default/scripting/common/named_values.focs.txt
  default/scripting/game_rules.focs.py
  default/scripting/monster_fleets.inf
  default/scripting/specials/ASTEROID_COATING.focs.txt
  default/scripting/specials/planet/ANCIENT_RUINS.focs.txt
  default/scripting/specials/planet/FORTRESS.focs.txt
  default/scripting/specials/planet/GAIA.focs.txt
  default/scripting/specials/planet/HONEYCOMB.focs.txt
  default/scripting/specials/planet/PANOPTICON.focs.txt
  default/scripting/specials/planet/monster_guard.macros
  default/scripting/specials/planet/monster_nest/JUGGERNAUT_NEST.focs.txt
  default/scripting/specials/planet/monster_nest/KRAKEN_NEST.focs.txt
  default/scripting/specials/planet/monster_nest/SNOWFLAKE_NEST.focs.txt
  default/scripting/species/SP_BEIGEGOO.focs.txt
  default/scripting/species/SP_FIFTYSEVEN.focs.txt
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak

#3989 Rename fighter tech label to numeric (instead Laser, Plasma,… Fighters)
  default/stringtables/en.txt
Labels: component:art music text assets, category:tweak

#3987 Add NamedString and NamedStringLookup for FOCS
  parse/NamedValueRefParser.cpp
  parse/StringValueRefParser.cpp
  parse/ValueRefParser.h
  universe/NamedValueRefManager.cpp
Labels: category:feature, component:internal

#3997 remove unused string that was removed from en.txt
  default/stringtables/fr.txt
Labels: category:bug, component:art music text assets

#3994 Block enqueuing more than one of any colony building on a planet
  default/scripting/buildings/colonies/SP_ABADDONI.focs.txt
  default/scripting/buildings/colonies/SP_BANFORO.focs.txt
  default/scripting/buildings/colonies/SP_CHATO.focs.txt
  default/scripting/buildings/colonies/SP_CRAY.focs.txt
  default/scripting/buildings/colonies/SP_DERTHREAN.focs.txt
  default/scripting/buildings/colonies/SP_EAXAW.focs.txt
  default/scripting/buildings/colonies/SP_EGASSEM.focs.txt
  default/scripting/buildings/colonies/SP_ETTY.focs.txt
  default/scripting/buildings/colonies/SP_EXOBOT.focs.txt
  default/scripting/buildings/colonies/SP_FULVER.focs.txt
  default/scripting/buildings/colonies/SP_FURTHEST.focs.txt
  default/scripting/buildings/colonies/SP_GEORGE.focs.txt
  default/scripting/buildings/colonies/SP_GYSACHE.focs.txt
  default/scripting/buildings/colonies/SP_HAPPY.focs.txt
  default/scripting/buildings/colonies/SP_HHHOH.focs.txt
  default/scripting/buildings/colonies/SP_HUMAN.focs.txt
  default/scripting/buildings/colonies/SP_KILANDOW.focs.txt
  default/scripting/buildings/colonies/SP_KOBUNTURA.focs.txt
  default/scripting/buildings/colonies/SP_LAENFA.focs.txt
  default/scripting/buildings/colonies/SP_MISIORLA.focs.txt
  default/scripting/buildings/colonies/SP_MUURSH.focs.txt
  default/scripting/buildings/colonies/SP_PHINNERT.focs.txt
  default/scripting/buildings/colonies/SP_REPLICON.focs.txt
  default/scripting/buildings/colonies/SP_SCYLIOR.focs.txt
  default/scripting/buildings/colonies/SP_SETINON.focs.txt
  default/scripting/buildings/colonies/SP_SILEXIAN.focs.txt
  default/scripting/buildings/colonies/SP_SLY.focs.txt
  default/scripting/buildings/colonies/SP_SSLITH.focs.txt
  default/scripting/buildings/colonies/SP_SUPER_TEST.focs.txt
  default/scripting/buildings/colonies/SP_TAEGHIRUS.focs.txt
  default/scripting/buildings/colonies/SP_TRITH.focs.txt
  default/scripting/buildings/colonies/SP_UGMORS.focs.txt
  default/scripting/buildings/colonies/col_bld_gen.py
Labels: component:content scripting, category:tweak

#3999 [AI] adaption for new species shield traits
  default/python/AI/AIDependencies.py
  default/python/AI/CombatRatingsAI/__init__.py
  default/python/AI/CombatRatingsAI/_ratings.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/colonization/rate_pilots.py
  default/python/AI/freeorion_tools/__init__.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
Labels: category:feature, component:AI

#4001 Use other brackets for *Cast type information
  universe/ValueRefs.h
Labels: category:bug, component:UI, status:merged, priority:high

#4000 Change docker test ubuntu version to 22.10
  .github/ubuntu-22.10/Dockerfile
  .github/workflows/build-docker.yml
Labels: component:infrastructure, status:merged, category:tweak

#4003 [AI] annotations
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/common/fo_typing.py
Labels: component:AI, category:tweak

#4002 Adapt AI for no longer parallel colony buildings
  default/python/AI/ProductionAI.py
Labels: component:AI, category:tweak

#4006 Test Ubuntu Kinetic build with gcc-12
  .github/ubuntu-22.10/Dockerfile
  .github/workflows/build-docker.yml
Labels: component:infrastructure, status:merged, category:tweak

#4004 Raise MacOS version in CI to 11
  .github/workflows/build-macos.yml
Labels: component:infrastructure, status:merged, category:tweak

#4009 Convert default/scripting/techs/ship_parts/damage_control/SHP_ADV_DAM_CONT.focs
  default/scripting/techs/ship_parts/damage_control/SHP_ADV_DAM_CONT.focs.py
  default/scripting/techs/ship_parts/damage_control/SHP_ADV_DAM_CONT.focs.txt
  default/scripting/tox.ini
  parse/ConditionPythonParser.cpp
  parse/PythonParser.cpp
  parse/SourcePythonParser.cpp
  parse/SourcePythonParser.h
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, component:content scripting, status:merged, component:internal

#4010 Convert default/scripting/techs/ship_parts/damage_control/SHP_BASIC_DAM_CONT.focs
  default/scripting/techs/ship_parts/damage_control/SHP_BASIC_DAM_CONT.focs.py
  default/scripting/techs/ship_parts/damage_control/SHP_BASIC_DAM_CONT.focs.txt
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, component:content scripting, status:merged, component:internal

#4011 Convert default/scripting/techs/ship_parts/damage_control/SHP_FLEET_REPAIR.focs
  default/scripting/techs/ship_parts/damage_control/SHP_FLEET_REPAIR.focs.py
  default/scripting/techs/ship_parts/damage_control/SHP_FLEET_REPAIR.focs.txt
  default/scripting/tox.ini
  parse/ConditionPythonParser.cpp
  parse/EnumPythonParser.cpp
Labels: category:refactoring, component:content scripting, status:merged, component:internal

#4015 Convert default/scripting/techs/ship_parts/damage_control/SHP_REINFORCED_HULL.focs
  default/scripting/techs/ship_parts/damage_control/SHP_REINFORCED_HULL.focs.py
  default/scripting/techs/ship_parts/damage_control/SHP_REINFORCED_HULL.focs.txt
  default/scripting/tox.ini
Labels: category:refactoring, component:content scripting, status:merged

#4014 rename building type base class and use it for annotation
  default/python/AI/ProductionAI.py
  default/python/AI/buildings.py
Labels: category:refactoring, component:AI

#4016 Convert default/scripting/techs/ship_parts/fuel/SHP_ANTIMATTER_TANK.focs
  default/scripting/techs/ship_parts/fuel/SHP_ANTIMATTER_TANK.focs.py
  default/scripting/techs/ship_parts/fuel/SHP_ANTIMATTER_TANK.focs.txt
  default/scripting/techs/ship_parts/fuel/fuel.py
  default/scripting/tox.ini
  parse/ConditionPythonParser.cpp
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, component:content scripting, status:merged, component:internal

#4012 Fix description of great/ult. shields
  default/scripting/species/common/shields.macros
Labels: category:bug, component:content scripting

#4013 Fix check for available slots
  default/python/AI/PolicyAI.py
Labels: category:bug, component:AI

#3978 Use multipage layout
  default/python/charting/collect_data.py
  default/python/charting/file_reader.py
  default/python/charting/pages/01_policies.py
  default/python/charting/requirements_charts.txt
  default/python/charting/streamlite_app.py
  default/python/charting/widgets.py
Labels: component:infrastructure, category:tweak
