Repository freeorion/freeorion, pull requests merged in 2022-10, with the labels that each got.

#4168 Test script changes in CI
  .github/workflows/build-docker.yml
Labels: component:infrastructure, status:merged, category:tweak

#4096 Rework Replicon
  default/scripting/encyclopedia/game_concepts/species_traits/ADAPTIVE.focs.txt
  default/scripting/species/SP_REPLICON.focs.txt
  default/scripting/species/common/happiness.macros
  default/scripting/species/common/population.macros
  default/scripting/techs/growth/SYMBIOTIC_BIO.focs.py
  default/scripting/techs/growth/XENO_GENETICS.focs.py
  default/scripting/techs/growth/XENO_HYBRIDS.focs.py
  default/stringtables/en.txt
Labels: category:refactoring, component:content scripting

#4165 [AI] Played with patch and mock to add some more tests
  default/python/tests/AI/test_system_network.py
Labels: component:AI, category:tweak

#4172 [AI] Bump development tools versions
  .pre-commit-config.yaml
  cmake/make_versioncpp.py
  default/python/requirements-dev.txt
Labels: component:infrastructure, category:tweak

#4171 Fix imports to avoid crashes during test collection
  default/python/charting/test_tokenizer.py
Labels: category:bug, component:infrastructure

#4173 Add SetStarType effect and ValueRefDouble/float operator
  parse/EffectPythonParser.cpp
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, status:merged, component:internal

#4175 Change operator < to return value test instead of condition
  parse/ConditionPythonParser.cpp
  parse/ConditionPythonParser.h
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, status:merged, component:internal

#4176 Try to move shared code to actions
  .github/actions/flake8-lint/action.yml
  .github/workflows/python-check.yml
Labels: component:deployment, category:tweak

#4177 Bump actions and restricts some build runs
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu.yml
  .github/workflows/build-windows-msvs.yml
  .github/workflows/build-windows.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/godot-check.yml
  .github/workflows/project-labeler.yml
  .github/workflows/python-check.yml
  .github/workflows/python-format-check.yml
  .github/workflows/snapcraft.yml
  .github/workflows/string-tables-check.yml
Labels: component:deployment, category:tweak

#4170 Move string tables docs
  check/README.md
  default/stringtables/README.md
Labels: category:tweak, component:technical docs

#4179 [CI] Add skip for isort to speed it up
  pyproject.toml
Labels: component:deployment, category:tweak

#4181 Add WithinStarlaneJumps condition and value ref operators
  parse/ConditionPythonParser.cpp
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, status:merged, component:internal

#4178 Fix inconsistant tags
  default/scripting/species/SP_FIFTYSEVEN.focs.txt
  default/scripting/species/SP_LAENFA.focs.txt
Labels: category:bug, component:content scripting

#4182 Autodeploy MacOS installer to SorceForge
  .github/workflows/build-macos.yml
Labels: component:infrastructure, status:merged, category:tweak

#4184 Implement MoveTo effect in Python FOCS parser
  parse/EffectPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4187 Add WithinDistance condition to Python FOCS parser
  parse/ConditionPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4189 Add Object condition, MoveTowards effect, and non equal operation
  parse/ConditionPythonParser.cpp
  parse/EffectPythonParser.cpp
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, status:merged, component:internal

#4183 Pedia tweaks
  default/stringtables/en.txt
Labels: category:tweak, component:user manual

#4185 [AI] Move unused code to special function
  default/python/AI/ResearchAI.py
Labels: category:refactoring, component:AI

#4197 [AI] Text cleanup and code folding removal
  default/python/AI/ProductionAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/empire/survey_universe.py
Labels: category:refactoring, component:AI

#4180 Extract cmake build to action
  .github/actions/cmake-build/action.yml
  .github/workflows/build-windows.yml
Labels: status:work in progress, component:infrastructure, category:tweak

#4198 Test build of godot client in docker CI
  .github/manjaro/Dockerfile
  .github/workflows/build-docker.yml
Labels: component:infrastructure, status:merged, category:tweak

#4174 Extract tech queue header check
  default/python/AI/ResearchAI.py
Labels: category:refactoring, component:AI

#4199 Detect godot executable in Dockerized CI
  .github/fedora-32/Dockerfile
  .github/fedora-rawhide/Dockerfile
  .github/godot-detect.cmake
  .github/workflows/build-docker.yml
Labels: component:infrastructure, status:merged, category:tweak

#4201 Strip Android libraries before packaging
  CMakeLists.txt
  godot/freeoriongodot.gdnlib
Labels: component:build system, status:merged, category:tweak

#4200 Remove use of std::function in Python FOCS parser
  parse/GameRulesParser.cpp
  parse/SpeciesParser.cpp
  parse/TechsParser.cpp
  parse/ValueRefPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4202 Run godot unit tests in dockerized CI
  .github/workflows/build-docker.yml
Labels: component:infrastructure, category:tweak

#4137 [AI] Add option to use conformance
  default/python/AI/PlanetUtilsAI.py
  default/python/AI/PolicyAI.py
Labels: category:feature, component:AI

#4206 Fix meter rounding issues
  universe/Meter.h
Labels: category:bug, component:game mechanic

#4192 Fix doc in EffectParser1
  parse/EffectParser1.cpp
Labels: status:merged, component:internal, category:tweak

#4207 Add more checks for Godot unit tests
  .github/workflows/build-docker.yml
  .github/workflows/build-ubuntu.yml
  godot/test/integration/test_quickstart.gd
Labels: component:infrastructure, status:merged, category:tweak, component:godot-client

#4203 [CI] Add windows artefact building on master branch
  .github/workflows/build-windows.yml
Labels: component:infrastructure, category:tweak

#4209 [AI] Update skeleton generator doc parser
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/stub_generator/parse_docs.py
  default/python/stub_generator/test_docs.py
Labels: category:refactoring, component:infrastructure

#4210 [CI] Fix upload artefact name
  .github/workflows/build-windows.yml
Labels: category:bug, component:infrastructure

#4188 Grooming mostly
  default/scripting/monster_designs/SM_SNOWFLAKE_1.focs.txt
  default/scripting/monster_designs/SM_SNOWFLAKE_2.focs.txt
  default/scripting/monster_designs/SM_SNOWFLAKE_3.focs.txt
Labels: category:bug, category:feature, component:game mechanic, component:internal, category:tweak

#4211 Run Godot unit tests on Manjaro with Xvfb
  .github/manjaro/Dockerfile
  .github/workflows/build-docker.yml
  CMakeLists.txt
  client/godot/FreeOrionNode.cpp
  client/godot/FreeOrionNode.h
  godot/FreeOrionClient.gd
  godot/test/integration/test_quickstart.gd
Labels: component:infrastructure, category:tweak, component:godot-client

#4213 Use separate job to generate godot API for Android CI
  .github/workflows/build-android.yml
Labels: component:infrastructure, status:merged, category:tweak

#4216 Improve return type fo AI skeletons
  default/python/AI/freeOrionAIInterface.pyi
  default/python/common/fo_typing.py
  default/python/freeorion.pyi
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/stub_generator/class_generator.py
  default/python/stub_generator/stub_generator/function_generator.py
  default/python/stub_generator/stub_generator/rtype/__init__.py
  default/python/stub_generator/stub_generator/rtype/_base_rtype_mapping.py
  default/python/stub_generator/stub_generator/rtype/_function_mapping.py
  default/python/stub_generator/stub_generator/rtype/_method_mapping.py
  default/python/stub_generator/stub_generator/rtype/_property_mapping.py
  default/python/stub_generator/stub_generator/rtype/test_rtype.py
Labels: component:infrastructure, category:tweak

#4220 Fix timeout when generate Godot API file
  .github/workflows/build-android.yml
Labels: component:infrastructure, status:merged, category:tweak

#4193 Generate NSIS installer for Windows
  .github/workflows/build-windows-msvs.yml
Labels: category:feature, component:infrastructure, status:merged

#4223 Move effects checks to last at species parser test
  test/parse/TestPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4225 Implement remaining fields in species Python FOCS parser
  parse/SpeciesParser.cpp
  test/parse/TestPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4195 Add supply war info to METER_SUPPLY_VALUE_DESC
  default/stringtables/en.txt
Labels: component:art music text assets, category:tweak, component:user manual

#4227 [AI] Update skeleton genration to set proper rtype for Mapping
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/stub_generator/rtype/__init__.py
  default/python/stub_generator/stub_generator/rtype/_base_rtype_mapping.py
  default/python/stub_generator/stub_generator/rtype/_mapping_code.py
  default/python/stub_generator/stub_generator/rtype/test_rtype.py
Labels: category:bug, component:infrastructure

#4234 [AI] Update Set and Vec type hints
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/stub_generator/rtype/_base_rtype_mapping.py
  default/python/stub_generator/stub_generator/rtype/_function_mapping.py
  default/python/stub_generator/stub_generator/rtype/_mapping_code.py
  default/python/stub_generator/stub_generator/rtype/_method_mapping.py
  default/python/stub_generator/stub_generator/rtype/_property_mapping.py
  default/python/stub_generator/stub_generator/rtype/test_rtype.py
Labels: category:refactoring, component:infrastructure

#4232 Refactor comparison operators in Python FOCS parser
  parse/ConditionPythonParser.cpp
  parse/ConditionPythonParser.h
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, status:merged, component:internal

#4236 Add operand 'float' + 'ValueRefInt'
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: status:merged, component:internal, category:tweak

#4186 [CI] Enable complexity check for the Python code.
  check/checkSpeciesTags.py
  check/st-tool.py
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/ColonisationAI.py
  default/python/AI/CombatRatingsAI/_ship_combat_stats.py
  default/python/AI/DiplomaticCorp.py
  default/python/AI/ExplorationAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/PlanetUtilsAI.py
  default/python/AI/PolicyAI.py
  default/python/AI/PriorityAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/colonization/calculate_population.py
  default/python/AI/empire/survey_universe.py
  default/python/AI/fleet_orders.py
  default/python/AI/pathfinding.py
  default/python/AI/savegame_codec/_decoder.py
  default/python/AI/turn_state/_empire_resources.py
  default/python/requirements-dev.txt
  default/python/stub_generator/parse_docs.py
  default/python/stub_generator/stub_generator/class_generator.py
  default/python/tox.ini
  default/python/universe_generation/empires.py
  default/python/universe_generation/galaxy.py
  default/python/universe_generation/monsters.py
  default/python/universe_generation/natives.py
  default/python/universe_generation/specials.py
  default/python/universe_generation/starnames.py
  default/python/universe_generation/teams.py
  default/python/universe_generation/universe_generator.py
  doc/tag_parser.py
Labels: component:infrastructure, category:tweak

#4237 Remove coping globals from parsed Python files
  parse/PythonParser.cpp
  parse/PythonParser.h
Labels: category:refactoring, component:internal

#4243 Move FocusType to use in imports and implement EmpireStockpile in Python FOCS parser
  parse/EffectPythonParser.cpp
  parse/EnumPythonParser.cpp
  parse/PythonParser.cpp
  parse/SpeciesParser.cpp
  parse/ValueRefPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4238 [AI] Remove excluded policies from social options
  default/python/AI/PolicyAI.py
Labels: category:bug, component:AI

#4246 Add test species dump and unlock item effect
  parse/EffectPythonParser.cpp
  test/parse/TestPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4247 Add SetPlanetSize, NoEffect effects, None as None condition, operation != for int
  parse/EffectPythonParser.cpp
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
  test/system/TestChecksum.cpp
Labels: category:refactoring, component:internal

#4245 [AI] Minor fixes
  default/python/AI/EnumsAI.py
  default/python/AI/colonization/calculate_research.py
Labels: category:bug, component:AI

#4221 Fix species modifier for Troop Techs
  default/scripting/techs/defense/Garrison.focs.py
Labels: category:bug, component:content scripting

#4099 Clarify some policy bonuses in pedia
  default/scripting/policies/EXPLORATION.focs.txt
  default/stringtables/en.txt
Labels: category:tweak, component:user manual

#4258 Update tests to be compatiable with Python3.10 on Ubuntu
  default/python/tests/AI/test_debug_chat.py
Labels: category:bug, component:AI, status:merged

#4248 Tweak stealth and distance to empire of kraken in the ice special
  default/scripting/specials/planet/KRAKEN_IN_THE_ICE.focs.txt
Labels: component:content scripting, category:tweak

#4226 Make it possible to hide the kraken nests from turn 1 und 2
  default/scripting/specials/planet/monster_guard.macros
Labels: category:bug, component:content scripting

#4222 Tweak Hyperspatial Dam
  default/scripting/buildings/HYPER_DAM.focs.txt
Labels: component:content scripting, category:tweak

#4255 Add More Named values for pedia
  default/scripting/specials/planet/FORTRESS.focs.txt
  default/scripting/techs/defense/BarrierShield.focs.py
  default/scripting/techs/learning/FORCE_FIELD.focs.py
  default/stringtables/en.txt
Labels: component:content scripting, component:art music text assets, category:tweak, component:user manual

#4266 [AI] Update skeletons to recent changes
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/stub_generator/stub_generator/rtype/_base_rtype_mapping.py
  default/python/stub_generator/stub_generator/rtype/test_rtype.py
Labels: component:infrastructure, category:tweak

#4267 [AI] Remove rating of continuous scanning, since it has been nerfed
  default/python/AI/PolicyAI.py
Labels: component:AI, category:tweak

#4268 Remove fuel rounding hacks since meters use fixed point arithmetics
  default/scripting/ship_hulls/organic/organic.macros
  default/scripting/ship_hulls/ship_hulls.macros
Labels: component:content scripting, category:tweak

#4263 Pedia: PLC_CHECKPOINTS does not change supply anymore
  default/stringtables/en.txt
  default/stringtables/fr.txt
Labels: category:bug, component:art music text assets, category:tweak, component:user manual

#4261 Do not add more evacuees than sending planet's population
  default/scripting/buildings/EVACUATION.focs.txt
Labels: category:bug, component:content scripting

#4264 Add supply traversals for borders for common allies of both suppliers
  Empire/Supply.cpp
Labels: component:game mechanic, category:tweak

#4273 Set diplomatic status from Python API
  server/ServerWrapper.cpp
Labels: category:feature, component:internal, priority:high

#4274 Fix policy evaluation of AI charts
  default/python/charting/pages/01_policies.py
Labels: category:bug

#4281 [AI] Fix focus_stability_effects
  default/python/AI/PlanetUtilsAI.py
Labels: category:bug, component:AI

#4290 tweak exobot productivity stringtable entry
  default/stringtables/en.txt
Labels: category:bug, component:content scripting

#4272 Fix alliance victory if diplomacy is forbidden
  server/ServerApp.cpp
Labels: category:bug, component:game mechanic, status:merged, priority:high
