Repository freeorion/freeorion, pull requests merged in 2023-10, with the labels that each got.

#4760 Fix deprecated Ubuntu in CI
  .github/ubuntu-23.04/Dockerfile
  .github/workflows/_build-docker.yml
Labels: category:bug, component:infrastructure, status:merged, status:cherry-pick for release, priority:high

#4758 Enable CMAKE_CXX_EXTENSIONS
  CMakeLists.txt
  GG/CMakeLists.txt
Labels: category:bug, component:build system, component:internal

#4700 Test Debian sid i386 on CI
  .github/debian-sid-i386/Dockerfile
  .github/workflows/_build-docker.yml
Labels: component:infrastructure, status:merged, status:cherry-pick for release, category:tweak

#4757 Tweaks
  Empire/Empire.h
  Empire/ProductionQueue.h
  GG/GG/Clr.h
  GG/GG/Flags.h
  GG/GG/Font.h
  GG/GG/PtRect.h
  GG/GG/StrongTypedef.h
  GG/GG/UnicodeCharsets.h
  GG/src/Font.cpp
  network/Message.cpp
  network/Message.h
  parse/EnumPythonParser.h
  universe/BuildingType.h
  universe/Condition.h
  universe/Effect.cpp
  universe/Effect.h
  universe/FieldType.h
  universe/Meter.h
  universe/ShipHull.h
  universe/ShipPart.h
  universe/Special.h
  universe/Species.h
  universe/Tech.h
  universe/UnlockableItem.h
  universe/ValueRef.h
  universe/ValueRefs.h
  util/MultiplayerCommon.cpp
  util/MultiplayerCommon.h
  util/OptionsDB.h
Labels: component:internal, category:tweak

#4761 Refactor Docker CI
  .github/docker/debian-oldstable/Dockerfile
  .github/docker/debian-sid-i386/Dockerfile
  .github/docker/debian-sid/Dockerfile
  .github/docker/debian-stable/Dockerfile
  .github/docker/fedora-33/Dockerfile
  .github/docker/fedora-rawhide/Dockerfile
  .github/docker/manjaro/Dockerfile
  .github/docker/ubuntu-23.04/Dockerfile
  .github/workflows/_build-docker.yml
  .github/workflows/pr_run_config.toml
Labels: category:refactoring, component:infrastructure, status:merged

#4681 [AI] Another attempt to handle focus switches via target ratio
  default/python/AI/ResourcesAI.py
Labels: component:AI, category:tweak

#4768 dump species info to trace log after parsing
  client/human/GGHumanClientApp.cpp
  parse/SpeciesParser.cpp
Labels: component:content scripting, category:tweak

#4772 [FOCS] Port changes
  default/scripting/focs/_effects.pyi
  default/scripting/species/common/fuel.py
Labels: component:content scripting, category:tweak

#4777 remove test script
  default/scripting/species/SP_HUMAN.focs.txt
Labels: category:bug, component:content scripting

#4775 use newer clang on ubuntu 22.04 GitHub workflow
  .github/workflows/_build-ubuntu.yml
Labels: category:bug, component:infrastructure, component:build system, category:tweak

#4778 [AI] Build prerequisite ship facilities when needed
  default/python/AI/ProductionAI.py
Labels: category:bug, component:AI, status:cherry-pick for release

#4770 Port changes in py file to the macroses
  default/scripting/species/common/focus.macros
Labels: category:bug, component:content scripting, status:merged

#4776 expose SetFocus effect to Python parser
  parse/EffectPythonParser.cpp
Labels: component:content scripting, component:game mechanic, component:internal, category:tweak

#4779 Install packaged Clang 15 for Ubuntu 22.04
  .github/workflows/_build-ubuntu.yml
  .github/workflows/ubuntu-22.04-install-build.sh
Labels: component:infrastructure, category:tweak
