Repository freeorion/freeorion, pull requests merged in 2023-07, with the labels that each got.

#4594 Fix species description in encyclopedia
  parse/EffectPythonParser.cpp
  test/parse/TestPythonParser.cpp
  universe/Effects.cpp
Labels: category:bug, status:merged, component:internal, status:cherry-pick for release

#4565 Add game rules for tower defense mode
  default/scripting/game_rules.focs.py
  default/scripting/ship_hulls/monster/monster.macros
  default/scripting/specials/planet/monster_nest/monster_nest.macros
  default/stringtables/en.txt
Labels: category:feature, component:content scripting, status:merged

#4600 Validate checksums in Godot client
  client/godot/FreeOrionNode.cpp
Labels: status:merged, category:tweak, component:godot-client

#4598 Fix species description in encyclopedia [0.5]
  parse/EffectPythonParser.cpp
  universe/Effects.cpp
Labels: category:bug, status:merged, component:internal

#4605 Fix SetCapacity to accept float in Python FOCS
  parse/EffectPythonParser.cpp
Labels: category:bug, status:merged, component:internal

#4607 [FOCS] Update focs, fix error in tests
  .github/workflows/build_on_master.yml
  .github/workflows/build_on_pull_request.yml
  .github/workflows/codeql-analysis.yml
  .pre-commit-config.yaml
  default/scripting/focs/_effects.py
  default/scripting/focs/_effects.pyi
  default/scripting/focs/_species.pyi
  default/scripting/species/SP_ABADDONI.focs.py
  default/scripting/species/SP_ACIREMA.focs.py
  default/scripting/species/SP_BANFORO.focs.py
  default/scripting/species/SP_BEIGEGOO.focs.py
  default/scripting/species/common/env.py
  default/scripting/species/common/focus.py
  default/scripting/species/common/general.py
  default/scripting/species/common/happiness.py
  default/scripting/species/common/industry.py
  default/scripting/species/common/influence.py
  default/scripting/species/common/population.py
  default/scripting/species/common/research.py
  default/scripting/species/common/shields.py
  default/scripting/species/common/supply.py
  default/scripting/species/common/troops.py
  pyproject.toml
  test-scripting/species/SP_ABADDONI.focs.py
Labels: component:content scripting, category:tweak

#4596 [AI] Fix zero division error
  default/python/AI/ResourcesAI.py
Labels: category:bug, component:AI, status:cherry-pick for release

#4613 [FOCS] Add pyright support
  .github/workflows/python-focs-checks.yml
  .pre-commit-config.yaml
  default/python/requirements-dev.txt
  default/scripting/focs/_effects.pyi
  pyproject.toml
Labels: component:infrastructure, category:tweak

#4576 fix issue with rendering caret at start of line in MultiEdit
  GG/src/MultiEdit.cpp
Labels: category:bug, component:UI

#4616 typo
  default/scripting/species/common/native_fortification.macros
  default/scripting/species/common/native_fortification.py
Labels: component:content scripting, category:tweak

#4610 Add Armed condition and SetVisibility effect to Python FOCS
  parse/ConditionPythonParser.cpp
  parse/EffectPythonParser.cpp
  parse/EnumPythonParser.cpp
  parse/PythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4620 Fix Banforo species parsing
  default/scripting/species/SP_BANFORO.focs.py
Labels: category:bug, component:content scripting, priority:high

#4621 Build and run tests when scripts changed
  .github/workflows/build_on_master.yml
  .github/workflows/build_on_pull_request.yml
  .github/workflows/build_on_scripts.yml
Labels: component:infrastructure, category:tweak

#4626 [FOCS] Port typing changes
  default/scripting/focs/_effects.pyi
  default/scripting/focs/_species.pyi
  default/scripting/focs/_types.py
  default/scripting/species/common/detection.py
  default/scripting/species/common/empire_opinions.py
  default/scripting/species/common/focus.py
  default/scripting/species/common/general.py
  default/scripting/species/common/weapons.py
Labels: component:content scripting, category:tweak

#4627 Disable tests on Fedora Rawhide
  .github/workflows/_build-docker.yml
Labels: category:bug, component:infrastructure, status:merged, status:cherry-pick for release

#4628 Add Debian sid to CI
  .github/debian-sid/Dockerfile
  .github/workflows/_build-docker.yml
Labels: component:infrastructure, status:merged, status:cherry-pick for release, category:tweak

#4630 Fix Docker CI
  .github/debian-sid/Dockerfile
  .github/workflows/_build-docker.yml
Labels: category:bug, component:infrastructure, status:merged, status:cherry-pick for release

#4617 Prevent large laser targeting fighters
  default/scripting/ship_parts/ShortRange/SR_ICE_BEAM.focs.txt
Labels: component:content scripting, component:game mechanic, category:tweak

#4634 fix missing include
  default/scripting/ship_parts/ShortRange/SR_ICE_BEAM.focs.txt
Labels: category:bug, component:internal

#4635 Tweak Builld Workflows
  .github/workflows/build_on_master.yml
  .github/workflows/build_weekly.yml
Labels: component:infrastructure, category:tweak

#4606 Do not overriding species pilot trait effects by tech (Fix #4604)
  default/scripting/techs/ship_weapons/SHP_ROOT_AGGRESSION.focs.py
  default/scripting/techs/ship_weapons/ship_weapons.py
Labels: category:bug, component:content scripting

#4632 Remove unused game rule RULE_ENABLE_ALLIED_REPAIR
  default/scripting/game_rules.focs.py
  default/stringtables/en.txt
  default/stringtables/es.txt
  default/stringtables/fr.txt
Labels: category:bug, component:content scripting, component:game mechanic

#4631 Remove tests from Fedora Rawhide, add Debian sid to Docker CI [0.5]
  .github/debian-sid/Dockerfile
  .github/workflows/build-docker.yml
Labels: category:bug, component:infrastructure

#4633 Create binaries-test component for Windows archive
  .github/workflows/_build-windows.yml
  CMakeLists.txt
Labels: category:feature, component:build system, status:merged

#4642 Show error window in Godot
  godot/ErrorWindow.gd
  godot/ErrorWindow.tscn
  godot/FreeOrionClient.gd
Labels: category:feature, status:merged, component:godot-client

#4641 Fix ObjectMap internal copying
  universe/ObjectMap.cpp
  universe/ObjectMap.h
Labels: category:bug, component:internal

#4623 [CI] Allow to run workflow only on specic files change
  .github/workflows/_build-android.yml
  .github/workflows/_codeql-analysis.yml
  .github/workflows/_lint-python.yml
  .github/workflows/_lint_py_focs.yml
  .github/workflows/_lint_string-tables.yml
  .github/workflows/build_on_master.yml
  .github/workflows/build_on_pull_request.yml
  .github/workflows/build_on_scripts.yml
  .pre-commit-config.yaml
  check/__init__.py
  check/check_file_changed/_detectors.py
  check/check_file_changed/_workflow.py
  check/check_file_changed/check_coverage.py
  check/check_file_changed/set_output.py
  check/check_file_changed/tests/conftest.py
  check/check_file_changed/tests/test_detectors.py
  pyproject.toml
Labels: category:refactoring, component:infrastructure

#4647 [FOCS] Convert Chato
  default/scripting/species/SP_CHATO.focs.py
  default/scripting/species/SP_CHATO.focs.txt
Labels: category:refactoring, component:content scripting, status:merged

#4650 [FOCS] Convert species
  default/scripting/species/SP_CELESTEPHYTE.focs.py
  default/scripting/species/SP_CELESTEPHYTE.focs.txt
  default/scripting/species/SP_CRAY.focs.py
  default/scripting/species/SP_CRAY.focs.txt
  default/scripting/species/SP_CYNOS.focs.py
  default/scripting/species/SP_CYNOS.focs.txt
  default/scripting/species/SP_DERTHREAN.focs.py
  default/scripting/species/SP_DERTHREAN.focs.txt
  default/scripting/species/SP_EGASSEM.focs.py
  default/scripting/species/SP_EGASSEM.focs.txt
  default/scripting/species/common/industry.py
  default/scripting/species/common/troops.py
Labels: category:refactoring, component:content scripting

#4655 Fix some crashes
  universe/ObjectMap.cpp
  universe/Universe.cpp
Labels: category:bug, component:internal, priority:high
