Repository freeorion/freeorion, pull requests merged in 2023-01, with the labels that each got.

#4208 Apply damage scaling for combat value estimates in ship design pedia entry
  UI/EncyclopediaDetailPanel.cpp
Labels: category:bug, component:UI, status:cherry-pick for release

#4355 Fix links to outdated package version on test dependencies for snap test
  .github/workflows/snapcraft.yml
Labels: category:bug, component:infrastructure, status:cherry-pick for release

#4357 don't move from pointer passed elsewhere in the same call
  GG/src/Edit.cpp
Labels: category:bug, component:internal, status:cherry-pick for release, priority:high

#4363 Fix compilation with boost 1.81
  GG/GG/Base.h
Labels: category:bug, component:internal, status:cherry-pick for release

#4358 Change impossible liked focus
  default/scripting/species/SP_CYNOS.focs.txt
Labels: component:content scripting, status:cherry-pick for release, category:tweak

#4361 fix compile error with GCC 13
  GG/GG/Clr.h
  GG/GG/Enum.h
  UI/EncyclopediaDetailPanel.cpp
  UI/MapWnd.cpp
  network/Networking.h
  parse/ConditionPythonParser.cpp
  parse/EffectPythonParser.cpp
  server/ServerApp.cpp
  test/system/SmokeTestGame.cpp
  universe/BuildingType.cpp
  universe/FieldType.cpp
  universe/Meter.h
  universe/ShipHull.cpp
  universe/Species.cpp
  universe/Universe.cpp
  universe/UnlockableItem.h
  universe/ValueRefs.cpp
  util/Pending.h
  util/i18n.cpp
  util/i18n.h
Labels: category:bug, component:internal

#4364 GCC 13 fixes onto v0.5
  GG/GG/Clr.h
  GG/GG/Enum.h
  UI/MapWnd.cpp
  network/Networking.h
  parse/ConditionPythonParser.cpp
  parse/EffectPythonParser.cpp
  server/ServerApp.cpp
  test/system/SmokeTestGame.cpp
  universe/BuildingType.cpp
  universe/FieldType.cpp
  universe/Meter.h
  universe/ShipHull.cpp
  universe/Species.cpp
  universe/Universe.cpp
  universe/UnlockableItem.h
  universe/ValueRefs.cpp
  util/Pending.h
Labels: category:bug, component:internal, category:tweak

#4365 Fix Clickable List of Fields
  UI/EncyclopediaDetailPanel.cpp
Labels: category:bug, component:UI, status:cherry-pick for release

#4367 switch #include to silence a deprecation message
  parse/NamedValueRefParser.cpp
Labels: component:internal, status:cherry-pick for release, category:tweak

#4362 [AI] Update skeleton generator
  .pre-commit-config.yaml
  default/python/freeorion.pyi
  default/python/handlers/shared_instances_code.py
Labels: component:AI, component:infrastructure, category:tweak

#4375 Fix Fleet Destroy
  universe/Universe.cpp
Labels: category:bug, component:internal, priority:high

#4351 Fix industry distribution for PLC_COLONIALISM
  default/scripting/policies/COLONIALISM.focs.txt
Labels: category:bug, component:content scripting, status:cherry-pick for release

#4378 Fix inconsistency in TotalWeaponsShipDamage usage
  UI/FleetWnd.cpp
Labels: category:bug, component:UI, status:cherry-pick for release

#4369 Update xvfb Github Action from deprecated Node.js 12
  .github/workflows/snapcraft.yml
Labels: component:infrastructure, status:cherry-pick for release, category:tweak

#4373 Update charting apperance
  default/python/charting/README.md
  default/python/charting/log_parser/__init__.py
  default/python/charting/log_parser/collect_data.py
  default/python/charting/log_parser/extract_data.py
  default/python/charting/log_parser/file_reader.py
  default/python/charting/log_parser/log_tokenizer.py
  default/python/charting/log_parser/tests/conftest.py
  default/python/charting/log_parser/tests/test_tokenizer.py
  default/python/charting/requirements_charts.txt
  default/python/charting/streamlite_app.py
  default/python/charting/tabs/__init__.py
  default/python/charting/tabs/policies.py
  default/python/charting/tabs/stats.py
  default/python/charting/tabs/widgets.py
Labels: category:refactoring, component:infrastructure

#4372 [AI] update ini file reader
  default/python/README.md
  default/python/common/option_tools.py
Labels: category:refactoring, component:AI
