Repository freeorion/freeorion, pull requests merged in 2023-06, with the labels that each got.

#4240 [AI] Remove unused code
  default/python/AI/AIDependencies.py
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/ColonisationAI.py
  default/python/AI/EnumsAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/PlanetUtilsAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ResearchAI.py
Labels: category:refactoring, component:AI

#4537 [AI] update skeleton typing
  default/python/AI/DiplomaticCorp.py
  default/python/AI/FreeOrionAI.py
  default/python/AI/freeOrionAIInterface.pyi
  default/python/common/fo_typing.py
  default/python/freeorion.pyi
  default/python/stub_generator/__init__.py
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/stub_generator/class_generator.py
  default/python/stub_generator/stub_generator/rtype/_function_mapping.py
  default/python/stub_generator/stub_generator/rtype/_method_mapping.py
  default/python/stub_generator/stub_generator/rtype/_property_mapping.py
  default/python/stub_generator/stub_generator/rtype/mapper.py
  default/python/stub_generator/stub_generator/rtype/utils.py
Labels: component:AI, category:tweak

#4538 [AI] Remove unused code
  default/python/AI/ResearchAI.py
  default/python/AI/turn_state/__init__.py
  default/python/AI/turn_state/_empire_resources.py
  pyproject.toml
Labels: category:refactoring, component:AI

#4524 Pick starting spots for empires with a minimum variety of planets
  default/python/universe_generation/empires.py
  default/python/universe_generation/options.py
  default/python/universe_generation/universe_generator.py
  default/scripting/game_rules.focs.py
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak

#4545 [AI] logs and skeletons improvements
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/freeOrionAIInterface.pyi
  default/python/AI/generate_orders.py
  default/python/common/fo_typing.py
  default/python/common/print_utils/__init__.py
  default/python/common/print_utils/_base_field.py
  default/python/common/print_utils/_dict.py
  default/python/common/print_utils/_table.py
  default/python/freeorion.pyi
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/stub_generator/collection_classes/_collection_name_parser.py
  default/python/stub_generator/stub_generator/collection_classes/test_type_parsing.py
  default/python/stub_generator/stub_generator/rtype/__init__.py
  default/python/stub_generator/stub_generator/rtype/_function_mapping.py
  default/python/stub_generator/stub_generator/rtype/_mapping_code.py
  default/python/stub_generator/stub_generator/rtype/_method_mapping.py
  default/python/stub_generator/stub_generator/rtype/_property_mapping.py
  default/python/stub_generator/stub_generator/rtype/mapper.py
  default/python/stub_generator/stub_generator/rtype/test_rtype_conversion.py
  default/python/stub_generator/stub_generator/rtype/utils.py
  default/python/tests/common/test_print_utils.py
Labels: category:refactoring, component:AI

#4546 [AI] Refactor combat stats
  default/python/AI/CombatRatingsAI/_ratings.py
  default/python/AI/CombatRatingsAI/_ship_combat_stats.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/freeorion_tools/__init__.py
  default/python/AI/freeorion_tools/_freeorion_tools.py
  default/python/AI/freeorion_tools/design_compare.py
  default/python/common/fo_typing.py
  default/python/tests/AI/test_design_compare.py
Labels: category:refactoring, component:AI

#4547 Increase refuel rate of ramscoop
  default/scripting/common/named_values.focs.txt
  default/scripting/ship_hulls/ship_hulls.macros
  default/scripting/ship_parts/Fuel/FU_RAMSCOOP.focs.txt
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak

#4534 Fix Or
  universe/Conditions.cpp
Labels: category:bug, component:game mechanic

#4549 [AI] refactor ship design
  default/python/AI/ShipDesignAI.py
  default/python/AI/ship_design/__init__.py
  default/python/AI/ship_design/_additional_specification.py
  default/python/AI/ship_design/_design_stats.py
  default/python/AI/ship_design/_ship_design_cache.py
Labels: category:refactoring, component:AI

#4558 move ARTISAN_APPRECIATION to happiness.macros
  default/scripting/species/common/happiness.macros
  default/scripting/species/common/happiness.py
  default/scripting/species/common/influence.macros
  default/scripting/species/common/influence.py
  test-scripting/species/common/happiness.py
  test-scripting/species/common/influence.py
Labels: component:content scripting, category:tweak

#4562 [CI] simplify ci run
  .github/workflows/_build-macos.yml
  .github/workflows/_build-ubuntu.yml
  .github/workflows/build_on_pull_request.yml
  .github/workflows/build_weekly.yml
Labels: component:deployment, category:tweak

#4563 [CI] Fix steps order for weekly build
  .github/workflows/_build-windows.yml
Labels: category:bug, component:deployment

#4561 Make Experimentors spawn base turn a game rule
  default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.txt
  default/scripting/game_rules.focs.py
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak

#4564 copy first and second parts of TagVecs rather than first part twice
  python/UniverseWrapper.cpp
Labels: category:bug, component:internal

#4567 Fix serialization bug
  default/python/AI/CombatRatingsAI/_ship_combat_stats.py
  default/python/AI/savegame_codec/_encoder.py
  default/python/tests/AI/save_game_codec/test_savegame_manager.py
Labels: category:bug, component:AI

#4557 Always set Max?-Capacity-SecondaryStat for WEAPON_BASE_EFFECTS
  default/scripting/techs/ship_weapons/ship_weapons.py
  pyproject.toml
Labels: category:bug, component:content scripting

#4572 Tabs To Spaces
  default/scripting/buildings/shipyards/ASTEROID.focs.txt
  default/scripting/buildings/shipyards/ASTEROID_REF.focs.txt
  default/scripting/buildings/shipyards/BASE.focs.txt
  default/scripting/buildings/shipyards/CON_ADV_ENGINE.focs.txt
  default/scripting/buildings/shipyards/CON_GEOINT.focs.txt
  default/scripting/buildings/shipyards/CON_NANOROBO.focs.txt
  default/scripting/buildings/shipyards/ENERGY_COMP.focs.txt
  default/scripting/buildings/shipyards/ENERGY_SOLAR.focs.txt
  default/scripting/buildings/shipyards/ORBITAL_DRYDOCK.focs.txt
  default/scripting/buildings/shipyards/ORGANIC_CEL_GRO.focs.txt
  default/scripting/buildings/shipyards/ORGANIC_ORB_INC.focs.txt
  default/scripting/buildings/shipyards/ORGANIC_XENO_FAC.focs.txt
  default/scripting/species/common/empire_opinions.macros
Labels: component:content scripting, category:tweak

#4577 Fix 4575 master
  GG/src/MultiEdit.cpp
Labels: category:bug, component:UI

#4581 [AI] Update skeletons
  default/python/AI/freeOrionAIInterface.pyi
  default/python/freeorion.pyi
  default/python/stub_generator/stub_generator/rtype/_property_mapping.py
Labels: component:AI, category:tweak

#4585 Tweak CheckSums
  util/CheckSums.cpp
  util/CheckSums.h
Labels: category:bug, component:internal, category:tweak

#4586 Implement ValueRefInt >= int in Python FOCS parser
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, status:merged, component:internal

#4590 fix serialization failure due to mismatched tags
  util/SerializeEmpire.cpp
Labels: category:bug, component:network
