Repository freeorion/freeorion, pull requests merged in 2023-08, with the labels that each got.

#4649 Implement ValueRefDouble - ValueRefInt in Python FOCS
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, status:merged, component:internal

#3446 Launch tests on MacOS
  .github/workflows/_build-macos.yml
  GG/test/unit/CMakeLists.txt
  test/parse/CMakeLists.txt
  test/system/CMakeLists.txt
  test/util/CMakeLists.txt
Labels: component:infrastructure, status:merged, category:tweak

#4659 Don't run tests on MacOS 12
  .github/workflows/_build-macos.yml
Labels: component:infrastructure, status:merged

#4662 [FOCS] Update macroses and typing
  default/scripting/focs/_effects.pyi
  default/scripting/focs/_species.pyi
  default/scripting/species/common/happiness.py
  default/scripting/species/common/influence.py
  default/scripting/species/common/planet_defense.py
  default/scripting/species/common/planet_shields.py
  default/scripting/species/common/planet_size.py
  default/scripting/species/common/population.py
  default/scripting/species/common/research.py
  default/scripting/species/common/shields.py
  default/scripting/species/common/supply.py
  default/scripting/species/common/troops.py
  default/scripting/species/common/xenophobic.py
Labels: component:content scripting, category:tweak

#4640 Use FindPython3 CMake module instead of deprecated FindPythonLibs and FindPythonInterp
  .github/workflows/_build-android.yml
  CMakeLists.txt
Labels: category:bug, component:build system, status:merged, priority:high

#4657 Test Python parsers on MacOS
  test/parse/CMakeLists.txt
  test/parse/ParserAppFixture.cpp
  test/parse/ParserAppFixture.h
  test/parse/TestPythonParser.cpp
  util/Directories.cpp
  util/Directories.h
Labels: category:refactoring, status:merged, component:internal

#4665 Fix PlanetPanel use of client empire
  UI/SidePanel.cpp
Labels: category:bug, component:UI

#4667 Cleanup FOCS skeletons
  .pre-commit-config.yaml
  default/python/requirements-dev.txt
  default/scripting/focs/_effects.pyi
  default/scripting/focs/_species.pyi
  default/scripting/focs/_types.py
Labels: category:refactoring, component:content scripting

#4672 Add Debian Oldstable to CI
  .github/debian-oldstable/Dockerfile
  .github/workflows/_build-docker.yml
Labels: component:infrastructure, status:merged, category:tweak

#4673 Fix range usage for GCC 10.3
  util/ranges.h
Labels: status:merged, component:internal, category:tweak

#4675 Fix objects not being moved in SortedNumberOf::Eval with no sort key
  universe/Conditions.cpp
Labels: category:bug, component:content scripting, component:game mechanic, component:internal, priority:high

#4658 Newlines in stringtable
  UI/ChatWnd.cpp
  UI/ClientUI.cpp
  client/human/HumanClientFSM.cpp
Labels: component:translation, component:internal, category:tweak

#4677 remove duplicate mesa libs when building snap
  snap/snapcraft.yaml
Labels: category:bug, component:build system, status:merged

#4679 [AI, CI] Update python linter version
  .pre-commit-config.yaml
  check/checkSpeciesTags.py
  check/st-tool.py
  default/python/AI/AIFleetMission.py
  default/python/AI/AIstate.py
  default/python/AI/ColonisationAI.py
  default/python/AI/CombatRatingsAI/_ship_combat_stats.py
  default/python/AI/DiplomaticCorp.py
  default/python/AI/ExplorationAI.py
  default/python/AI/FleetUtilsAI.py
  default/python/AI/InvasionAI.py
  default/python/AI/MilitaryAI.py
  default/python/AI/PlanetUtilsAI.py
  default/python/AI/PolicyAI.py
  default/python/AI/PriorityAI.py
  default/python/AI/ProductionAI.py
  default/python/AI/ResearchAI.py
  default/python/AI/ResourcesAI.py
  default/python/AI/ShipDesignAI.py
  default/python/AI/colonization/calculate_population.py
  default/python/AI/empire/survey_universe.py
  default/python/AI/fleet_orders.py
  default/python/AI/pathfinding.py
  default/python/AI/savegame_codec/_decoder.py
  default/python/AI/ship_design/_ship_design_cache.py
  default/python/AI/turn_state/_empire_resources.py
  default/python/requirements-dev.txt
  default/python/stub_generator/parse_docs.py
  default/python/stub_generator/stub_generator/class_generator.py
  default/python/tests/AI/character_test/character_test.py
  default/python/tests/AI/save_game_codec/test_savegame_manager.py
  default/python/universe_generation/empires.py
  default/python/universe_generation/galaxy.py
  default/python/universe_generation/monsters.py
  default/python/universe_generation/natives.py
  default/python/universe_generation/specials.py
  default/python/universe_generation/starnames.py
  default/python/universe_generation/starsystems.py
  default/python/universe_generation/teams.py
  default/python/universe_generation/universe_generator.py
  default/scripting/focs/_effects.pyi
  doc/tag_parser.py
Labels: category:refactoring, component:AI

#4680 [FOCS] Convert species to Python
  default/scripting/species/SP_EXOBOT.focs.py
  default/scripting/species/SP_EXOBOT.focs.txt
  default/scripting/species/SP_EXPERIMENTOR.focs.py
  default/scripting/species/SP_EXPERIMENTOR.focs.txt
  default/scripting/species/SP_FIFTYSEVEN.focs.py
  default/scripting/species/SP_FIFTYSEVEN.focs.txt
  default/scripting/species/SP_FURTHEST.focs.py
  default/scripting/species/SP_FURTHEST.focs.txt
  default/scripting/species/SP_GEORGE.focs.py
  default/scripting/species/SP_GEORGE.focs.txt
  default/scripting/species/SP_GISGUFGTHRIM.focs.py
  default/scripting/species/SP_GISGUSGTHRIM.focs.txt
  default/scripting/species/SP_GYSACHE.focs.py
  default/scripting/species/SP_GYSACHE.focs.txt
  default/scripting/species/SP_HAPPY.focs.py
  default/scripting/species/SP_HAPPY.focs.txt
Labels: category:refactoring, component:content scripting, status:merged

#4684 fix broken policy likes/dislikes on exobot
  default/scripting/species/SP_EXOBOT.focs.py
Labels: category:bug, component:content scripting

#4683 Output species likes and dislikes in dump
  universe/Species.cpp
Labels: status:merged, component:internal, category:tweak

#4686 Add species likes/dislikes to checksum calculation
  test/parse/TestPythonParser.cpp
  universe/Species.cpp
Labels: status:merged, component:internal, category:tweak

#4685 [FOCS] Update readme
  default/scripting/README.md
  default/scripting/_readme_images/error_missed_argument.png
  default/scripting/_readme_images/error_typo_in_name.png
  default/scripting/_readme_images/import.png
  default/scripting/_readme_images/mark_as_source_root.png
  default/scripting/_readme_images/quick-fix.png
Labels: category:tweak, component:technical docs

#4687 Fix and test broken string in species name, likes and dislikes
  default/scripting/species/SP_BANFORO.focs.py
  default/scripting/species/SP_CELESTEPHYTE.focs.py
  test/parse/TestPythonParser.cpp
Labels: category:bug, component:content scripting, component:internal

#4676 give Megalith effects different stacking groups
  default/scripting/buildings/MEGALITH.focs.txt
Labels: category:bug, component:content scripting, status:cherry-pick for release, category:tweak

#4691 Fix Debian depenencies package name on CI
  .github/debian-oldstable/Dockerfile
  .github/debian-sid/Dockerfile
  .github/debian-stable/Dockerfile
Labels: category:bug, component:infrastructure, status:merged

#4693 [FOCS] Update typing, minor fixes
  default/scripting/focs/_effects.pyi
  default/scripting/focs/_species.pyi
  default/scripting/focs/_types.py
  default/scripting/species/SP_CELESTEPHYTE.focs.py
  default/scripting/species/common/focus.py
  default/scripting/species/common/planet_defense.py
  default/scripting/species/common/planet_shields.py
  default/scripting/species/common/stealth.py
  default/scripting/species/common/xenophobic.py
Labels: component:content scripting, category:tweak

#4694 refactor zooming to next/previous system/fleet code
  UI/MapWnd.cpp
Labels: category:bug, component:UI, category:tweak

#4695 [FOCS] Simplify typing
  .pre-commit-config.yaml
  default/scripting/buildings/colonies/col_bld_gen.py
  default/scripting/focs/_effects.pyi
  default/scripting/focs/_species.pyi
  default/scripting/focs/_types.py
Labels: component:content scripting, category:tweak

#4698 Fixed engine parts tech descriptions
  default/stringtables/en.txt
Labels: category:bug, component:translation

#4703 disable annexation of Experimentors
  default/scripting/species/SP_EXPERIMENTOR.focs.py
Labels: component:content scripting, category:tweak

#4706 [PY] update stubs
  default/python/AI/freeOrionAIInterface.pyi
  default/python/common/fo_typing.py
  default/python/freeorion.pyi
  default/python/stub_generator/generate_stub.py
  default/python/stub_generator/interface_inspector/class_processor.py
  default/python/stub_generator/stub_generator/class_generator.py
  default/python/stub_generator/stub_generator/rtype/_function_mapping.py
  default/python/stub_generator/stub_generator/rtype/_method_mapping.py
  default/python/stub_generator/stub_generator/rtype/_property_mapping.py
  default/python/stub_generator/stub_generator/rtype/mapper.py
  default/python/stub_generator/stub_generator/test_resource_builder.py
Labels: component:AI, category:tweak

#4710 [FOCS] Fix inconsistence in fighter bay
  default/scripting/techs/ship_weapons/fighters/SHP_FIGHTERS_4.focs.py
Labels: category:bug, component:content scripting

#4711 [Translation] Actualise translation to the fighter bays
  default/stringtables/en.txt
Labels: category:bug, component:content scripting, component:translation

#4713 convert Option::SetFromValue parameters to std::string when possible
  util/OptionsDB.h
Labels: component:internal, category:tweak

#4718 Stake Awake
  network/Message.cpp
Labels: category:bug, component:internal
