Repository freeorion/freeorion, pull requests merged in 2024-09, with the labels that each got.

#4987 Fix DebugLogger usage in Python Init not to get wide string
  util/PythonCommon.cpp
Labels: category:bug, component:internal

#5000 some explicit utf8 path encoding to deal with out-of-codepage paths on Windows
  UI/ClientUI.cpp
  client/AI/AIClientApp.cpp
  client/AI/AIFramework.cpp
  client/AI/AIWrapper.cpp
  client/human/GGHumanClientApp.cpp
  python/PythonBase.cpp
  python/PythonBase.h
  server/ServerApp.cpp
  server/ServerFSM.cpp
  server/ServerFramework.cpp
  server/ServerFramework.h
  util/Logger.cpp
  util/StringTable.cpp
  util/i18n.cpp
Labels: category:bug, component:internal

#4962 Implement HasStarlane in Python FOCS parser
  parse/ConditionPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5008 fix internal compiler error in MSVC on particular system
  universe/ShipDesign.cpp
Labels: category:bug, component:internal

#5011 Fix Cancel Giving Crash
  UI/FleetWnd.cpp
Labels: category:bug, component:UI, component:internal
