Repository freeorion/freeorion, pull requests merged in 2024-07, with the labels that each got.

#4970 Fix PLC_ENGINEERING to have effect for RULE_SHIP_PART_BASED_UPKEEP
  default/scripting/macros/upkeep.macros
Labels: category:bug, component:content scripting

#4965 close some rgba tags
  UI/IntroScreen.cpp
  UI/PlayerListWnd.cpp
Labels: category:bug, component:UI

#4972 fix design existence test in CheckRename
  util/Order.cpp
Labels: category:bug, component:UI

#4975 Use singleton to fix RichText::RegisterDefaultBlock
  GG/src/RichText/RichText.cpp
Labels: category:bug, component:UI

#4986 Update BUILD.md (old link didn't work)
  BUILD.md
Labels: category:bug, component:technical docs

#4960 Fix some python FOCS errors
  default/scripting/focs/_industry.py
  default/scripting/focs/_industry.pyi
  default/scripting/species/species_macros/industry.py
  test-scripting/focs/_buildings.py
  test-scripting/focs/_effects.py
  test-scripting/focs/_species.py
  test-scripting/focs/_tech.py
  test-scripting/species/SP_ABADDONI.focs.py
  test-scripting/species/SpeciesCensusOrdering.focs.py
Labels: component:content scripting, category:tweak, priority:high

#4967 fix 4952 fix nest eradicator
  default/scripting/buildings/NEST_ERADICATOR.focs.txt
  default/scripting/macros/priorities.macros
  default/scripting/macros/priorities.py
  default/scripting/specials/planet/monster_nest/monster_nest.macros
Labels: category:bug, component:content scripting

#4985 texture loading - use gil::read_image with ifstream to overcome unicode path issues
  GG/src/Texture.cpp
Labels: category:bug, component:internal

#4973 fix design existence test in CheckRename v0.5
  util/Order.cpp
Labels: category:bug, component:UI

#4961 Make missing import a failure in Python FOCS parser
  parse/PythonParser.cpp
Labels: component:content scripting, status:merged, component:internal, category:tweak

#4982 Use GCC 14 with Debian sid in Docker CI
  .github/docker/debian-sid/Dockerfile
Labels: component:infrastructure, status:merged, category:tweak

#4983 Use GCC 14 with Debian sid in Docker CI [0.5]
  .github/debian-sid/Dockerfile
Labels: component:infrastructure, status:merged, category:tweak
