Repository freeorion/freeorion, pull requests merged in 2024-02, with the labels that each got.

#4863 Fix monster detection to get detection out of monsters, not player ships
  combat/CombatSystem.cpp
Labels: category:bug, component:game mechanic

#4827 Add code to parse and compare FOCS dumps
  .github/workflows/_lint-python.yml
  check/focs_dump_parser/.gitignore
  check/focs_dump_parser/README.md
  check/focs_dump_parser/__init__.py
  check/focs_dump_parser/_tools.py
  check/focs_dump_parser/make_diff.py
  check/focs_dump_parser/parse_buildings.py
  check/focs_dump_parser/parser.py
  check/focs_dump_parser/test_parser.py
  check/focs_dump_parser/test_prettyfy_dump.py
Labels: category:feature, component:infrastructure

#4849 boostrapping stability growth happen at AFTER_ALL_TARGET_MAX_METERS_PRIORITY
  default/scripting/policies/BOOTSTRAPPING.focs.txt
Labels: category:bug, component:content scripting

#4855 Swap research order of domesticated monsters and nest eradication
  default/scripting/buildings/NEST_ERADICATOR.focs.txt
  default/scripting/techs/growth/MEGA_ECO.focs.py
  default/scripting/techs/ship_hulls/SHP_DOMESTIC_MONSTER.focs.py
  default/scripting/techs/ship_hulls/organic/SHP_ORG_HULL.focs.py
Labels: component:content scripting, category:tweak

#4868 Fix Compile Error in Apple Clang 15
  universe/ScriptingContext.h
Labels: category:bug, component:internal

#4832 Fix division by zero when AI has researched everything
  default/python/AI/ResourcesAI.py
Labels: category:bug, component:AI
