Repository freeorion/freeorion, pull requests merged in 2024-12, with the labels that each got.

#5042 v0.5.1 changelog
  ChangeLog.md
Labels: status:cherry-pick for release, component:technical docs, component:user manual, priority:high

#5041 Trigger full CI build when push on release branches
  .github/workflows/build_on_master.yml
Labels: component:infrastructure, status:merged, status:cherry-pick for release, category:tweak

#5046 don't forward args twice when checking then issuing order in AI wrapper
  client/AI/AIWrapper.cpp
Labels: category:bug, component:AI, component:internal, status:cherry-pick for release

#5051 Fix Void missing boost.python library
  .github/docker/void-musl/Dockerfile
Labels: category:bug, component:infrastructure, status:cherry-pick for release

#5050 Enable CI build on PR for release branch
  .github/workflows/build_on_pull_request.yml
Labels: component:infrastructure, status:cherry-pick for release, category:tweak

#5056 copy string_view into a (null terminated) string before passing to sscanf
  universe/Meter.cpp
Labels: component:internal, category:tweak

#5055 Fix Font Regex Iteration
  GG/src/Font.cpp
Labels: category:bug, component:internal
