Repository freeorion/freeorion, pull requests merged in 2024-04, with the labels that each got.

#4899 updates for Boost 1.85
  GG/src/dialogs/FileDlg.cpp
  util/Directories.cpp
  util/OptionsDB.cpp
Labels: category:bug, component:internal

#4908 updates for Boost 1.85
  GG/src/dialogs/FileDlg.cpp
  util/Directories.cpp
  util/OptionsDB.cpp
Labels: category:bug, component:internal, category:tweak

#4907 better indicate detection of ships that launch fighters in combat log
  combat/CombatEvent.h
  combat/CombatEvents.cpp
  combat/CombatEvents.h
  combat/CombatSystem.cpp
  default/stringtables/en.txt
  util/SerializeCombat.cpp
Labels: category:bug, component:UI

#4896 Make Military Command cheaper
  default/scripting/buildings/MILITARY_COMMAND.focs.txt
Labels: component:content scripting, category:tweak

#4102 Remove exclusion between Exploration and Colonization Policy
  default/scripting/policies/COLONIZATION.focs.txt
  default/scripting/policies/EXPLORATION.focs.txt
Labels: component:content scripting, category:tweak

#4893 Rework Augmentation Policy
  default/scripting/macros/misc.macros
  default/scripting/macros/misc.py
  default/scripting/policies/AUGMENTATION.focs.txt
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak

#4913 Tweak Isolation Policy
  default/scripting/policies/ISOLATION.focs.txt
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak

#4923 remove "using enum PlanetType" that breaks gcc 10.3.1 and 10.2.1 builds
  universe/Planet.cpp
Labels: category:bug, component:internal

#4922 Musl compatibility
  universe/Enums.h
Labels: category:bug, component:internal

#4909 Concede Object Rules
  default/stringtables/en.txt
  server/ServerApp.cpp
  util/GameRuleRanks.h
  util/MultiplayerCommon.cpp
Labels: component:game mechanic, category:tweak

#4924 missing value ref strings
  default/stringtables/en.txt
Labels: component:art music text assets, category:tweak

#4917 allow range 0 detection at the same location
  universe/Universe.cpp
Labels: component:game mechanic, category:tweak

#4925 Add Void with musl to Docker CI
  .github/docker/void-musl/Dockerfile
  .github/workflows/_build-docker.yml
Labels: component:infrastructure, category:tweak

#4918 Rework Centralization
  default/scripting/policies/BUREAUCRACY.focs.txt
  default/scripting/policies/CENTRALIZATION.focs.txt
  default/scripting/species/SP_EGASSEM.focs.py
  default/scripting/species/SP_REPLICON.focs.py
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak

#4927 add turn 1 species unlocks to pedia
  default/scripting/species/SP_ABADDONI.focs.py
  default/scripting/species/SP_FULVER.focs.py
  default/scripting/species/SP_SLY.focs.py
  default/stringtables/en.txt
Labels: component:content scripting, component:UI, component:art music text assets, category:tweak

#4916 expose hull detection to Python API
  python/UniverseWrapper.cpp
Labels: component:content scripting, category:tweak

#4932 Allow Traffic Control/Lighthouses to work for peaceful/allied empires
  default/scripting/buildings/LIGHTHOUSE.focs.txt
  default/scripting/policies/TRAFFIC_CONTROL.focs.txt
  default/stringtables/en.txt
Labels: component:content scripting, category:tweak
