Repository freeorion/freeorion, pull requests merged in 2024-01, with the labels that each got.

#4833 Fix division by zero when AI has researched everything
  default/python/AI/ResourcesAI.py
Labels: category:bug, component:AI

#4838 Implement CreateField effect in FOCS Python parser
  parse/EffectPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#4822 fix compile errors
  UI/TechTreeLayout.cpp
Labels: category:bug, component:internal

#4843 Fix Python 3.12 issues
  .github/workflows/_build-docker.yml
  parse/PythonParser.cpp
  parse/PythonParser.h
  util/PythonCommon.cpp
Labels: category:bug, status:merged, component:internal

#4848 Fix build for GCC-14
  universe/System.cpp
Labels: category:bug, status:merged, component:internal

#4850 Fix build with GCC 14
  GG/src/UnicodeCharsets.cpp
Labels: category:bug, status:merged, component:internal

#4852 Fix boost assertion
  GG/src/Font.cpp
Labels: category:bug, status:merged, component:internal

#4857 Fix reference to invalidated element
  UI/CUIControls.cpp
Labels: category:bug, status:merged, component:internal

#4858 Restore CI tests on Fedora Rawhide
  .github/workflows/build-docker.yml
Labels: component:infrastructure, status:merged, category:tweak

#4839 (0.5) Cap xeno frenzy malus with self-sustain bonus
  default/scripting/species/common/xenophobic.macros
Labels: category:bug, component:content scripting, component:game mechanic, status:merged

#4750 Move colonizer CanColonize location condition to FOCS. Allow outposts…
  UI/BuildDesignatorWnd.cpp
  default/scripting/ship_parts/Colony/CO_COLONY_POD.focs.txt
  default/scripting/ship_parts/Colony/CO_SUPEND_ANIM_POD.focs.txt
  universe/Ship.cpp
  universe/ShipDesign.cpp
  universe/ShipDesign.h
Labels: component:content scripting, component:internal, category:tweak
