Repository freeorion/freeorion, pull requests merged in 2024-08, with the labels that each got.

#4994 fix multiline color rendering issues by removing 255 stack limit on saved colors
  GG/GG/Font.h
  GG/src/Font.cpp
Labels: category:bug, component:UI

#4995 Focus password field in password dialog
  client/human/HumanClientFSM.cpp
Labels: component:UI, status:merged, category:tweak

#5003 Feudalism Tweaks
  default/scripting/policies/FEUDALISM.focs.txt
Labels: category:bug, component:content scripting

#5005 typos found by Lintian
  GG/GG/DynamicGraphic.h
  GG/GG/Wnd.h
  GG/src/Texture.cpp
  UI/SidePanel.cpp
  UI/TechTreeWnd.h
  combat/CombatEvent.h
  default/scripting/custom_sitreps.py
  server/ServerFSM.cpp
  server/ServerNetworking.cpp
  util/Directories.cpp
  util/Pending.h
Labels: component:internal, category:tweak
