Repository freeorion/freeorion, pull requests merged in 2025-02, with the labels that each got.

#5091 Default RULE_FIGHTER_DAMAGE_FACTOR to 5.0 instead of 6.0
  universe/ShipHull.cpp
Labels: component:game mechanic, status:merged, component:internal, category:tweak

#5093 Implement StarlaneToWouldCrossExistingStarlane, StarlaneToWouldBeAngularlyCloseToExistingStarlane, and StarlaneToWouldBeCloseToObject conditions in Python FOCS parser
  parse/ConditionPythonParser.cpp
Labels: category:refactoring, component:internal

#5090 CI: Make automatic scheduled weekly test builds
  .github/workflows/_build-macos.yml
  .github/workflows/_build-windows-msvs.yml
  .github/workflows/_build-windows.yml
  .github/workflows/build_weekly.yml
  .github/workflows/build_weekly_scheduled.yml
Labels: category:feature, component:infrastructure

#5097 Add Described condition to Python FOCS parser
  parse/ConditionPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5095 fix ai fighter damage dependencies
  default/python/AI/AIDependencies.py
Labels: component:AI, status:merged, status:cherry-pick for release, category:tweak

#5094 Fix fighter damage with scaling info in pedia
  default/scripting/species/species_macros/weapons.py
  default/scripting/techs/ship_weapons/fighters/SHP_FIGHTERS_2.focs.py
  default/scripting/techs/ship_weapons/fighters/SHP_FIGHTERS_3.focs.py
  default/scripting/techs/ship_weapons/fighters/SHP_FIGHTERS_4.focs.py
  default/scripting/techs/ship_weapons/ship_weapons.py
  default/stringtables/en.txt
Labels: category:bug, status:merged, status:cherry-pick for release, component:user manual

#5098 Fix CI errors: disable Fedora Rawhide, fix Python linting
  .github/workflows/_build-docker.yml
  default/scripting/species/species_macros/weapons.py
  default/scripting/techs/ship_weapons/ship_weapons.py
Labels: category:bug, component:content scripting, component:infrastructure, status:merged, status:cherry-pick for release

#5099 Implement Design condition in Python FOCS parser
  parse/ConditionPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5101 Implement unary -ValueRefDouble in Python FOCS parser
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, status:merged, component:internal

#5102 Test empire statistic parser on test files
  test-scripting/empire_statistics/ARMED_MONSTER_COUNT.focs.txt
  test/parse/TestPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5103 CI: Disable debian sid due gcc 15.0.1 ICE
  .github/workflows/_build-docker.yml
Labels: category:bug, component:infrastructure, status:cherry-pick for release

#5081 Remove duplicated build dependency in CI/CD Dockerfiles
  .github/docker/debian-oldstable/Dockerfile
  .github/docker/debian-sid-i386/Dockerfile
  .github/docker/debian-sid/Dockerfile
  .github/docker/debian-stable/Dockerfile
  .github/docker/ubuntu-24.10/Dockerfile
Labels: component:infrastructure, status:merged, status:cherry-pick for release, category:tweak

#5104 [tools] Update buiding parser to filter unrelated log lines
  check/focs_dump_parser/parser.py
  check/focs_dump_parser/test_parser.py
Labels: component:internal, category:tweak

#5106 Implement MoveTowards(speed, x, y) in Python FOCS parser
  parse/EffectPythonParser.cpp
Labels: category:refactoring, component:internal

#5108 Test empire statistic parser on default files
  test/parse/TestDefaultPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5109 Make empire statistic parser synchronized
  parse/DummyParsers.cpp
  parse/EmpireStatsParser.cpp
  parse/Parse.h
  server/ServerApp.cpp
  test/parse/TestDefaultPythonParser.cpp
  test/parse/TestPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5114 CI: Reorganize Docker godot settings
  .github/workflows/_build-docker.yml
Labels: category:refactoring, component:infrastructure

#4853 Add parser_context attribute to Python FOCS parser builtins
  parse/PythonParser.cpp
Labels: component:internal, category:tweak

#5117 CI: Restore Fedora Rawhode and Debian sid in Docker
  .github/docker/debian-sid/Dockerfile
  .github/docker/fedora-rawhide/Dockerfile
  .github/workflows/_build-docker.yml
Labels: component:infrastructure, category:tweak

#4763 Test species dump on Windows CI
  .github/workflows/_build-windows.yml
Labels: component:infrastructure, status:merged, category:tweak

#5119 use span instead of vector for TagVecs
  universe/UniverseObject.h
Labels: component:internal, category:tweak

#5122 CI: Restore building Windows test artifacts
  .github/workflows/_build-windows.yml
  .github/workflows/build_weekly_scheduled.yml
Labels: component:infrastructure, category:tweak

#5116 Don't use UserString in Dump
  universe/Conditions.h
  universe/Planet.cpp
  universe/Planet.h
  universe/Species.h
  universe/System.h
  universe/UniverseObject.h
  universe/ValueRefs.cpp
Labels: status:merged, component:internal, category:tweak

#5127 Fix master DummyParser
  parse/DummyParsers.cpp
Labels: category:bug, status:merged, component:internal, priority:high

#5125 Rename resources Industry and Inluence to resolve ambiguousness with meters
  default/scripting/focs/_effects.pyi
  default/scripting/species/species_macros/troops.py
  default/scripting/techs/construction/OUTPOST.focs.py
  parse/EnumPythonParser.cpp
  test-scripting/species/species_macros/troops.py
Labels: category:refactoring, component:content scripting, status:merged, component:internal

#5130 [FOCS] Update type stubs to support building conversion
  default/scripting/focs/_buildings.pyi
  default/scripting/focs/_effects.pyi
  default/scripting/focs/_types.py
Labels: category:refactoring, component:content scripting, status:merged

#5132 Implement ValueRefInt+ValueRefDouble in Python FOCS parser
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, status:merged, component:internal

#5133 [FOCS] Convert buildings
  default/scripting/buildings/BLACK_HOLE_COLLAPSER.focs.py
  default/scripting/buildings/BLACK_HOLE_COLLAPSER.focs.txt
  default/scripting/buildings/BLACK_HOLE_POW_GEN.focs.py
  default/scripting/buildings/BLACK_HOLE_POW_GEN.focs.txt
  default/scripting/buildings/COLLECTIVE_NET.focs.py
  default/scripting/buildings/COLLECTIVE_NET.focs.txt
  default/scripting/buildings/COLONY_BASE.focs.py
  default/scripting/buildings/COLONY_BASE.focs.txt
  default/scripting/buildings/COLONY_INDEPENDENCE_DECREE.focs.py
  default/scripting/buildings/CONC_CAMP.focs.py
  default/scripting/buildings/CONC_CAMP.focs.txt
  default/scripting/buildings/CULTURE_ARCHIVES.focs.py
  default/scripting/buildings/CULTURE_ARCHIVES.focs.txt
  default/scripting/buildings/CULTURE_LIBRARY.focs.py
  default/scripting/buildings/CULTURE_LIBRARY.focs.txt
  default/scripting/buildings/ENCLAVE_VOID.focs.py
  default/scripting/buildings/ENCLAVE_VOID.focs.txt
  default/scripting/buildings/EVACUATION.focs.py
  default/scripting/buildings/EVACUATION.focs.txt
  default/scripting/buildings/FIELD_REPELLOR.focs.py
  default/scripting/buildings/FIELD_REPELLOR.focs.txt
  default/scripting/buildings/GAIA_TRANS.focs.py
  default/scripting/buildings/GAIA_TRANS.focs.txt
  default/scripting/buildings/buildings.py
  default/scripting/macros/enqueue.py
Labels: category:refactoring, component:content scripting
