Repository freeorion/freeorion, pull requests merged in 2025-01, with the labels that each got.

#5058 Add requirements for Boost.Random and Boost.Graph libraries
  CMakeLists.txt
Labels: category:bug, component:build system

#5061 Workaround for compiler error with MSVC and Boost 1.87 on v0.5.1
  util/SerializeEmpire.cpp
Labels: category:bug, component:internal

#5065 Lexer getter on v051
  parse/BuildingsParser.cpp
  parse/DoubleValueRefParser.cpp
  parse/EmpireStatsParser.cpp
  parse/EncyclopediaParser.cpp
  parse/FieldsParser.cpp
  parse/FleetPlansParser.cpp
  parse/IntValueRefParser.cpp
  parse/ItemsParser.cpp
  parse/Lexer.cpp
  parse/Lexer.h
  parse/MonsterFleetPlansParser.cpp
  parse/NamedValueRefParser.cpp
  parse/PoliciesParser.cpp
  parse/ShipDesignsParser.cpp
  parse/ShipHullsParser.cpp
  parse/ShipPartsParser.cpp
  parse/SpecialsParser.cpp
  parse/StringValueRefParser.cpp
Labels: category:bug, component:internal

#5069 Add requirements for Boost.Container library
  CMakeLists.txt
Labels: category:bug, component:build system, status:merged

#5070 Lexer Getter Instead of Static
  parse/BuildingsParser.cpp
  parse/DoubleValueRefParser.cpp
  parse/EmpireStatsParser.cpp
  parse/EncyclopediaParser.cpp
  parse/FieldsParser.cpp
  parse/FleetPlansParser.cpp
  parse/IntValueRefParser.cpp
  parse/ItemsParser.cpp
  parse/Lexer.cpp
  parse/Lexer.h
  parse/MonsterFleetPlansParser.cpp
  parse/NamedValueRefParser.cpp
  parse/PoliciesParser.cpp
  parse/ShipDesignsParser.cpp
  parse/ShipHullsParser.cpp
  parse/ShipPartsParser.cpp
  parse/SpecialsParser.cpp
  parse/StringValueRefParser.cpp
Labels: category:bug, component:internal

#5071 workaround for compiler error on master
  util/SerializeEmpire.cpp
Labels: category:bug, component:internal

#5072 don't log in Sound::Impl destruct, as this reportedly caused a crash on v0.5.1
  UI/Sound.cpp
Labels: category:bug, component:UI

#5073 don't log in Sound::Impl destruct, as this reportedly caused a crash on master
  UI/Sound.cpp
Labels: category:bug, component:UI

#5060 No parallal pedia article search
  UI/EncyclopediaDetailPanel.cpp
Labels: category:bug, component:UI

#5074 CI: Pin ubuntu version in Android Godot job
  .github/workflows/_build-android.yml
Labels: category:bug, component:infrastructure

#5075 CI: Pin ubuntu version in Android Godot job [v0.5.1]
  .github/workflows/_build-android.yml
Labels: category:bug, component:infrastructure

#5078 bump Python in/and CodeQL version
  .github/workflows/_codeql-analysis.yml
Labels: category:bug, component:infrastructure

#5079 Make tooltip text more useful
  default/stringtables/en.txt
Labels: component:UI, category:tweak

#5082 Force MapWnd Init Before Searching Pedia (on v0.5.1)
  UI/EncyclopediaDetailPanel.cpp
Labels: category:bug, component:UI
