Repository freeorion/freeorion, pull requests merged in 2025-05, with the labels that each got.

#5221 Cleanup version check for unsupported Python versions
  parse/BuildingsParser.cpp
  parse/EmpireStatsParser.cpp
  parse/PythonParser.cpp
  parse/SpeciesParser.cpp
  parse/TechsParser.cpp
Labels: status:merged, component:internal, category:tweak

#5225 internal compiler error workarounds
  universe/Conditions.cpp
Labels: category:bug, component:internal

#5226 Fix Boost.Process V1 usage for Boost 1.88
  util/Process.cpp
Labels: category:bug, status:merged, component:internal

#5231 Remove warnings by adding SR_GRAV_PULSE to upgrade dicts
  default/python/AI/AIDependencies.py
Labels: category:bug, component:AI

#5112 move shared bld black hole pow gen min stability to named values (0.5.1.1)
  default/scripting/buildings/BLACK_HOLE_POW_GEN.focs.txt
  default/scripting/macros/named_values.focs.txt
Labels: component:content scripting, status:merged, category:tweak

#5129 Update to SDK v16 with python 3.10.16
  .github/workflows/_build-android.yml
  .github/workflows/_build-windows-msvs.yml
  .github/workflows/_build-windows.yml
  CMakeLists.txt
  msvc2022/Common/Common.vcxproj
  msvc2022/FreeOrion/FreeOrion.vcxproj
  msvc2022/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2022/FreeOrionD/FreeOrionD.vcxproj
  msvc2022/Parsers/Parsers.vcxproj
  msvc2022/Test/Test.vcxproj
  util/Directories.cpp
Labels: category:refactoring, status:merged, component:internal

#5155 Use Boost.Process V1 for MacOS
  util/Process.cpp
Labels: category:refactoring, status:merged, component:internal

#5234 Add tests for different Python versions
  .github/workflows/_lint-python.yml
Labels: category:refactoring, component:infrastructure

#5110 Provide file name for Python FOCS parser
  parse/PythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5241 Raise minumum python version to 3.10
  BUILD.md
  CMakeLists.txt
  default/scripting/README.md
Labels: category:refactoring, status:merged, component:internal

#5244 Rewrite savegame coder, to provide better testing [v0.5.1]
  default/python/AI/savegame_codec/_decoder.py
  default/python/AI/savegame_codec/_definitions.py
  default/python/AI/savegame_codec/_encoder.py
  default/python/tests/AI/save_game_codec/test_savegame_manager.py
Labels: category:bug, component:AI, status:merged
