Repository freeorion/freeorion, pull requests merged in 2025-06, with the labels that each got.

#5242 Allow to see and dismiss stale ghost buildings [v0.5.1*]
  UI/BuildingsPanel.cpp
  UI/OptionsWnd.cpp
  UI/SidePanel.cpp
  default/stringtables/en.txt
Labels: category:bug, component:UI, status:merged, status:cherry-pick for release, priority:high

#5246 Fix compilation after dismiss stale building cherry-picked
  UI/BuildingsPanel.cpp
Labels: category:bug, status:merged, component:internal

#4945 Let ShipDesignAI considers flak, distractions for multi-target weapons
  default/python/AI/AIstate.py
  default/python/AI/CombatRatingsAI/__init__.py
  default/python/AI/CombatRatingsAI/_ratings.py
  default/python/AI/CombatRatingsAI/_ship_combat_stats.py
  default/python/AI/CombatRatingsAI/_targets.py
  default/python/AI/ShipDesignAI.py
Labels: category:refactoring, component:AI
