Repository freeorion/freeorion, pull requests merged in 2025-03, with the labels that each got.

#5138 Move BLD_BLACK_HOLE_POW_GEN_MIN_STABILITY valueref definition
  default/scripting/buildings/BLACK_HOLE_POW_GEN.focs.py
  default/scripting/macros/named_values.focs.txt
Labels: category:bug, component:content scripting

#5139 Accept ValueRefInt as argument for Max-Min-OneOf on floats in Python FOCS parser
  parse/ValueRefPythonParser.cpp
Labels: category:refactoring, component:internal

#5140 Accept ValueRefDouble in Turn condition in Python FOCS parser
  parse/ConditionPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5141 Initialize error handler within sub-interpreter context
  parse/GameRulesParser.cpp
  parse/PythonParser.cpp
  pyproject.toml
  python/PythonBase.cpp
  test-scripting/game_rules_failed.focs.py
  test/parse/TestDefaultPythonParser.cpp
  test/parse/TestPythonParser.cpp
  util/PythonCommon.cpp
  util/PythonCommon.h
Labels: category:refactoring, status:merged, component:internal

#5135 Fix stringtables build constraint for Species InterDesign Academy (six -> seven)
  default/stringtables/en.txt
Labels: category:bug, component:content scripting, status:merged, status:cherry-pick for release

#5147 Fix CI build on MSVS 14.43
  universe/ValueRefs.cpp
Labels: category:bug, status:merged, component:internal, status:cherry-pick for release

#5144 Use Boost.Process V1 for linux
  util/Process.cpp
Labels: category:refactoring, status:merged, component:internal

#5149 Fix default affiliation in GenerateSitRepMessage in Python FOCS parser
  parse/EffectPythonParser.cpp
Labels: status:merged, component:internal, category:tweak

#4867 [FOCS] WIP convert buildings (expected to fail builds)
  default/scripting/buildings/CONC_CAMP_REMNANT.focs.py
  default/scripting/buildings/CONC_CAMP_REMNANT.focs.txt
  default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.py
  default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.txt
  default/scripting/focs/_effects.pyi
Labels: category:refactoring, component:content scripting, status:work in progress

#5153 Implement ShortestPath(ValueRefInt, ValueRefInt) in Python FOCS parser
  parse/ValueRefPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5148 Use Boost.Process V1 for Windows
  util/Process.cpp
Labels: category:refactoring, status:merged, component:internal

#5159 [FOCS] Convert building
  default/scripting/buildings/GAS_GIANT_GEN.focs.py
  default/scripting/buildings/GAS_GIANT_GEN.focs.txt
  default/scripting/buildings/GATEWAY_VOID.focs.py
  default/scripting/buildings/GATEWAY_VOID.focs.txt
  default/scripting/buildings/GENOME_BANK.focs.py
  default/scripting/buildings/GENOME_BANK.focs.txt
  default/scripting/buildings/HYPER_DAM.focs.py
  default/scripting/buildings/HYPER_DAM.focs.txt
  default/scripting/buildings/INDUSTRY_CENTER.focs.py
  default/scripting/buildings/INDUSTRY_CENTER.focs.txt
  default/scripting/buildings/INTERSPECIES_ACADEMY.focs.py
  default/scripting/buildings/INTERSPECIES_ACADEMY.focs.txt
  default/scripting/buildings/NEUTRONIUM_EXTRACTOR.focs.py
  default/scripting/buildings/NEUTRONIUM_EXTRACTOR.focs.txt
  default/scripting/buildings/NEUTRONIUM_FORGE.focs.py
  default/scripting/buildings/NEUTRONIUM_FORGE.focs.txt
  default/scripting/buildings/NEUTRONIUM_SYNTH.focs.py
  default/scripting/buildings/NEUTRONIUM_SYNTH.focs.txt
  default/scripting/buildings/NOVA_BOMB_ACTIVATOR.focs.py
  default/scripting/buildings/NOVA_BOMB_ACTIVATOR.focs.txt
  default/scripting/buildings/PLANET_BEACON.focs.py
  default/scripting/buildings/PLANET_BEACON.focs.txt
  default/scripting/buildings/PLANET_CLOAK.focs.py
  default/scripting/buildings/PLANET_CLOAK.focs.txt
  default/scripting/buildings/PLANET_DRIVE.focs.py
  default/scripting/buildings/PLANET_DRIVE.focs.txt
  default/scripting/buildings/SCANNING_FACILITY.focs.py
  default/scripting/buildings/SCANNING_FACILITY.focs.txt
  default/scripting/buildings/SOL_ORB_GEN.focs.py
  default/scripting/buildings/SOL_ORB_GEN.focs.txt
  default/scripting/buildings/SPACE_ELEVATOR.focs.py
  default/scripting/buildings/SPACE_ELEVATOR.focs.txt
  default/scripting/buildings/SPATIAL_DISTORT_GEN.focs.py
  default/scripting/buildings/SPATIAL_DISTORT_GEN.focs.txt
  default/scripting/buildings/STARGATE.focs.py
  default/scripting/buildings/STARGATE.focs.txt
  default/scripting/buildings/STARLANE_NEXUS.focs.py
  default/scripting/buildings/STARLANE_NEXUS.focs.txt
  default/scripting/buildings/SUPER_TEST.focs.py
  default/scripting/buildings/SUPER_TEST.focs.txt
  default/scripting/buildings/TRANSFORMER.focs.py
  default/scripting/buildings/TRANSFORMER.focs.txt
  default/scripting/buildings/XENORESURRECTION_LAB.focs.py
  default/scripting/buildings/XENORESURRECTION_LAB.focs.txt
  default/scripting/buildings/buildings.py
  default/scripting/focs/_effects.pyi
Labels: category:refactoring, component:content scripting, status:merged

#5157 fix generated valueref descriptions like "Source's turns since annexa…
  universe/ValueRefs.cpp
Labels: category:bug, component:UI

#5161 Implement SetEmpireCapital effect in Python FOCS parser
  parse/EffectPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5162 Add COLONIZATION_POLICY_MULTIPLIER macros to Python FOCS parser
  default/scripting/macros/upkeep.py
Labels: category:refactoring, component:content scripting, status:merged

#5152 Implement empire statistics in Python FOCS parser and test it
  parse/EmpireStatsParser.cpp
  test-scripting/empire_statistics/ARMED_MONSTER_COUNT.focs.py
  test-scripting/empire_statistics/ARMED_MONSTER_COUNT.focs.txt
  test-scripting/focs/_empire_statistics.py
Labels: category:refactoring, status:merged, component:internal

#5167 Output warning if Pathfinder uses graph bigger than number of systems
  universe/Pathfinder.cpp
Labels: status:merged, component:internal, category:tweak

#5154 Add LIFECYCLE_MANIP_POPULATION_EFFECTS macros to Python FOCS parser
  default/scripting/focs/_effects.pyi
  default/scripting/macros/misc.py
Labels: category:refactoring, component:content scripting, status:merged

#5171 Fix address sanitizer error in pyhon FOCS parser
  parse/PythonParser.cpp
Labels: category:bug, status:merged, component:internal, status:cherry-pick for release

#5173 fix repeatedly creating strings and passing mismatched iterators
  UI/SaveFileDialog.cpp
Labels: category:bug, status:merged, component:internal, status:cherry-pick for release

#5165 cmake: Remove old boost version handling for...
  CMakeLists.txt
Labels: component:build system, status:merged, category:tweak

#5175 [FOCS] Convert building
  default/scripting/buildings/LIGHTHOUSE.focs.py
  default/scripting/buildings/LIGHTHOUSE.focs.txt
  default/scripting/buildings/MEGALITH.focs.py
  default/scripting/buildings/MEGALITH.focs.txt
  default/scripting/buildings/MILITARY_COMMAND.focs.py
  default/scripting/buildings/MILITARY_COMMAND.focs.txt
  default/scripting/buildings/NEST_ERADICATOR.focs.py
  default/scripting/buildings/NEST_ERADICATOR.focs.txt
  default/scripting/buildings/REGIONAL_ADMIN.focs.py
  default/scripting/buildings/REGIONAL_ADMIN.focs.txt
  default/scripting/buildings/SCRYING_SPHERE.focs.py
  default/scripting/buildings/SCRYING_SPHERE.focs.txt
  default/scripting/buildings/STOCKPILING_CENTER.focs.py
  default/scripting/buildings/STOCKPILING_CENTER.focs.txt
  default/scripting/buildings/TRANSLATOR.focs.py
  default/scripting/focs/_buildings.pyi
  default/scripting/focs/_effects.pyi
  default/scripting/macros/enqueue.py
Labels: category:refactoring, component:content scripting, status:merged

#5176 Make Windows CI build fail on failed tests
  .github/workflows/_build-windows.yml
Labels: category:bug, component:infrastructure, status:merged, status:cherry-pick for release

#5182 Fix address issue in PathFinder
  universe/Pathfinder.cpp
Labels: category:bug, status:merged, component:internal, priority:high

#5180 CI: Restore Manjaro Docker image
  .github/workflows/_build-docker.yml
Labels: component:infrastructure, status:merged, status:cherry-pick for release, category:tweak

#5183 Try to use address sanitizer in CI
  .github/workflows/_build-ubuntu.yml
Labels: component:infrastructure, status:merged, status:cherry-pick for release, category:tweak

#5184 Add new badges for README.md
  .github/ISSUE_TEMPLATE/release.md
  README.md
Labels: category:feature, component:infrastructure, status:merged, status:cherry-pick for release

#5181 Add option for alternative AI executable
  default/stringtables/en.txt
  server/ServerApp.cpp
  server/dmain.cpp
Labels: status:merged, component:internal, category:tweak

#5177 [FOCS] Convert buildings
  default/scripting/buildings/LIGHTHOUSE.focs.py
  default/scripting/buildings/LIGHTHOUSE.focs.txt
  default/scripting/buildings/MEGALITH.focs.py
  default/scripting/buildings/MEGALITH.focs.txt
  default/scripting/buildings/MILITARY_COMMAND.focs.py
  default/scripting/buildings/MILITARY_COMMAND.focs.txt
  default/scripting/buildings/NEST_ERADICATOR.focs.py
  default/scripting/buildings/NEST_ERADICATOR.focs.txt
  default/scripting/buildings/REGIONAL_ADMIN.focs.py
  default/scripting/buildings/REGIONAL_ADMIN.focs.txt
  default/scripting/buildings/SCRYING_SPHERE.focs.py
  default/scripting/buildings/SCRYING_SPHERE.focs.txt
  default/scripting/buildings/STOCKPILING_CENTER.focs.py
  default/scripting/buildings/STOCKPILING_CENTER.focs.txt
  default/scripting/focs/_buildings.pyi
  default/scripting/focs/_effects.pyi
  default/scripting/macros/enqueue.py
Labels: category:refactoring, component:content scripting, status:merged

#5179 Fix LeastJumpsPath - for human and AI client use system graph
  universe/Pathfinder.cpp
Labels: category:bug, component:internal, priority:high

#5186 Implement Statistic(TypeReturn, TypeValue, StatisticType, value=ValueRef[TypeValue], condition=Condition) in Python FOCS parser
  parse/ValueRefPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5192 Deduplicate Parsing Code
  parse/ConditionPythonParser.cpp
Labels: status:merged, component:internal, category:tweak
