Repository freeorion/freeorion, pull requests merged in 2025-04, with the labels that each got.

#5193 Implement ValueRefPlanetType != ValueRefPlantetType in Python FOCS parser
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:refactoring, status:merged, component:internal

#5194 Introduce Const(type, value) to Python FOCS parser
  parse/ValueRefPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5160 [FOCS] Convert building
  check/focs_dump_parser/_tools.py
  check/focs_dump_parser/make_diff.py
  default/scripting/buildings/IMPERIAL_PALACE.focs.py
  default/scripting/buildings/IMPERIAL_PALACE.focs.txt
  default/scripting/buildings/STARLANE_BORE.focs.py
  default/scripting/buildings/STARLANE_BORE.focs.txt
  default/scripting/buildings/TERRAFORM.focs.py
  default/scripting/buildings/TERRAFORM.focs.txt
  default/scripting/buildings/TRANSLATOR.focs.py
  default/scripting/buildings/TRANSLATOR.focs.txt
  default/scripting/focs/_buildings.pyi
  default/scripting/focs/_effects.pyi
  default/scripting/focs/_types.py
  default/scripting/macros/enqueue.py
Labels: category:refactoring, component:content scripting, status:merged

#5196 Bump ruff
  .github/workflows/_lint-python.yml
  .pre-commit-config.yaml
  default/python/AI/fleet_orders.py
  default/python/AI/target.py
  default/python/requirements-dev.txt
  default/python/tests/AI/save_game_codec/test_savegame_manager.py
  pyproject.toml
Labels: component:AI, status:merged, category:tweak

#5199 [FOCS] Convert shipyards part 1
  default/scripting/buildings/shipyards/ASTEROID.focs.py
  default/scripting/buildings/shipyards/ASTEROID.focs.txt
  default/scripting/buildings/shipyards/ASTEROID_REF.focs.py
  default/scripting/buildings/shipyards/ASTEROID_REF.focs.txt
  default/scripting/buildings/shipyards/CON_ADV_ENGINE.focs.py
  default/scripting/buildings/shipyards/CON_ADV_ENGINE.focs.txt
  default/scripting/buildings/shipyards/CON_GEOINT.focs.py
  default/scripting/buildings/shipyards/CON_GEOINT.focs.txt
  default/scripting/buildings/shipyards/CON_NANOROBO.focs.py
  default/scripting/buildings/shipyards/CON_NANOROBO.focs.txt
  default/scripting/buildings/shipyards/ORGANIC_CEL_GRO.focs.py
  default/scripting/buildings/shipyards/ORGANIC_CEL_GRO.focs.txt
  default/scripting/buildings/shipyards/ORGANIC_ORB_INC.focs.py
  default/scripting/buildings/shipyards/ORGANIC_ORB_INC.focs.txt
  default/scripting/buildings/shipyards/ORGANIC_XENO_FAC.focs.py
  default/scripting/buildings/shipyards/ORGANIC_XENO_FAC.focs.txt
  default/scripting/focs/_effects.pyi
  default/scripting/macros/enqueue.py
Labels: category:refactoring, component:content scripting, status:merged

#5201 Implement CanProduceShips condition in Python FOCS parser
  parse/ConditionPythonParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5202 CI: Restore Godot3 test for Fedora Rawhide Docker
  .github/docker/fedora-rawhide/Dockerfile
  .github/workflows/_build-docker.yml
Labels: component:infrastructure, status:cherry-pick for release, category:tweak

#5204 [FOCS] Convert shipyards
  default/scripting/buildings/buildings.macros
  default/scripting/buildings/shipyards/BASE.focs.py
  default/scripting/buildings/shipyards/BASE.focs.txt
  default/scripting/buildings/shipyards/ENERGY_COMP.focs.py
  default/scripting/buildings/shipyards/ENERGY_COMP.focs.txt
  default/scripting/buildings/shipyards/ENERGY_SOLAR.focs.py
  default/scripting/buildings/shipyards/ENERGY_SOLAR.focs.txt
  default/scripting/buildings/shipyards/ORBITAL_DRYDOCK.focs.py
  default/scripting/buildings/shipyards/ORBITAL_DRYDOCK.focs.txt
  default/scripting/focs/_effects.pyi
Labels: category:refactoring, component:content scripting

#5207 [CI] Bump static check tools
  .pre-commit-config.yaml
  default/python/requirements-dev.txt
Labels: component:infrastructure, status:merged, status:cherry-pick for release, category:tweak

#5210 Drop old FOCS parser for buildings types
  parse/BuildingsParser.cpp
Labels: category:refactoring, status:merged, component:internal

#5212 Test optional result value before dereference
  test/parse/TestDefaultPythonParser.cpp
  test/parse/TestPythonParser.cpp
Labels: status:merged, component:internal, category:tweak

#5214 Fix parser type PlanetType -> PlanetSize
  parse/PythonParser.cpp
  parse/ValueRefPythonParser.cpp
  parse/ValueRefPythonParser.h
Labels: category:bug, status:help wanted, component:content scripting, component:internal

#5215 Use ClientFSMEvents only in the GG client
  client/CMakeLists.txt
  client/human/CMakeLists.txt
  client/human/ClientFSMEvents.cpp
  client/human/ClientFSMEvents.h
  client/human/HumanClientFSM.h
  msvc2022/FreeOrion/FreeOrion.vcxproj
  msvc2022/FreeOrion/FreeOrion.vcxproj.filters
  msvc2022/FreeOrionCA/FreeOrionCA.vcxproj
  msvc2022/FreeOrionCA/FreeOrionCA.vcxproj.filters
  test/system/CMakeLists.txt
Labels: status:merged, component:internal, category:tweak

#5217 CI: Update Ubuntu used for address sanitizer to 24.04
  .github/workflows/_build-ubuntu.yml
  .github/workflows/ubuntu-24.04-install-build.sh
Labels: component:infrastructure, status:merged, status:cherry-pick for release, category:tweak
